In [1]:
import pandas as pd 
import numpy as np
import sys
import os
from pathlib import Path
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor

sys.path.append(os.path.abspath("src"))
pd.set_option("display.max_columns", None)

# Load data

In [2]:
# Schools

path_sch_18 = "/Users/Lenovo/Desktop/Personal/PISA_Research/cy07_msu_sch_qqq.sas7bdat"
path_sch_22 = "/Users/Lenovo/Desktop/Personal/PISA_Research/CY08MSP_SCH_QQQ.SAS7BDAT"

df_sch_2018 = pd.read_sas(path_sch_18, format="sas7bdat")
df_sch_2022 = pd.read_sas(path_sch_22, format="sas7bdat")

In [3]:
# Students

path_stu_18 = "/Users/Lenovo/Desktop/Personal/PISA_Research/cy07_msu_stu_qqq.sas7bdat"
path_stu_22 = "/Users/Lenovo/Desktop/Personal/PISA_Research/CY08MSP_STU_QQQ.SAS7BDAT"

df_stu_2018 = pd.read_sas(path_stu_18, format="sas7bdat")
df_stu_2022 = pd.read_sas(path_stu_22, format="sas7bdat")

In [4]:
print(f'School 2018 data: {df_sch_2018.shape}')
print(f'School 2022 data: {df_sch_2022.shape}')
print(f'Student 2018 data: {df_stu_2018.shape}')
print(f'Student 2022 data: {df_stu_2022.shape}')

School 2018 data: (21903, 198)
School 2022 data: (21629, 431)
Student 2018 data: (612004, 1119)
Student 2022 data: (613744, 1278)

In [5]:
df_sch_2018.head()

,CNTRYID,CNT,CNTSCHID,CYC,NatCen,Region,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC161Q01SA,SC161Q02SA,SC161Q03SA,SC161Q04SA,SC161Q05SA,SC162Q01SA,SC155Q01HA,SC155Q02HA,SC155Q03HA,SC155Q04HA,SC155Q05HA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC156Q01HA,SC156Q02HA,SC156Q03HA,SC156Q04HA,SC156Q05HA,SC156Q06HA,SC156Q07HA,SC156Q08HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC012Q07TA,SC042Q01TA,SC042Q02TA,SC154Q01HA,SC154Q02WA,SC154Q03WA,SC154Q04WA,SC154Q05WA,SC154Q06WA,SC154Q07WA,SC154Q08WA,SC154Q09HA,SC154Q10WA,SC154Q11HA,SC036Q01TA,SC036Q02TA,SC036Q03NA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC037Q10NA,SC165Q01HA,SC165Q02HA,SC165Q03HA,SC165Q04HA,SC165Q05HA,SC165Q06HA,SC165Q07HA,SC165Q08HA,SC165Q09HA,SC165Q10HA,SC166Q02HA,SC166Q03HA,SC166Q05HA,SC166Q06HA,SC167Q01HA,SC167Q02HA,SC167Q03HA,SC167Q04HA,SC167Q05HA,SC167Q06HA,SC158Q01HA,SC158Q02HA,SC158Q04HA,SC158Q07HA,SC158Q08HA,SC158Q09HA,SC158Q12HA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC048Q01NA,SC048Q02NA,SC048Q03NA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q04NA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC018Q05NA01,SC018Q05NA02,SC018Q06NA01,SC018Q06NA02,SC018Q07NA01,SC018Q07NA02,SC025Q01NA,SC159Q01HA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q12IA,SC053Q13IA,SC053Q09TA,SC053Q10TA,SC053Q14IA,SC053Q15IA,SC053Q16IA,SC053D11TA,SC150Q01IA,SC150Q02IA,SC150Q03IA,SC150Q04IA,SC150Q05IA,SC164Q01HA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,SC152Q01HA,SC160Q01WA,SC052Q01NA,SC052Q02NA,SC052Q03HA,PRIVATESCH,SCHLTYPE,STRATIO,SCHSIZE,RATCMP1,RATCMP2,TOTAT,PROATCE,PROAT5AB,PROAT5AM,PROAT6,CLSIZE,CREACTIV,EDUSHORT,STAFFSHORT,STUBEHA,TEACHBEHA,SCMCEG,W_SCHGRNRABWT,W_FSTUWT_SCH_SUM,SENWT,VER_DAT,M,BOOKID
0,8.0,b'ALB',800002.0,b'07MS',b'000800',800.0,b'ALB0109',b'0080000',0.0,2.0,140.0,1.0,1.0,95.0,0.0,5.0,0.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,1.0,3.0,2.0,3.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,40.0,NaN,7.0,0.0,0.0,0.0,1.0,1.0,26.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,98.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,b'0008002',2.0,2.0,2.0,2.0,2.0,0.0,70.0,70.0,100.0,0.0,2.0,NaN,2.0,2.0,2.0,b'public',3.0,NaN,NaN,NaN,0.0000,26.0,0.0000,0.0000,0.1154,0.0,18.0,1.0,1.2478,-1.4551,-1.1797,-2.0409,-1.0391,7.98891,115.10603,24.81933,b' 09MAY19:11:20:57',NaN,NaN
1,8.0,b'ALB',800003.0,b'07MS',b'000800',800.0,b'ALB0109',b'0080000',0.0,2.0,140.0,1.0,1.0,NaN,NaN,100.0,NaN,1.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,0.0,0.0,0.0,0.0,NaN,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,NaN,3.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,NaN,NaN,NaN,5.0,70.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,6.0,NaN,6.0,NaN,2.0,NaN,2.0,NaN,0.0,NaN,19.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,b'0008002',1.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,b'public',3.0,NaN,NaN,NaN,NaN,6.0,1.0000,0.3333,0.3333,0.0,13.0,1.0,0.6221,-1.4551,2.1196,2.5150,-1.0542,6.50492,26.01970,20.20900,b' 09MAY19:11:20:57',NaN,NaN
2,8.0,b'ALB',800004.0,b'07MS',b'000800',800.0,b'ALB0211',b'0080000',0.0,2.0,140.0,1.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,3.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,109.0,96.0,NaN,2.0,85.0,37.0,0.0,0.0,0.0,0.0,2.0,0.0,21.0,0.0,21.0,0.0,11.0,0.0,10.0,0.0,0.0,0.0,100.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,b'0008002',1.0,1.0,1.0,1.0,1.0,1.0,62.0,80.0,60.0,90.0,1.0,1.0,1.0,1.0,1.0,b'public',3.0,9.7619,205.0,0.0000,NaN,21.0,1.0000,0.5238,0.4762,0.0,18.0,2.0,0.4591,-1.4551,-0.6199,-0.4415,0.9042,6.64198,99.62974,20.63480,b' 09MAY19:11:20:57',NaN,NaN
3,8.0,b'ALB',800005.0,b'07MS',b'000800',800.0,b'ALB0107',b'0080000',0.0,2.0,140.0,2.0,1.0,100.0,0.0,0.0,0.0,3.0,3.0,2.0,3.0,4.0,3.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,2.0,25.0,NaN,15.0,5.0,0.0,0.0,1.0,4.0,34.0,1.0,21.0,0.0,12.0,1.0,22.0,0.0,0.0,0.0,100.0,1.0,3.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,b'0008001',2.0,2.0,2.0,2.0,2.0,1.0,65.0,60.0,58.0,55.0,1.0,3.0,2.0,1.0,1.0,b'public',3.0,NaN,NaN,NaN,0.3333,34.5,0.6087,0.3623,0.6377,0.0,23.0,1.0,1.3065,1.2432,-0.2682,-0.0452,-1.5648,5.93762,66.50133,18.44654,b' 09MAY19:11:20:57',NaN,NaN
4,8.0,b'ALB',800006.0,b'07MS',b'000800',800.0,b'ALB0105',b'0080000',0.0,2.0,140.0,2.0,1.0,100.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,2.0,2.0,2.0,4.0,3.0,4.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,175.0,140.0,0.0,1.0,12.0,39.0,1.0,1.0,1.0,0.0,1.0,1.0,17.0,1.0,17.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,87.0,2.0,6.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,b'0008001',2.0,2.0,2.0,2.0,2.0,NaN,97.0,97.0,99.0,2.0,1.0,3.0,2.0,2.0,1.0,b'public',3.0,18.0000,315.0,0.0256,1.0000,17.5,1.0000,0.0000,0.1714,0.0,38.0,3.0,-0.2376,-1.4551,-1.3196,-2.0409,0.9042,14.61508,277.68645,45.40500,b' 09MAY19:11:20:57',NaN,NaN

In [6]:
df_sch_2018['EDUSHORT'].max()

np.float64(3.5229)

In [7]:
df_sch_2022.head()

,CNT,CNTRYID,CNTSCHID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,ADMINMODE,LANGTEST_QQQ,SC001Q01TA,SC013Q01TA,SC014Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC011Q01TA,SC002Q01TA,SC002Q02TA,SC211Q01JA,SC211Q02JA,SC211Q03JA,SC211Q04JA,SC211Q05JA,SC211Q06JA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC018Q08JA01,SC018Q08JA02,SC018Q09JA01,SC018Q09JA02,SC018Q10JA01,SC018Q10JA02,SC182Q01WA01,SC182Q01WA02,SC182Q06WA01,SC182Q06WA02,SC182Q07JA01,SC182Q07JA02,SC182Q08JA01,SC182Q08JA02,SC182Q09JA01,SC182Q09JA02,SC182Q10JA01,SC182Q10JA02,SC168Q01JA,SC168Q02JA,SC168Q03JA,SC168Q04JA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC012Q08JA,SC012Q10JA,SC012Q11JA,SC012Q12JA,SC185Q01WA,SC185Q02WA,SC185Q03WA,SC185Q04WA,SC185Q05WA,SC202Q01JA,SC202Q02JA,SC202Q03JA,SC202Q04JA,SC202Q05JA,SC202Q06JA,SC202Q07JA,SC202Q08JA,SC202Q09JA,SC202Q10JA,SC202Q11JA,SC202Q12JA,SC201Q01JA,SC201Q03JA,SC201Q04JA,SC201Q05JA,SC201Q06JA,SC201Q07JA,SC201Q11JA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q08JA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC190Q01JA,SC190Q02JA,SC190Q05JA,SC190Q06JA,SC190Q07JA,SC190Q08JA,SC190Q09JA,SC190Q10JA,SC190Q11JA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC037Q11JA,SC200Q01JA,SC200Q02JA,SC200Q03JA,SC200Q04JA,SC032Q01TA,SC032Q02TA,SC032Q03TA,SC032Q04TA,SC193Q01WA,SC193Q02WA,SC193Q03WA,SC193Q04WA,SC193Q05WA,SC193Q06WA,SC193Q07WA,SC025Q01NA,SC025Q02NA,SC027Q02NA,SC027Q03NA,SC027Q04NA,SC183Q02JA,SC183Q03JA,SC183Q04JA,SC184Q01JA,SC184Q02JA,SC184Q03JA,SC184Q04JA,SC184Q05JA,SC184Q06JA,SC184Q07JA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC017Q09JA,SC017Q10JA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC172Q02JA,SC172Q03JA,SC172Q04JA,SC172Q05JA,SC172Q06JA,SC172Q07JA,SC173Q01JA,SC173Q02JA,SC173Q03JA,SC173Q04JA,SC173Q05JA,SC173Q06JA,SC064Q05WA,SC064Q06WA,SC064Q01TA,SC064Q02TA,SC064Q04NA,SC064Q03TA,SC064Q07WA,SC192Q01JA,SC192Q02JA,SC192Q03JA,SC192Q04JA,SC192Q05JA,SC192Q06JA,SC175Q01JA,SC175Q02JA,SC176Q01JA,SC003Q01TA,SC174Q01JA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q05NA,SC053Q06NA,SC053Q07TA,SC053Q08TA,SC053Q09TA,SC053Q10TA,SC053D11TA,SC212Q01JA,SC212Q02JA,SC212Q03JA,SC034Q01NA,SC034Q02NA,SC034Q03TA,SC034Q04TA,SC035Q01NA,SC035Q01NB,SC035Q02TA,SC035Q02TB,SC035Q03TA,SC035Q03TB,SC035Q04TA,SC035Q04TB,SC035Q05TA,SC035Q05TB,SC035Q06TA,SC035Q06TB,SC035Q07TA,SC035Q07TB,SC035Q08TA,SC035Q08TB,SC035Q09NA,SC035Q09NB,SC035Q10TA,SC035Q10TB,SC035Q11NA,SC035Q11NB,SC042Q01TA,SC042Q02TA,SC187Q01WA,SC187Q02WA,SC187Q03WA,SC187Q04WA,SC177Q01JA,SC177Q02JA,SC177Q03JA,SC188Q01JA,SC188Q02JA,SC188Q03JA,SC188Q04JA,SC188Q05JA,SC188Q06JA,SC188Q07JA,SC188Q08JA,SC188Q09JA,SC188Q10JA,SC188Q11JA,SC195Q01JA,SC195Q02JA,SC195Q03JA,SC195Q04JA,SC198Q01JA,SC198Q02JA,SC198Q03JA,SC178Q01JA,SC178Q02JA,SC180Q01JA,SC181Q01JA,SC181Q02JA,SC181Q03JA,SC189Q02WA,SC189Q03WA,SC189Q04WA,SC189Q01JA,SC189Q05JA,SC189Q06JA,SC169Q01JA,SC210Q01JA,SC170Q01JA,SC171Q01JA,SC171Q02JA,SC171Q03JA,SC171Q04JA,SC204Q01JA,SC204Q02JA,SC204Q05JA,SC204Q06JA,SC205Q01JA,SC205Q02JA,SC205Q03JA,SC205Q05JA,SC205Q06JA,SC205Q07JA,SC207Q01JA,SC207Q02JA,SC207Q03JA,SC207Q04JA,SC207Q05JA,SC207Q06JA,SC207Q07JA,SC207Q08JA,SC208Q01JA,SC208Q02JA,SC208Q03JA,SC208Q04JA,SC208Q05JA,SC208Q06JA,SC208Q07JA,SC208Q08JA,SC208Q09JA,SC213Q01JA,SC213Q02JA,SC214Q01JA,SC214Q02JA,SC214Q03JA,SC215Q01JA,SC215Q02JA,SC215Q03JA,SC215Q04JA,SC215Q05JA,SC215Q06JA,SC215Q07JA,SC215Q08JA,SC216Q01JA,SC216Q02JA,SC216Q03JA,SC216Q04JA,SC216Q05JA,SC216Q06JA,SC216Q07JA,SC216Q08JA,SC216Q09JA,SC217Q01JA,SC217Q02JA,SC217Q03JA,SC217Q04JA,SC217Q05JA,SC217Q06JA,SC217Q07JA,SC217Q08JA,SC217Q10JA,SC218Q01JA,SC219Q01JA,SC220Q01JA,SC221Q01JA,SC221Q02JA,SC221Q03JA,SC221Q04JA,SC222Q01JA,SC222Q02JA,SC222Q03JA,SC222Q04JA,SC222Q05JA,SC223Q01JA,SC223Q02JA,SC223Q03JA,SC223Q04JA,SC223Q05JA,SC223Q06JA,SC223Q07JA,SC223Q08JA,SC223Q09JA,SC223Q10JA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC224Q01JA,SC209Q04JA,SC209Q05JA,SC209Q06JA,PRIVATESCH,SCHLTYPE,SCHSIZE,TOTAT,PROATCE,PROPAT6,PROPAT7,PROPAT8,STRATIO,TOTMATH,PROPMATH,SMRATIO,TOTSTAFF,PROPSUPP,PROADMIN,PROMGMT,PROOSTAF,SCHSEL,SCHAUTO,TCHPART,SRESPCUR,SRESPRES,EDULEAD,INSTLEAD,ENCOURPG,RATCMP1,RATCMP2,RATTAB,DIGDVPOL,TEAFDBK,MTTRAIN,DMCVIEWS,NEGSCLIM,STAFFSHORT,EDUSHORT,STUBEHA,TEACHBEHA,MCLSIZE,CLSIZE,STDTEST,TDTEST,CREACTIV,ALLACTIV,MACTIV,MATHEXC,ABGMATH,BCREATSC,CREENVSC,ACTCRESC,OPENCUL,SCSUPRTED,SCSUPRT,PROBSCRI,SCPREPBP,SCPREPAP,DIGPREP,W_SCHGRNRABWT,W_FSTUWT_SCH_SUM,W_FSTUWT_SCH_N,SENWT,VER_DAT
0,b'ALB',8.0,800001.0,b'08MS',b'000800',b'ALB05',b'0080000',800.0,0.0,2.0,140.0,3.0,1.0,4.0,100.0,0.0,0.0,0.0,3.0,303.0,349.0,NaN,NaN,14.0,NaN,32.0,NaN,38.0,1.0,38.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,4.0,1.0,3.0,5.0,2.0,3.0,1.0,2.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,1.0,2.0,1.0,2.0,4.0,1.0,6.0,6.0,6.0,6.0,6.0,6.0,1.0,2.0,6.0,6.0,3.0,4.0,4.0,4.0,3.0,4.0,3.0,179.0,28.0,28.0,21.0,3.0,4.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,3.0,3.0,4.0,3.0,100.0,100.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,3.0,2.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,1.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,4.0,5.0,5.0,27.0,64.0,36.0,72.0,21.0,36.0,13.0,2.0,3.0,3.0,2.0,3.0,3.0,45.0,45.0,5.0,5.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,b'0080002',2.0,2.0,1.0,3.0,1.0,3.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,1.0,3.0,4.0,3.0,2.0,2.0,4.0,4.0,3.0,3.0,4.0,2.0,3.0,2.0,1.0,3.0,3.0,3.0,4.0,2.0,2.0,1.0,95.0,5.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,1.0,4.0,1.0,4.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,4.0,3.0,3.0,2.0,3.0,3.0,90.0,0.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,3.0,1.0,1.0,1.0,1.0,4.0,3.0,3.0,4.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,b'public',3.0,652.0,38.5,1.0000,0.0779,0.0779,0.0519,16.9351,5.0,0.1299,100.0,13.0,0.3077,0.0769,0.2308,0.3846,3.0,-0.4178,NaN,0.5,0.3333,0.9403,0.9572,0.9212,0.1564,1.00,0.1173,-0.0598,0.8961,-0.0313,0.4944,-1.6916,-0.2968,1.2048,0.6058,-0.5488,33.0,33.0,0.9589,0.1717,0.0,-0.3384,1.0,NaN,3.0,-0.3682,0.3518,-1.0019,0.5652,2.0,2.0,0.7965,-0.8314,0.8462,0.5908,1.43376,160.58080,41.0,5.76182,b'03MAY23:10:11:34'
1,b'ALB',8.0,800002.0,b'08MS',b'000800',b'ALB07',b'0080000',800.0,0.0,2.0,140.0,1.0,1.0,4.0,90.0,5.0,5.0,0.0,2.0,88.0,95.0,NaN,NaN,NaN,NaN,20.0,NaN,16.0,0.0,16.0,0.0,3.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,2.0,2.0,5.0,5.0,6.0,6.0,3.0,3.0,1.0,6.0,1.0,2.0,6.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,59.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,3.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,2.0,2.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,5.0,5.0,5.0,2.0,80.0,100.0,100.0,70.0,80.0,100.0,80.0,2.0,2.0,2.0,2.0,2.0,2.0,45.0,45.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,b'0080001',2.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,3.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,1.0,90.0,10.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,70.0,10.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,3.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,b'public',3.0,183.0,16.0,1.0000,0.4375,0.2500,0.0000,11.4375,3.0,0.1875,61.0,4.0,0.2500,0.0000,0.2500,0.5000,3.0,-0.5280,NaN,1.0,0.6000,-0.1642,-0.1660,-0.3835,0.0000,0.00,0.0000,1.3483,0.4869,1.0982,1.2535,-1.6916,-1.4551,2.9595,-0.0956,-2.0409,13.0,13.0,0.7237,1.5226,1.0,0.4074,4.0,3.0,3.0,-0.9046,2.1631,-0.6079,0.0911,2.0,1.0,-0.5687,-0.8314,0.8462,-0.3475,2.85278,133.71140,36.0,11.46442,b'03MAY23:10:11:34'
2,b'ALB',8.0,800003.0,b'08MS',b'000800',b'ALB06',b'0080000',800.0,0.0,2.0,140.0,2.0,2.0,2.0,0.0,0.0,10.0,90.0,1.0,74.0,47.0,77.0,NaN,1.0,NaN,64.0,NaN,17.0,0.0,17.0,0.0,4.0,0.0,13.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,11.0,22.0,22.0,0.0,9.0,9.0,18.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,100.0,100.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,4.0,2.0,3.0,3.0,3.0,29.0,37.0,16.0,38.0,13.0,43.0,55.0,2.0,2.0,3.0,2.0,2.0,2.0,45.0,45.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,b'0080002',2.0,1.0,1.0,3.0,4.0,3.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,1.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,3.0,4.0,4.0,5.0,2.0,1.0,1.0,90.0,10.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,2.0,2.0,3.0,2.0,2.0,6.0,6.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,115.0,6.0,5.0,5.0,5.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,8.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,1.0,2.0,1.0,b'private',1.0,121.0,17.0,1.0000,1.0000,0.7647,0.0000,7.1176,2.0,0.1176,60.5,4.0,0.0000,0.2500,0.7500,0.0000,3.0,1.4001,NaN,5.0,7.0000,-0.1686,-0.2686,-0.0248,2.0000,1.00,0.0000,0.0889,0.4569,0.0794,0.0836,2.0223,0.2833,0.6299,1.3399,0.2266,13.0,13.0,-0.2921,-0.9681,2.0,-0.8108,0.0,NaN,3.0,0.1019,0.4118,-0.2771,-0.8952,1.0,1.0,0.1896,-0.8314,-0.8711,0.4409,7.40007,25.61079,3.0,29.73857,b'03MAY23:10:11:34'
3,b'ALB',8.0,800004.0,b'08MS',b'000800',b'ALB05',b'0080000',800.0,0.0,2.0,140.0,3.0,1.0,4.0,100.0,0.0,0.0,0.0,1.0,583.0,491.0,11.0,2.0,16.0,NaN,4.0,NaN,63.0,1.0,60.0,0.0,2.0,0.0,13.0,0.0,0.0,0.0,8.0,0.0,8.0,0.0,8.0,0.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,4.0,7.0,3.0,3.0,3.0,1.0,3.0,2.0,3.0,1.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,6.0,6.0,3.0,3.0,2.0,6.0,1.0,2.0,6.0,6.0,5.0,4.0,3.0,3.0,2.0,2.0,2.0,136.0,25.0,16.0,0.0,0.0,2.0,16.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,3.0,3.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,80.0,85.0,85.0,85.0,30.0,100.0,NaN,2.0,2.0,2.0,2.0,3.0,3.0,45.0,45.0,4.0,4.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,b'0080001',2.0,2.0,1.0,3.0,1.0,3.0,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,2.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,2.0,NaN,NaN,1.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,4.0,4.0,1.0,1.0,3.0,2.0,2.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0,84.0,16.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,3.0,3.0,2.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,b'public',3.0,1074.0,63.5,0.9449,0.2362,0.2047,0.0000,16.9134,8.0,0.1260,100.0,11.0,0.0000,0.0000,0.3636,0.6364,3.0,0.2405,NaN,0.5,1.6667,0.0243,0.1402,0.4919,0.1838,0.64,0.0000,1.3483,0.4795,1.0982,2.1585,-0.8905,-1.4551,1.6863,-0.7912,-0.9138,28.0,28.0,-0.1123,1.4914,0.0,-0.1653,3.0,1.0,3.0,-0.9046,1.1180,-1.1844,-0.4642,NaN,NaN,NaN,NaN,NaN,-0.7414,4.34319,192.24130,39.0,17.45392,b'03MAY23:10:11:34'
4,b'ALB',8.0,800005.0,b'08MS',b'000800',b'ALB03',b'0080000',800.0,0.0,2.0,140.0,3.0,1.0,4.0,75.0,10.0,10.0,5.0,1.0,166.0,151.0,NaN,1.0,1.0,1.0,3.0,NaN,26.0,2.0,26.0,0.0,12.0,2.0,14.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,4.0,2.0,0.0,3.0,3.0,1.0,2.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,NaN,2.0,3.0,6.0,6.0,1.0,2.0,6.0,6.0,3.0,4.0,3.0,2.0,2.0,3.0,2.0,38.0,2.0,2.0,9.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,2.0,4.0,4.0,1.0,NaN,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,45.0,5.0,20.0,100.0,30.0,70.0,75.0,2.0,2.0,3.0,2.0,3.0,2.0,45.0,45.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,b'0080001',1.0,1.0,1.0,2.0,2.0,3.0,5.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,3.0,1.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,2.0,3.0,4.0,5.0,2.0,1.0,1.0,100.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,4.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,5.0,3.0,6.0,4.0,6.0,6.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,5.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,1.0,1.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,b'public',3.0,317.0,27.0,0.9630,NaN,0.5556,0.0370,11.7407,2.0,0.0741,100.0,8.0,0.2500,0.5000,0.2500,0.0000,3.0,-0.0472,NaN,0.5,NaN,-0.4247,-0.4562,0.3802,0.0526,1.00,0.2368,1.3483,1.2115,0.1756,2.1585,-0.8905,-0.2129,1.2478,-2.0719,-0.5079,18.0,18.0,0.8580,-0.2225,1.0,-0.5672,3.0,3.0,1.0,0.1019,0.4118,1.0543,0.4217,2.0,2.0,0.6649,-0.8314,0.8462,-0.0102,7.52060,45.69535,5.0,30.22293,b'03MAY23:10:11:34'

In [8]:
df_sch_2022['CREACTIV'].max()

np.float64(3.0)

In [9]:
df_stu_2018.head()

,CNTRYID,CNT,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST_QQQ,LANGTEST_COG,LANGTEST_PAQ,BOOKID,ST001D01T,ST003D02T,ST003D03T,ST004D01T,ST005Q01TA,ST006Q01TA,ST006Q02TA,ST006Q03TA,ST006Q04TA,ST007Q01TA,ST008Q01TA,ST008Q02TA,ST008Q03TA,ST008Q04TA,ST011Q01TA,ST011Q02TA,ST011Q03TA,ST011Q04TA,ST011Q05TA,ST011Q06TA,ST011Q07TA,ST011Q08TA,ST011Q09TA,ST011Q10TA,ST011Q11TA,ST011Q12TA,ST011Q16NA,ST011D17TA,ST011D18TA,ST011D19TA,ST012Q01TA,ST012Q02TA,ST012Q03TA,ST012Q05NA,ST012Q06NA,ST012Q07NA,ST012Q08NA,ST012Q09NA,ST013Q01TA,ST019AQ01T,ST019BQ01T,ST019CQ01T,ST021Q01TA,ST125Q01NA,ST126Q01TA,ST127Q01TA,ST127Q02TA,ST127Q03TA,ST022Q01TA,ST023Q01TA,ST023Q02TA,ST023Q03TA,ST023Q04TA,ST023Q05TA,ST097Q01TA,ST097Q02TA,ST097Q03TA,ST097Q04TA,ST097Q05TA,ST100Q01TA,ST100Q02TA,ST100Q03TA,ST100Q04TA,ST102Q01TA,ST102Q02TA,ST102Q03TA,ST102Q04TA,ST211Q01HA,ST211Q02HA,ST211Q03HA,ST212Q01HA,ST212Q02HA,ST212Q03HA,ST104Q02NA,ST104Q03NA,ST104Q04NA,ST213Q01HA,ST213Q02HA,ST213Q03HA,ST213Q04HA,ST150Q01IA,ST150Q02IA,ST150Q03IA,ST150Q04HA,ST152Q05IA,ST152Q06IA,ST152Q07IA,ST152Q08IA,ST154Q01HA,ST153Q01HA,ST153Q02HA,ST153Q03HA,ST153Q04HA,ST153Q05HA,ST153Q06HA,ST153Q08HA,ST153Q09HA,ST153Q10HA,ST158Q01HA,ST158Q02HA,ST158Q03HA,ST158Q04HA,ST158Q05HA,ST158Q06HA,ST158Q07HA,ST160Q01IA,ST160Q02IA,ST160Q03IA,ST160Q04IA,ST160Q05IA,ST167Q01IA,ST167Q02IA,ST167Q03IA,ST167Q04IA,ST167Q05IA,ST168Q01HA,ST175Q01IA,ST176Q01IA,ST176Q02IA,ST176Q03IA,ST176Q05IA,ST176Q06IA,ST176Q07IA,ST161Q01HA,ST161Q02HA,ST161Q03HA,ST161Q06HA,ST161Q07HA,ST161Q08HA,ST163Q02HA,ST163Q03HA,ST163Q04HA,ST164Q01IA,ST164Q02IA,ST164Q03IA,ST164Q04IA,ST164Q05IA,ST164Q06IA,ST165Q01IA,ST165Q02IA,ST165Q03IA,ST165Q04IA,ST165Q05IA,ST166Q01HA,ST166Q02HA,ST166Q03HA,ST166Q04HA,ST166Q05HA,ST016Q01NA,ST036Q05TA,ST036Q06TA,ST036Q08TA,ST225Q01HA,ST225Q02HA,ST225Q03HA,ST225Q04HA,ST225Q05HA,ST225Q06HA,ST181Q02HA,ST181Q03HA,ST181Q04HA,ST182Q03HA,ST182Q04HA,ST182Q05HA,ST182Q06HA,ST183Q01HA,ST183Q02HA,ST183Q03HA,ST184Q01HA,ST185Q01HA,ST185Q02HA,ST185Q03HA,ST186Q05HA,ST186Q06HA,ST186Q07HA,ST186Q10HA,ST186Q09HA,ST186Q02HA,ST186Q01HA,ST186Q08HA,ST186Q03HA,ST208Q01HA,ST208Q02HA,ST208Q04HA,ST188Q01HA,ST188Q02HA,ST188Q03HA,ST188Q06HA,ST188Q07HA,ST034Q01TA,ST034Q02TA,ST034Q03TA,ST034Q04TA,ST034Q05TA,ST034Q06TA,ST196Q02HA,ST196Q03HA,ST196Q04HA,ST196Q05HA,ST196Q06HA,ST196Q07HA,ST197Q01HA,ST197Q02HA,ST197Q04HA,ST197Q07HA,ST197Q08HA,ST197Q09HA,ST197Q12HA,ST215Q01HA,ST215Q02HA,ST215Q03HA,ST215Q04HA,ST215Q05HA,ST216Q01HA,ST216Q02HA,ST216Q03HA,ST216Q04HA,ST216Q05HA,ST216Q06HA,ST218Q01HA,ST218Q02HA,ST218Q03HA,ST218Q04HA,ST218Q05HA,ST218Q06HA,ST218Q07HA,ST222Q01HA,ST222Q03HA,ST222Q04HA,ST222Q05HA,ST222Q06HA,ST222Q08HA,ST222Q09HA,ST222Q10HA,ST214Q01HA,ST214Q02HA,ST214Q03HA,ST214Q06HA,ST220Q01HA,ST220Q02HA,ST220Q03HA,ST220Q04HA,ST217Q01HA,ST217Q02HA,ST217Q03HA,ST217Q04HA,ST217Q05HA,ST219Q01HA,ST219Q02HA,ST219Q03HA,ST219Q04HA,ST219Q05HA,ST219Q06HA,ST204Q02HA,ST204Q03HA,ST204Q04HA,ST204Q05HA,ST177Q01HA,ST177Q02HA,ST177Q03HA,ST189Q01HA,ST221Q01HA,ST221Q02HA,ST221Q03HA,ST221Q04HA,ST221Q05HA,ST221Q06HA,ST221Q07HA,ST221Q08HA,ST221Q09HA,ST221Q11HA,ST223Q02HA,ST223Q04HA,ST223Q05HA,ST223Q08HA,ST123Q02NA,ST123Q03NA,ST123Q04NA,ST205Q01HA,ST205Q02HA,ST205Q03HA,ST205Q04HA,ST059Q01TA,ST059Q02TA,ST059Q03TA,ST059Q04HA,ST060Q01NA,ST061Q01NA,ST062Q01TA,ST062Q02TA,ST062Q03TA,ST038Q03NA,ST038Q04NA,ST038Q05NA,ST038Q06NA,ST038Q07NA,ST038Q08NA,ST207Q01HA,ST207Q02HA,ST207Q03HA,ST207Q04HA,ST207Q05HA,ST206Q01HA,ST206Q02HA,ST206Q03HA,ST206Q04HA,IC001Q01TA,IC001Q02TA,IC001Q03TA,IC001Q04TA,IC001Q05TA,IC001Q06TA,IC001Q07TA,IC001Q08TA,IC001Q09TA,IC001Q10TA,IC001Q11TA,IC009Q01TA,IC009Q02TA,IC009Q03TA,IC009Q05NA,IC009Q06NA,IC009Q07NA,IC009Q08TA,IC009Q09TA,IC009Q10NA,IC009Q11NA,IC002Q01HA,IC004Q01HA,IC005Q01TA,IC006Q01TA,IC007Q01TA,IC150Q01HA,IC150Q02HA,IC150Q03HA,IC150Q04HA,IC150Q05HA,IC150Q06HA,IC150Q07HA,IC150Q08HA,IC150Q09HA,IC151Q01HA,IC151Q02HA,IC151Q03HA,IC151Q04HA,IC151Q05HA,IC151Q06HA,IC151Q07HA,IC151Q08HA,IC151Q09HA,IC152Q01HA,IC152Q02HA,IC152Q03HA,IC152Q04HA,IC152Q05HA,IC152Q06HA,IC152Q07HA,IC152Q08HA,IC152Q09HA,IC008Q01TA,IC008Q02TA,IC008Q03TA,IC008Q04TA,IC008Q05TA,IC008Q07NA,IC008Q08TA,IC008Q09TA,IC008Q10TA,IC008Q11TA,IC008Q12TA,IC008Q13NA,IC010Q01TA,IC010Q02NA,IC010Q03TA,IC010Q04TA,IC010Q05NA,IC010Q06NA,IC010Q07TA,IC010Q08TA,IC010Q09NA,IC010Q10NA,IC010Q11HA,IC010Q12HA,IC011Q01TA,IC011Q02TA,IC011Q03TA,IC011Q04TA,IC011Q05TA,IC011Q06TA,IC011Q07TA,IC011Q08TA,IC011Q09TA,IC011Q10HA,IC013Q01NA,IC013Q04NA,IC013Q05NA,IC013Q11NA,IC013Q12NA,IC013Q13NA,IC014Q03NA,IC014Q04NA,IC014Q06NA,IC014Q08NA,IC014Q09NA,IC015Q02NA,IC015Q03NA,IC015Q05NA,IC015Q07NA,IC015Q09NA,IC016Q01NA,IC016Q02NA,IC016Q04NA,IC016Q05NA,IC016Q07NA,IC169Q01HA,EC031Q01TA,EC032Q01TA,EC033Q01NA,EC150Q01WA,EC150Q02WA,EC150Q03WA,EC150Q04WA,EC150Q05WA,EC150Q06WA,EC150Q07WA,EC150Q08WA,EC150Q09WA,EC150Q10WA,EC151Q01WA,EC151Q01WB,EC151Q01WC,EC151Q02WA,EC151Q02WB,EC151Q02WC,EC151Q03WA,EC151Q03WB,EC151Q03WC,EC151Q04WA,EC151Q04WB,EC151Q04WC,EC151Q05WA,EC151Q05WB,EC151Q05WC,EC152Q01HA,EC153Q01HA,EC153Q02HA,EC153Q03HA,EC153Q04HA,EC153Q05HA,EC153Q06HA,EC153Q07HA,EC153Q08HA,EC153Q09HA,EC153Q10HA,EC153Q11HA,EC160Q01HA,EC158Q01HA,EC158Q02HA,EC159Q01HA,EC159Q02HA,EC163Q01HA,EC163Q02HA,EC163Q03HA,EC163Q04HA,EC163Q05HA,EC163Q06HA,EC163Q07HA,EC162Q01HA,EC162Q02HA,EC162Q03HA,EC162Q04HA,EC162Q05HA,EC162Q06HA,EC162Q07HA,EC162Q08HA,EC154Q01IA,EC154Q02IA,EC154Q03IA,EC154Q04HA,EC154Q05IA,EC154Q06IA,EC154Q07IA,EC154Q08HA,EC154Q09IA,EC012Q01NA,EC012Q02NA,EC012Q04NA,EC012Q06NA,EC012Q07NA,EC012Q08NA,EC012Q13HA,EC012Q12NA,EC155Q01DA,EC155Q02DA,EC155Q03DA,EC155Q04HA,EC155Q05HA,WB150Q01HA,WB151Q01HA,WB152Q01HA,WB153Q01HA,WB153Q02HA,WB153Q03HA,WB153Q04HA,WB153Q05HA,WB154Q01HA,WB154Q02HA,WB154Q03HA,WB154Q04HA,WB154Q05HA,WB154Q06HA,WB154Q07HA,WB154Q08HA,WB154Q09HA,WB155Q01HA,WB155Q02HA,WB155Q03HA,WB155Q04HA,WB155Q05HA,WB155Q06HA,WB155Q07HA,WB155Q08HA,WB155Q09HA,WB155Q10HA,WB156Q01HA,WB158Q01HA,WB160Q01HA,WB161Q01HA,WB162Q01HA,WB162Q02HA,WB162Q03HA,WB162Q04HA,WB162Q05HA,WB162Q06HA,WB162Q07HA,WB162Q08HA,WB162Q09HA,WB163Q01HA,WB163Q02HA,WB163Q03HA,WB163Q04HA,WB163Q05HA,WB163Q06HA,WB163Q07HA,WB163Q08HA,WB164Q01HA,WB165Q01HA,WB166Q01HA,WB166Q02HA,WB166Q03HA,WB166Q04HA,WB167Q01HA,WB168Q01HA,WB168Q02HA,WB168Q03HA,WB168Q04HA,WB171Q01HA,WB171Q02HA,WB171Q03HA,WB171Q04HA,WB172Q01HA,WB173Q01HA,WB173Q02HA,WB173Q03HA,WB173Q04HA,WB176Q01HA,WB177Q01HA,WB177Q02HA,WB177Q03HA,WB177Q04HA,WB032Q01NA,WB032Q02NA,WB031Q01NA,WB178Q01HA,WB178Q02HA,WB178Q03HA,WB178Q04HA,WB178Q05HA,WB178Q06HA,WB178Q07HA,FL150Q01TA,FL150Q02TA,FL150Q03TA,FL151Q01HA,FL151Q02HA,FL164Q01HA,FL164Q02HA,FL164Q03HA,FL164Q04HA,FL164Q05HA,FL164Q06HA,FL164Q07HA,FL164Q08HA,FL164Q09HA,FL164Q10HA,FL164Q11HA,FL164Q12HA,FL164Q13HA,FL164Q14HA,FL164Q15HA,FL164Q16HA,FL164Q17HA,FL164Q18HA,FL165Q01HA,FL165Q02HA,FL165Q03HA,FL165Q04HA,FL166Q01HA,FL166Q02HA,FL166Q03HA,FL166Q05HA,FL166Q06HA,FL166Q07HA,FL153Q01HA,FL153Q02HA,FL153Q03HA,FL153Q04HA,FL153Q05HA,FL153Q06HA,FL167Q01HA,FL167Q02HA,FL167Q03HA,FL167Q04HA,FL167Q05HA,FL156Q01TA,FL156Q02TA,FL156Q03TA,FL156Q04TA,FL156Q05TA,FL156Q06TA,FL156Q07HA,FL159Q01HA,FL159Q02HA,FL159Q03HA,FL159Q04HA,FL160Q01HA,FL160Q02HA,FL160Q03HA,FL160Q04HA,FL161Q01HA,FL161Q02HA,FL161Q03HA,FL162Q01HA,FL162Q02HA,FL162Q03HA,FL162Q04HA,FL162Q05HA,FL162Q06HA,FL163Q01HA,FL163Q02HA,FL163Q03HA,FL163Q04HA,FL163Q05HA,FL168Q01HA,FL168Q02HA,FL168Q03HA,FL168Q04HA,FL168Q05HA,FL168Q06HA,FL168Q07HA,FL168Q08HA,FL169Q01HA,FL169Q02HA,FL169Q03HA,FL169Q04HA,PA001Q01TA,PA001Q02TA,PA001Q03TA,PA003Q01TA,PA003Q02TA,PA003Q03TA,PA003Q04HA,PA003Q05IA,PA003Q06IA,PA003Q07IA,PA154Q01IA,PA154Q02IA,PA154Q03IA,PA154Q04IA,PA154Q05IA,PA154Q06IA,PA154Q07IA,PA154Q08IA,PA154Q09IA,PA154Q10HA,PA155Q01IA,PA156Q01HA,PA156Q02HA,PA156Q03HA,PA156Q04HA,PA004Q02NA,PA004Q03NA,PA004Q04NA,PA008Q01TA,PA008Q02TA,PA008Q03TA,PA008Q04TA,PA008Q05TA,PA008Q06NA,PA008Q07NA,PA008Q08NA,PA008Q09NA,PA008Q10NA,PA009Q01NA,PA009Q02NA,PA009Q03NA,PA009Q04NA,PA009Q05NA,PA009Q06NA,PA009Q07NA,PA009Q08NA,PA009Q09NA,PA009Q10NA,PA009Q11NA,PA007Q01TA,PA007Q02TA,PA007Q03TA,PA007Q04TA,PA007Q05TA,PA007Q06TA,PA007Q07TA,PA007Q09NA,PA007Q11NA,PA007Q12NA,PA007Q13NA,PA007Q14NA,PA007Q15NA,PA005Q01TA,PA006Q01TA,PA006Q02TA,PA006Q03TA,PA006Q04TA,PA006Q05TA,PA006Q06TA,PA006Q07TA,PA006Q08TA,PA006Q09TA,PA006Q10TA,PA006Q11TA,PA006Q12HA,PA006Q13HA,PA006Q14HA,PA158Q01HA,PA158Q02IA,PA158Q03HA,PA158Q04IA,PA158Q05HA,PA159Q01HA,PA160Q01HA,PA160Q02HA,PA160Q03HA,PA160Q04HA,PA160Q05HA,PA161Q01HA,PA161Q02HA,PA161Q03HA,PA161Q05HA,PA161Q06HA,PA161Q07HA,PA162Q01HA,PA163Q01HA,PA166Q01HA,PA167Q02HA,PA167Q03HA,PA167Q04HA,PA167Q05HA,PA168Q01HA,PA168Q02HA,PA168Q03HA,PA168Q06HA,PA169Q01HA,PA169Q02HA,PA169Q03HA,PA169Q04HA,PA169Q05HA,PA169Q06HA,PA170Q01HA,PA170Q02HA,PA170Q04HA,PA170Q07HA,PA170Q08HA,PA170Q09HA,PA170Q12HA,PA171Q01HA,PA171Q03HA,PA171Q04HA,PA171Q05HA,PA171Q06HA,PA171Q08HA,PA171Q09HA,PA171Q10HA,PA172Q01WA,PA172Q02WA,PA172Q03WA,PA172Q04WA,PA172Q05WA,PA172Q06WA,PA018Q01NA,PA018Q02NA,PA018Q03NA,PA177Q01HA,PA177Q02HA,PA177Q03HA,PA177Q04HA,PA177Q05HA,PA177Q06HA,PA177Q07HA,PA177Q08HA,PA180Q01HA,PA182Q01HA,PA175Q01HA,PA175Q02HA,PA041Q01TA,PA042Q01TA,EFFORT1,EFFORT2,OCOD1,OCOD2,OCOD3,GRADE,AGE,PROGN,COBN_S,COBN_M,COBN_F,LANGN,ISCEDL,ISCEDD,ISCEDO,MISCED,FISCED,HISCED,PARED,MISCED_D,FISCED_D,HISCED_D,PAREDINT,BMMJ1,BFMJ2,HISEI,LANGMOTHER,LANGFATHER,LANGSIBLINGS,LANGFRIEND,LANGSCHMATES,IMMIG,DURECEC,REPEAT,BSMJ,MMINS,LMINS,SMINS,TMINS,FCFMLRTY,SCCHANGE,CHANGE,STUBMI,ESCS,UNDREM,METASUM,METASPAM,ICTHOME,ICTSCH,HOMEPOS,CULTPOSS,HEDRES,WEALTH,ICTRES,DISCLIMA,TEACHSUP,DIRINS,PERFEED,EMOSUPS,STIMREAD,ADAPTIVITY,TEACHINT,JOYREAD,SCREADCOMP,SCREADDIFF,PISADIFF,PERCOMP,PERCOOP,ATTLNACT,COMPETE,WORKMAST,GFOFAIL,EUDMO,SWBP,RESILIENCE,MASTGOAL,GCSELFEFF,GCAWARE,ATTIMM,INTCULT,PERSPECT,COGFLEX,RESPECT,AWACOM,GLOBMIND,DISCRIM,BELONG,BEINGBULLIED,ENTUSE,HOMESCH,USESCH,INTICT,COMPICT,AUTICT,SOIAICT,ICTCLASS,ICTOUTSIDE,INFOCAR,INFOJOB1,INFOJOB2,FLCONFIN,FLCONICT,FLSCHOOL,FLFAMILY,CURSUPP,EMOSUPP,PQSCHOOL,PASCHPOL,PRESUPP,JOYREADP,ATTIMMP,INTCULTP,GCAWAREP,BODYIMA,SOCONPA,W_FSTUWT,W_FSTURWT1,W_FSTURWT2,W_FSTURWT3,W_FSTURWT4,W_FSTURWT5,W_FSTURWT6,W_FSTURWT7,W_FSTURWT8,W_FSTURWT9,W_FSTURWT10,W_FSTURWT11,W_FSTURWT12,W_FSTURWT13,W_FSTURWT14,W_FSTURWT15,W_FSTURWT16,W_FSTURWT17,W_FSTURWT18,W_FSTURWT19,W_FSTURWT20,W_FSTURWT21,W_FSTURWT22,W_FSTURWT23,W_FSTURWT24,W_FSTURWT25,W_FSTURWT26,W_FSTURWT27,W_FSTURWT28,W_FSTURWT29,W_FSTURWT30,W_FSTURWT31,W_FSTURWT32,W_FSTURWT33,W_FSTURWT34,W_FSTURWT35,W_FSTURWT36,W_FSTURWT37,W_FSTURWT38,W_FSTURWT39,W_FSTURWT40,W_FSTURWT41,W_FSTURWT42,W_FSTURWT43,W_FSTURWT44,W_FSTURWT45,W_FSTURWT46,W_FSTURWT47,W_FSTURWT48,W_FSTURWT49,W_FSTURWT50,W_FSTURWT51,W_FSTURWT52,W_FSTURWT53,W_FSTURWT54,W_FSTURWT55,W_FSTURWT56,W_FSTURWT57,W_FSTURWT58,W_FSTURWT59,W_FSTURWT60,W_FSTURWT61,W_FSTURWT62,W_FSTURWT63,W_FSTURWT64,W_FSTURWT65,W_FSTURWT66,W_FSTURWT67,W_FSTURWT68,W_FSTURWT69,W_FSTURWT70,W_FSTURWT71,W_FSTURWT72,W_FSTURWT73,W_FSTURWT74,W_FSTURWT75,W_FSTURWT76,W_FSTURWT77,W_FSTURWT78,W_FSTURWT79,W_FSTURWT80,UNIT,WVARSTRR,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE,PV1GLCM,PV2GLCM,PV3GLCM,PV4GLCM,PV5GLCM,PV6GLCM,PV7GLCM,PV8GLCM,PV9GLCM,PV10GLCM,PV1RCLI,PV2RCLI,PV3RCLI,PV4RCLI,PV5RCLI,PV6RCLI,PV7RCLI,PV8RCLI,PV9RCLI,PV10RCLI,PV1RCUN,PV2RCUN,PV3RCUN,PV4RCUN,PV5RCUN,PV6RCUN,PV7RCUN,PV8RCUN,PV9RCUN,PV10RCUN,PV1RCER,PV2RCER,PV3RCER,PV4RCER,PV5RCER,PV6RCER,PV7RCER,PV8RCER,PV9RCER,PV10RCER,PV1RTSN,PV2RTSN,PV3RTSN,PV4RTSN,PV5RTSN,PV6RTSN,PV7RTSN,PV8RTSN,PV9RTSN,PV10RTSN,PV1RTML,PV2RTML,PV3RTML,PV4RTML,PV5RTML,PV6RTML,PV7RTML,PV8RTML,PV9RTML,PV10RTML,SENWT,VER_DAT,i
0,8.0,b'ALB',800115.0,800001.0,b'07MS',b'000800',b'ALB0107',b'0080000',0.0,2.0,140.0,140.0,NaN,5.0,10.0,10.0,2002.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,b'0008001',b'0008001',b'0008001',3.0,2.0,3.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,NaN,5.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,3.0,3.0,2.0,1.0,3.0,3.0,3.0,4.0,3.0,4.0,3.0,2.0,2.0,2.0,1.0,4.0,3.0,3.0,4.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,5.0,2.0,2.0,2.0,2.0,3.0,2.0,4.0,1.0,1.0,1.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,4.0,5.0,3.0,2.0,4.0,1.0,3.0,2.0,7.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,3.0,3.0,3.0,4.0,3.0,2.0,NaN,1.0,NaN,NaN,3.0,2.0,4.0,5.0,5.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0,1.0,1.0,4.0,2.0,4.0,3.0,1.0,4.0,NaN,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,3.0,2.0,1.0,2.0,1.0,2.0,2.0,3.0,2.0,1.0,2.0,1.0,3.0,4.0,3.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,1.0,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0,3.0,3.0,4.0,2.0,4.0,4.0,6.0,59.0,45.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,2.0,2.0,1.0,3.0,1.0,3.0,5.0,5.0,1.0,5.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,3.0,2.0,3.0,NaN,2.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,2.0,NaN,1.0,1.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,3.0,1.0,2.0,3.0,3.0,3.0,2.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,NaN,2.0,2.0,2.0,3.0,2.0,1.0,2.0,4.0,3.0,9.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,b'5152',b'9211',b'2359',0.0,15.50,b'00080005',b'000800',b'000800',b'000800',140.0,3.0,1.0,1.0,6.0,6.0,6.0,16.0,6.0,6.0,6.0,16.0,32.20,11.74,32.20,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,66.42,180.0,90.0,180.0,2655.0,NaN,0.0,0.0,NaN,-0.2154,-1.64,0.59,0.87,11.0,7.0,-0.4259,0.3342,-0.1357,-0.5795,-0.7308,-0.9415,1.3140,1.8202,0.7743,-1.9687,1.0419,-0.4740,0.9278,-0.2704,0.1919,-1.8876,-0.5536,1.0326,0.6012,1.0844,2.0054,-0.1015,-1.8939,0.9269,0.1038,1.6219,1.3357,0.0156,0.3436,0.3013,-0.3559,0.6314,0.4704,-0.4899,0.1833,-0.1029,-0.4235,0.6344,0.6725,-0.6166,0.0877,0.2847,-0.6385,-0.6223,-0.8880,-0.0316,-1.2188,-1.3048,-0.4133,-0.9778,-0.1640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.68798,1.34399,4.03196,4.03196,4.03196,1.34399,4.03196,1.34399,4.03196,1.34399,1.34399,1.34399,1.34399,4.03196,4.03196,1.34399,4.03196,4.03196,1.34399,1.34399,4.03196,1.34399,4.03196,4.03196,4.03196,1.34399,4.03196,1.34399,4.03196,1.34399,1.34399,1.34399,1.34399,4.03196,4.03196,1.34399,4.03196,4.03196,1.34399,1.34399,4.03196,4.03196,1.34399,1.34399,1.34399,4.03196,1.34399,4.03196,1.34399,4.03196,4.03196,4.03196,4.03196,1.34399,1.34399,4.03196,1.34399,1.34399,4.03196,4.03196,1.34399,4.03196,1.34399,1.34399,1.34399,4.03196,1.34399,4.03196,1.34399,4.03196,4.03196,4.03196,4.03196,1.34399,1.34399,4.03196,1.34399,1.34399,4.03196,4.03196,1.34399,2.0,48.0,432.285,485.717,474.458,508.786,428.616,449.062,451.276,484.471,436.084,454.084,341.838,336.436,356.491,403.464,350.935,374.880,341.599,377.952,358.824,367.401,390.471,363.896,394.451,405.479,309.142,356.123,387.410,421.957,375.945,383.357,383.374,326.434,330.902,358.720,348.573,322.065,322.680,390.696,418.105,315.913,354.662,381.573,420.202,360.682,345.403,391.608,370.101,352.823,369.589,315.097,370.396,386.281,395.078,350.102,362.870,376.134,359.814,339.759,380.436,330.816,395.945,411.492,391.704,350.158,403.608,408.237,361.505,346.161,425.123,335.507,381.494,405.413,365.475,287.579,332.289,355.814,351.304,362.877,382.303,371.677,392.591,412.374,382.300,325.281,370.041,358.524,345.833,380.064,357.376,385.496,0.48064,b' 09MAY19:11:20:53',31.0

In [10]:
df_stu_2022.head()

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,ADMINMODE,LANGTEST_QQQ,LANGTEST_COG,LANGTEST_PAQ,Option_CT,Option_FL,Option_ICTQ,Option_WBQ,Option_PQ,Option_TQ,Option_UH,BOOKID,ST001D01T,ST003D02T,ST003D03T,ST004D01T,ST250Q01JA,ST250Q02JA,ST250Q03JA,ST250Q04JA,ST250Q05JA,ST250D06JA,ST250D07JA,ST251Q01JA,ST251Q02JA,ST251Q03JA,ST251Q04JA,ST251Q06JA,ST251Q07JA,ST251D08JA,ST251D09JA,ST253Q01JA,ST254Q01JA,ST254Q02JA,ST254Q03JA,ST254Q04JA,ST254Q05JA,ST254Q06JA,ST255Q01JA,ST256Q01JA,ST256Q02JA,ST256Q03JA,ST256Q06JA,ST256Q07JA,ST256Q08JA,ST256Q09JA,ST256Q10JA,ST230Q01JA,ST005Q01JA,ST006Q01JA,ST006Q02JA,ST006Q03JA,ST006Q04JA,ST006Q05JA,ST007Q01JA,ST008Q01JA,ST008Q02JA,ST008Q03JA,ST008Q04JA,ST008Q05JA,ST258Q01JA,ST259Q01JA,ST259Q02JA,ST019AQ01T,ST019BQ01T,ST019CQ01T,ST021Q01TA,ST022Q01TA,ST226Q01JA,ST125Q01NA,ST126Q01TA,ST127Q01TA,ST127Q02TA,ST127Q03TA,ST260Q01JA,ST260Q02JA,ST260Q03JA,ST261Q01JA,ST261Q02JA,ST261Q03JA,ST261Q04JA,ST261Q05JA,ST261Q06JA,ST261Q07JA,ST261Q08JA,ST261Q09JA,ST261Q10JA,ST261Q11JA,ST062Q01TA,ST062Q02TA,ST062Q03TA,ST267Q01JA,ST267Q02JA,ST267Q03JA,ST267Q04JA,ST267Q05JA,ST267Q06JA,ST267Q07JA,ST267Q08JA,ST034Q01TA,ST034Q02TA,ST034Q03TA,ST034Q04TA,ST034Q05TA,ST034Q06TA,ST038Q03NA,ST038Q04NA,ST038Q05NA,ST038Q06NA,ST038Q07NA,ST038Q08NA,ST038Q09JA,ST038Q10JA,ST038Q11JA,ST265Q01JA,ST265Q02JA,ST265Q03JA,ST265Q04JA,ST266Q01JA,ST266Q02JA,ST266Q03JA,ST266Q04JA,ST266Q05JA,ST294Q01JA,ST294Q02JA,ST294Q03JA,ST294Q04JA,ST294Q05JA,ST295Q01JA,ST295Q02JA,ST295Q03JA,ST295Q04JA,ST295Q05JA,ST326Q01JA,ST326Q02JA,ST326Q03JA,ST326Q04JA,ST326Q05JA,ST326Q06JA,ST326Q07JA,ST326Q08JA,ST326Q09JA,ST326Q10JA,ST326Q11JA,ST326Q12JA,ST322Q01JA,ST322Q02JA,ST322Q03JA,ST322Q04JA,ST322Q06JA,ST322Q07JA,ST307Q01JA,ST307Q02JA,ST307Q03JA,ST307Q04JA,ST307Q05JA,ST307Q06JA,ST307Q07JA,ST307Q08JA,ST307Q09JA,ST307Q10JA,ST309Q01JA,ST309Q02JA,ST309Q03JA,ST309Q04JA,ST309Q05JA,ST309Q06JA,ST309Q07JA,ST309Q08JA,ST309Q09JA,ST309Q10JA,ST301Q01JA,ST301Q02JA,ST301Q03JA,ST301Q04JA,ST301Q05JA,ST301Q06JA,ST301Q07JA,ST301Q08JA,ST301Q09JA,ST301Q10JA,ST343Q01JA,ST343Q02JA,ST343Q03JA,ST343Q04JA,ST343Q05JA,ST343Q06JA,ST343Q07JA,ST343Q08JA,ST343Q09JA,ST343Q10JA,ST311Q01JA,ST311Q02JA,ST311Q03JA,ST311Q04JA,ST311Q05JA,ST311Q06JA,ST311Q07JA,ST311Q08JA,ST311Q09JA,ST311Q10JA,ST315Q01JA,ST315Q02JA,ST315Q03JA,ST315Q04JA,ST315Q05JA,ST315Q06JA,ST315Q07JA,ST315Q08JA,ST315Q09JA,ST315Q10JA,ST303Q01JA,ST303Q02JA,ST303Q03JA,ST303Q04JA,ST303Q05JA,ST303Q06JA,ST303Q07JA,ST303Q08JA,ST305Q01JA,ST305Q02JA,ST305Q03JA,ST305Q04JA,ST305Q05JA,ST305Q06JA,ST305Q07JA,ST305Q08JA,ST305Q09JA,ST305Q10JA,ST345Q01JA,ST345Q02JA,ST345Q03JA,ST345Q04JA,ST345Q05JA,ST345Q06JA,ST345Q07JA,ST345Q08JA,ST345Q09JA,ST345Q10JA,ST313Q01JA,ST313Q02JA,ST313Q03JA,ST313Q04JA,ST313Q05JA,ST313Q06JA,ST313Q07JA,ST313Q08JA,ST313Q09JA,ST313Q10JA,ST263Q02JA,ST263Q04JA,ST263Q06JA,ST263Q08JA,ST016Q01NA,ST059Q01TA,ST059Q02JA,ST296Q01JA,ST296Q02JA,ST296Q03JA,ST296Q04JA,ST272Q01JA,ST273Q01JA,ST273Q02JA,ST273Q03JA,ST273Q04JA,ST273Q05JA,ST273Q06JA,ST273Q07JA,ST270Q01JA,ST270Q02JA,ST270Q03JA,ST270Q04JA,ST285Q01JA,ST285Q02JA,ST285Q03JA,ST285Q04JA,ST285Q05JA,ST285Q06JA,ST285Q07JA,ST285Q08JA,ST285Q09JA,ST283Q01JA,ST283Q02JA,ST283Q03JA,ST283Q04JA,ST283Q05JA,ST283Q06JA,ST283Q07JA,ST283Q08JA,ST283Q09JA,ST275Q01WA,ST275Q02WA,ST275Q03WA,ST275Q04WA,ST275Q05WA,ST275Q06WA,ST275Q07WA,ST275Q08WA,ST275Q09WA,ST276Q01JA,ST276Q02JA,ST276Q03JA,ST276Q04JA,ST276Q05JA,ST276Q06JA,ST276Q07JA,ST276Q08JA,ST276Q09JA,ST276Q10JA,ST268Q01JA,ST268Q02JA,ST268Q03JA,ST268Q04JA,ST268Q05JA,ST268Q06JA,ST268Q07JA,ST268Q08JA,ST268Q09JA,ST290Q01WA,ST290Q02WA,ST290Q03WA,ST290Q04WA,ST290Q05WA,ST290Q06WA,ST290Q07WA,ST290Q08WA,ST290Q09WA,ST291Q01JA,ST291Q02JA,ST291Q03JA,ST291Q04JA,ST291Q05JA,ST291Q06JA,ST291Q07JA,ST291Q08JA,ST291Q09JA,ST291Q10JA,ST289Q01WA,ST289Q02JA,ST289Q03WA,ST289Q04JA,ST289Q05WA,ST289Q06JA,ST289Q07JA,ST289Q08WA,ST289Q09WA,ST289Q10WA,ST289Q11WA,ST289Q14JA,ST293Q01JA,ST293Q02JA,ST293Q03JA,ST293Q04JA,ST293Q05JA,ST293Q06JA,ST293Q07JA,ST293Q08JA,ST293Q09JA,ST292Q01JA,ST292Q02JA,ST292Q03JA,ST292Q04JA,ST292Q05JA,ST292Q06JA,ST297Q01JA,ST297Q03JA,ST297Q05JA,ST297Q06JA,ST297Q07JA,ST297Q09JA,ST334Q01JA,ST334Q02JA,ST334Q03JA,ST334Q04JA,ST334Q05JA,ST334Q06JA,ST334Q07JA,ST334Q08JA,ST334Q09JA,ST334Q10JA,ST335Q01JA,ST335Q02JA,ST335Q03JA,ST335Q05JA,ST335Q06JA,ST335Q07JA,ST336Q01JA,ST336Q03JA,ST336Q04JA,ST336Q05JA,ST336Q06JA,ST336Q07JA,ST337Q01JA,ST337Q02JA,ST337Q03JA,ST337Q04JA,ST337Q05JA,ST337Q06JA,ST337Q07JA,ST337Q08JA,ST338Q01JA,ST338Q02JA,ST338Q03JA,ST338Q04JA,ST338Q05JA,ST338Q06JA,ST338Q07JA,ST338Q08JA,ST339Q04JA,ST339Q06JA,ST340Q01JA,ST340Q02JA,ST340Q03JA,ST340Q04JA,ST340Q05JA,ST340Q06JA,ST340Q07JA,ST340Q08JA,ST340Q09JA,ST340Q10JA,ST341Q01JA,ST341Q02JA,ST341Q03JA,ST341Q04JA,ST341Q05JA,ST342Q01JA,ST342Q02JA,ST342Q03JA,ST342Q04JA,ST342Q06JA,ST342Q07JA,ST342Q08JA,ST300Q01JA,ST300Q02JA,ST300Q03JA,ST300Q04JA,ST300Q05JA,ST300Q06JA,ST300Q07JA,ST300Q08JA,ST300Q09JA,ST300Q10JA,ST327Q01JA,ST327Q02JA,ST327Q03JA,ST327Q04JA,ST327Q05JA,ST327Q06JA,ST327Q07JA,ST327Q08JA,ST330Q01WA,ST330Q02WA,ST330Q03WA,ST330Q04WA,ST330Q05WA,ST330Q06WA,ST330Q07WA,ST330Q08WA,ST330Q09WA,ST330Q11WA,ST330D10WA,ST324Q02JA,ST324Q04JA,ST324Q05JA,ST324Q07JA,ST324Q10JA,ST324Q11JA,ST324Q12JA,ST324Q13JA,ST324Q14JA,ST347Q01JA,ST347Q02JA,ST348Q01JA,ST348Q02JA,ST348Q03JA,ST348Q04JA,ST348Q05JA,ST348Q06JA,ST348Q07JA,ST348Q08JA,ST349Q01JA,ST350Q01JA,ST351Q01JA,ST351Q02JA,ST351Q03JA,ST351Q04JA,ST351Q05JA,ST351Q06JA,ST351Q07JA,ST351Q08JA,ST352Q01JA,ST352Q02JA,ST352Q03JA,ST352Q04JA,ST352Q05JA,ST352Q06JA,ST352Q07JA,ST352Q08JA,ST353Q01JA,ST353Q02JA,ST353Q03JA,ST353Q04JA,ST353Q05JA,ST353Q06JA,ST353Q07JA,ST353Q08JA,ST354Q01JA,ST354Q02JA,ST354Q03JA,ST354Q04JA,ST354Q05JA,ST354Q06JA,ST354Q07JA,ST354Q08JA,ST354Q09JA,ST354Q10JA,ST355Q01JA,ST355Q02JA,ST355Q03JA,ST355Q04JA,ST355Q05JA,ST355Q06JA,ST355Q07JA,ST355Q08JA,ST356Q01JA,ST331Q01JA,ST331Q02JA,ST331Q03JA,FL150Q01TA,FL150Q02TA,FL150Q03TA,FL164Q01HA,FL164Q02HA,FL164Q03HA,FL164Q04HA,FL164Q05HA,FL164Q06HA,FL164Q07HA,FL164Q08HA,FL164Q09HA,FL164Q10HA,FL164Q11HA,FL164Q12HA,FL164Q13HA,FL164Q14HA,FL164Q15HA,FL164Q16HA,FL166Q01HA,FL166Q02HA,FL166Q03HA,FL166Q05HA,FL166Q06HA,FL166Q07HA,FL174Q01JA,FL174Q02JA,FL174Q03JA,FL174Q04JA,FL174Q05JA,FL174Q06JA,FL174Q07JA,FL167Q01HA,FL167Q02HA,FL167Q06JA,FL167Q03HA,FL167Q04HA,FL167Q05HA,FL167Q07JA,FL170Q01JA,FL170Q02JA,FL170Q03JA,FL170Q04JA,FL170Q05JA,FL170Q06JA,FL170Q07JA,FL159Q01HA,FL159Q02HA,FL159Q03HA,FL159Q04HA,FL160Q01HA,FL160Q02HA,FL160Q03HA,FL160Q04HA,FL161Q01HA,FL161Q02HA,FL161Q03HA,FL162Q01HA,FL162Q02HA,FL162Q03HA,FL162Q04HA,FL162Q05HA,FL162Q06HA,FL163Q01HA,FL163Q02HA,FL163Q03HA,FL163Q04HA,FL163Q05HA,FL171Q01JA,FL171Q02JA,FL171Q03JA,FL171Q04JA,FL171Q05JA,FL171Q07JA,FL171Q08JA,FL171Q09JA,FL171Q10JA,FL171Q11JA,FL171Q12JA,FL169Q01HA,FL169Q05JA,FL169Q02HA,FL169Q06JA,FL169Q07JA,FL169Q03HA,FL169Q04HA,FL169Q08JA,FL169Q10JA,FL169Q11JA,FL172Q01JA,FL172Q03JA,FL172Q05JA,FL172Q06JA,IC170Q01JA,IC170Q02JA,IC170Q03JA,IC170Q04JA,IC170Q05JA,IC170Q06JA,IC170Q07JA,IC171Q01JA,IC171Q02JA,IC171Q03JA,IC171Q04JA,IC171Q05JA,IC171Q06JA,IC172Q01JA,IC172Q02JA,IC172Q03JA,IC172Q04JA,IC172Q05JA,IC172Q06JA,IC172Q07JA,IC172Q08JA,IC172Q09JA,IC173Q01JA,IC173Q02JA,IC173Q03JA,IC173Q04JA,IC174Q01JA,IC174Q02JA,IC174Q03JA,IC174Q04JA,IC174Q05JA,IC174Q06JA,IC174Q07JA,IC174Q08JA,IC174Q09JA,IC174Q10JA,IC175Q01JA,IC175Q02JA,IC175Q03JA,IC175Q05JA,IC176Q01JA,IC176Q02JA,IC176Q03JA,IC176Q04JA,IC176Q05JA,IC176Q06JA,IC176Q07JA,IC176Q08JA,IC184Q01JA,IC184Q02JA,IC184Q03JA,IC184Q04JA,IC177Q01JA,IC177Q02JA,IC177Q03JA,IC177Q04JA,IC177Q05JA,IC177Q06JA,IC177Q07JA,IC178Q01JA,IC178Q02JA,IC178Q03JA,IC178Q04JA,IC178Q05JA,IC178Q06JA,IC178Q07JA,IC179Q01JA,IC179Q02JA,IC179Q03JA,IC179Q04JA,IC179Q05JA,IC179Q06JA,IC180Q01JA,IC180Q02JA,IC180Q03JA,IC180Q04JA,IC180Q05JA,IC180Q06JA,IC180Q07JA,IC180Q08JA,IC181Q01JA,IC181Q02JA,IC181Q03JA,IC181Q04JA,IC182Q01JA,IC182Q02JA,IC182Q03JA,IC183Q01JA,IC183Q02JA,IC183Q03JA,IC183Q04JA,IC183Q05JA,IC183Q07JA,IC183Q08JA,IC183Q09JA,IC183Q10JA,IC183Q12JA,IC183Q13JA,IC183Q14JA,IC183Q15JA,IC183Q16JA,WB150Q01HA,WB151Q01HA,WB152Q01HA,WB153Q01HA,WB153Q02HA,WB153Q03HA,WB153Q04HA,WB153Q05HA,WB154Q01HA,WB154Q02HA,WB154Q03HA,WB154Q04HA,WB154Q05HA,WB154Q06HA,WB154Q07HA,WB154Q08HA,WB154Q09HA,WB155Q01HA,WB155Q02HA,WB155Q03HA,WB155Q04HA,WB155Q05HA,WB155Q06HA,WB155Q07HA,WB155Q08HA,WB155Q09HA,WB155Q10HA,WB156Q01HA,WB158Q01HA,WB160Q01HA,WB161Q01HA,WB162Q01HA,WB162Q02HA,WB162Q03HA,WB162Q04HA,WB162Q05HA,WB162Q06HA,WB162Q07HA,WB162Q08HA,WB162Q09HA,WB163Q01HA,WB163Q02HA,WB163Q03HA,WB163Q04HA,WB163Q05HA,WB163Q06HA,WB163Q07HA,WB163Q08HA,WB164Q01HA,WB165Q01HA,WB166Q01HA,WB166Q02HA,WB166Q03HA,WB166Q04HA,WB167Q01HA,WB168Q01HA,WB168Q02HA,WB168Q03HA,WB168Q04HA,WB171Q01HA,WB171Q02HA,WB171Q03HA,WB171Q04HA,WB172Q01HA,WB173Q01HA,WB173Q02HA,WB173Q03HA,WB173Q04HA,WB176Q01HA,WB177Q01HA,WB177Q02HA,WB177Q03HA,WB177Q04HA,WB032Q01NA,WB032Q02NA,WB031Q01NA,WB178Q01HA,WB178Q02HA,WB178Q03HA,WB178Q04HA,WB178Q05HA,WB178Q06HA,WB178Q07HA,PA001Q01TA,PA001Q02TA,PA001Q03TA,PA003Q01TA,PA003Q02TA,PA003Q03TA,PA003Q05IA,PA003Q18WA,PA003Q19WA,PA003Q20WA,PA003Q11JA,PA003Q12JA,PA003Q13JA,PA003Q14JA,PA003Q15JA,PA003Q16JA,PA003Q17JA,PA196Q01WA,PA196Q02WA,PA196Q03WA,PA196Q04WA,PA197Q01WA,PA197Q02WA,PA197Q03WA,PA197Q04WA,PA197Q05WA,PA008Q01TA,PA008Q02TA,PA008Q03TA,PA008Q04TA,PA008Q05TA,PA008Q06NA,PA008Q07NA,PA008Q08NA,PA008Q09NA,PA008Q10NA,PA009Q01NA,PA009Q02NA,PA009Q03NA,PA009Q04NA,PA009Q05NA,PA009Q06NA,PA009Q07NA,PA009Q08NA,PA009Q09NA,PA009Q10NA,PA009Q11NA,PA007Q01TA,PA007Q02TA,PA007Q03TA,PA007Q04TA,PA007Q05TA,PA007Q06TA,PA007Q07TA,PA007Q09NA,PA007Q11NA,PA007Q12NA,PA007Q13NA,PA007Q14NA,PA007Q15NA,PA005Q01TA,PA006Q01TA,PA006Q02TA,PA006Q03TA,PA006Q04TA,PA006Q05TA,PA006Q06TA,PA006Q07TA,PA006Q08TA,PA006Q09TA,PA006Q10TA,PA006Q11TA,PA006Q12HA,PA006Q13HA,PA006Q14HA,PA166Q01HA,PA167Q02HA,PA167Q03HA,PA167Q04HA,PA167Q05HA,PA183Q01JA,PA183Q02JA,PA183Q03JA,PA183Q04JA,PA183Q05JA,PA183Q06JA,PA183Q07JA,PA183Q08JA,PA018Q01NA,PA018Q02NA,PA018Q03NA,PA177Q01HA,PA177Q02HA,PA177Q03HA,PA177Q04HA,PA177Q05HA,PA177Q06HA,PA177Q07HA,PA177Q08HA,PA180Q01HA,PA182Q01HA,PA175Q01HA,PA175Q02HA,PA175Q03JA,PA175Q04JA,PA185Q01JA,PA185Q02JA,PA185Q03JA,PA185Q04JA,PA185Q05JA,PA185Q07JA,PA185Q08JA,PA185Q09JA,PA185Q10JA,PA186Q01JA,PA186Q02JA,PA186Q03JA,PA186Q04JA,PA186Q05JA,PA186Q06JA,PA186Q07JA,PA186Q08JA,PA187Q04JA,PA187Q06JA,PA188Q01JA,PA188Q02JA,PA188Q03JA,PA188Q04JA,PA188Q05JA,PA188Q06JA,PA188Q08JA,PA188Q09JA,PA188Q10JA,PA189Q01JA,PA189Q02JA,PA189Q03JA,PA189Q04JA,PA189Q05JA,PA189Q06JA,PA189Q09JA,PA189Q10JA,PA194Q01JA,PA195Q01JA,PA041Q01TA,PA042Q01TA,EFFORT1,EFFORT2,OCOD1,OCOD2,OCOD3,PROGN,AGE,GRADE,ISCEDP,IMMIG,COBN_S,COBN_M,COBN_F,LANGN,REPEAT,MISSSC,SKIPPING,TARDYSD,EXERPRAC,STUDYHMW,WORKPAY,WORKHOME,EXPECEDU,MATHPREF,MATHEASE,MATHMOT,DURECEC,BSMJ,SISCO,RELATST,BELONG,BULLIED,FEELSAFE,SCHRISK,PERSEVAGR,CURIOAGR,COOPAGR,EMPATAGR,ASSERAGR,STRESAGR,EMOCOAGR,GROSAGR,INFOSEEK,FAMSUP,DISCLIM,TEACHSUP,COGACRCO,COGACMCO,EXPOFA,EXPO21ST,MATHEFF,MATHEF21,FAMCON,ANXMAT,MATHPERS,CREATEFF,CREATSCH,CREATFAM,CREATAS,CREATOOS,CREATOP,OPENART,IMAGINE,SCHSUST,LEARRES,PROBSELF,FAMSUPSL,FEELLAH,SDLEFF,MISCED,FISCED,HISCED,PAREDINT,BMMJ1,BFMJ2,HISEI,ICTRES,HOMEPOS,ESCS,FCFMLRTY,FLSCHOOL,FLMULTSB,FLFAMILY,ACCESSFP,FLCONFIN,FLCONICT,ACCESSFA,ATTCONFM,FRINFLFM,ICTSCH,ICTAVSCH,ICTHOME,ICTAVHOM,ICTQUAL,ICTSUBJ,ICTENQ,ICTFEED,ICTOUT,ICTWKDY,ICTWKEND,ICTREG,ICTINFO,ICTDISTR,ICTEFFIC,STUBMI,BODYIMA,SOCONPA,LIFESAT,PSYCHSYM,SOCCON,EXPWB,CURSUPP,PQMIMP,PQMCAR,PARINVOL,PQSCHOOL,PASCHPOL,ATTIMMP,PAREXPT,CREATHME,CREATACT,CREATOPN,CREATOR,W_FSTUWT,W_FSTURWT1,W_FSTURWT2,W_FSTURWT3,W_FSTURWT4,W_FSTURWT5,W_FSTURWT6,W_FSTURWT7,W_FSTURWT8,W_FSTURWT9,W_FSTURWT10,W_FSTURWT11,W_FSTURWT12,W_FSTURWT13,W_FSTURWT14,W_FSTURWT15,W_FSTURWT16,W_FSTURWT17,W_FSTURWT18,W_FSTURWT19,W_FSTURWT20,W_FSTURWT21,W_FSTURWT22,W_FSTURWT23,W_FSTURWT24,W_FSTURWT25,W_FSTURWT26,W_FSTURWT27,W_FSTURWT28,W_FSTURWT29,W_FSTURWT30,W_FSTURWT31,W_FSTURWT32,W_FSTURWT33,W_FSTURWT34,W_FSTURWT35,W_FSTURWT36,W_FSTURWT37,W_FSTURWT38,W_FSTURWT39,W_FSTURWT40,W_FSTURWT41,W_FSTURWT42,W_FSTURWT43,W_FSTURWT44,W_FSTURWT45,W_FSTURWT46,W_FSTURWT47,W_FSTURWT48,W_FSTURWT49,W_FSTURWT50,W_FSTURWT51,W_FSTURWT52,W_FSTURWT53,W_FSTURWT54,W_FSTURWT55,W_FSTURWT56,W_FSTURWT57,W_FSTURWT58,W_FSTURWT59,W_FSTURWT60,W_FSTURWT61,W_FSTURWT62,W_FSTURWT63,W_FSTURWT64,W_FSTURWT65,W_FSTURWT66,W_FSTURWT67,W_FSTURWT68,W_FSTURWT69,W_FSTURWT70,W_FSTURWT71,W_FSTURWT72,W_FSTURWT73,W_FSTURWT74,W_FSTURWT75,W_FSTURWT76,W_FSTURWT77,W_FSTURWT78,W_FSTURWT79,W_FSTURWT80,UNIT,WVARSTRR,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE,PV1MCCR,PV2MCCR,PV3MCCR,PV4MCCR,PV5MCCR,PV6MCCR,PV7MCCR,PV8MCCR,PV9MCCR,PV10MCCR,PV1MCQN,PV2MCQN,PV3MCQN,PV4MCQN,PV5MCQN,PV6MCQN,PV7MCQN,PV8MCQN,PV9MCQN,PV10MCQN,PV1MCSS,PV2MCSS,PV3MCSS,PV4MCSS,PV5MCSS,PV6MCSS,PV7MCSS,PV8MCSS,PV9MCSS,PV10MCSS,PV1MCUD,PV2MCUD,PV3MCUD,PV4MCUD,PV5MCUD,PV6MCUD,PV7MCUD,PV8MCUD,PV9MCUD,PV10MCUD,PV1MPEM,PV2MPEM,PV3MPEM,PV4MPEM,PV5MPEM,PV6MPEM,PV7MPEM,PV8MPEM,PV9MPEM,PV10MPEM,PV1MPFS,PV2MPFS,PV3MPFS,PV4MPFS,PV5MPFS,PV6MPFS,PV7MPFS,PV8MPFS,PV9MPFS,PV10MPFS,PV1MPIN,PV2MPIN,PV3MPIN,PV4MPIN,PV5MPIN,PV6MPIN,PV7MPIN,PV8MPIN,PV9MPIN,PV10MPIN,PV1MPRE,PV2MPRE,PV3MPRE,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT
0,b'ALB',8.0,800282.0,800001.0,b'08MS',b'000800',b'ALB03',b'0080000',800.0,0.0,2.0,140.0,140.0,NaN,1.0,0.0,1.0,0.0,0.0,0.0,0.0,46.0,10.0,5.0,2006.0,1.0,NaN,1.0,NaN,NaN,NaN,b'9999997',b'9999997',NaN,NaN,NaN,NaN,4.0,NaN,b'9999997',b'9999997',8.0,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,3.0,3.0,NaN,NaN,3.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,1.0,NaN,3.0,NaN,NaN,NaN,2.0,NaN,1.0,10.0,NaN,1.0,1.0,1.0,NaN,1.0,4.0,6.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,4.0,4.0,NaN,1.0,3.0,3.0,NaN,NaN,3.0,1.0,3.0,3.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,6.0,6.0,6.0,1.0,1.0,6.0,6.0,6.0,1.0,1.0,3.0,2.0,4.0,3.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,3.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,2.0,NaN,5.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,5.0,NaN,1.0,NaN,NaN,NaN,1.0,5.0,NaN,1.0,NaN,1.0,5.0,NaN,NaN,1.0,NaN,5.0,NaN,NaN,NaN,1.0,5.0,NaN,5.0,1.0,NaN,NaN,3.0,3.0,NaN,1.0,NaN,3.0,NaN,NaN,4.0,5.0,NaN,4.0,NaN,4.0,4.0,NaN,NaN,2.0,NaN,2.0,4.0,2.0,NaN,NaN,3.0,NaN,5.0,3.0,3.0,NaN,NaN,5.0,NaN,NaN,3.0,5.0,NaN,NaN,NaN,5.0,NaN,NaN,3.0,5.0,3.0,4.0,3.0,3.0,4.0,10.0,4.0,7.0,3.0,2.0,5.0,6.0,10.0,NaN,4.0,NaN,4.0,4.0,3.0,3.0,1.0,1.0,1.0,1.0,NaN,NaN,5.0,NaN,NaN,1.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,5.0,5.0,NaN,4.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,1.0,2.0,3.0,2.0,1.0,3.0,1.0,4.0,4.0,4.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,4.0,5.0,NaN,5.0,NaN,1.0,3.0,3.0,3.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,NaN,4.0,NaN,4.0,4.0,4.0,NaN,NaN,4.0,NaN,1.0,NaN,3.0,2.0,4.0,4.0,3.0,3.0,3.0,4.0,4.0,NaN,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,4.0,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'9999997',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,3.0,1.0,1.0,NaN,NaN,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,b'243',b'9412',b'9999',b'00080002',16.00,0.0,344.0,1.0,b'000800',b'000800',b'000800',140.0,0.0,0.0,1.0,NaN,0.0,10.0,0.0,10.0,9.0,0.0,0.0,0.0,NaN,NaN,NaN,0.9905,-0.2327,-1.2280,1.1246,-0.6386,NaN,3.3518,NaN,NaN,NaN,NaN,NaN,-0.5185,NaN,1.8355,0.6387,1.5558,0.8246,2.4962,-0.2284,2.4031,-1.4413,NaN,NaN,0.5440,-0.0085,2.4021,0.0590,0.8155,4.1226,NaN,NaN,0.7507,2.0225,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,7.0,14.5,73.91,16.50,73.91,4.9507,1.5995,1.1112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,-1.1989,-2.0261,-1.7886,NaN,NaN,NaN,NaN,0.8373,0.6984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.15874,4.74716,1.56827,1.59281,1.56609,4.74200,1.57824,4.71587,1.59336,4.70887,4.77874,4.72634,4.70898,1.60898,1.57351,4.67259,1.59631,1.58971,4.68497,4.73503,1.59094,1.57616,4.77874,4.70191,4.78900,1.57824,4.74200,1.58779,4.69220,1.59094,1.56827,1.58274,1.58971,4.66661,4.75539,1.60530,4.68497,4.70898,1.59631,1.58021,4.70887,4.74716,1.56827,1.59281,1.56609,4.74200,1.57824,4.71587,1.59336,4.70887,4.77874,4.72634,4.70898,1.60898,1.57351,4.67259,1.59631,1.58971,4.68497,4.73503,1.59094,1.57616,4.77874,4.70191,4.78900,1.57824,4.74200,1.58779,4.69220,1.59094,1.56827,1.58274,1.58971,4.66661,4.75539,1.60530,4.68497,4.70898,1.59631,1.58021,4.70887,1.0,50.0,179.583,201.334,222.248,194.943,222.755,213.100,221.021,293.710,226.912,254.745,247.571,322.919,220.679,220.125,259.780,242.733,253.962,299.988,164.397,265.872,335.468,295.861,312.648,263.027,263.343,308.478,309.256,273.810,297.433,353.279,117.551,159.092,107.677,199.973,175.183,164.531,161.525,109.699,130.735,112.173,162.813,250.264,104.945,231.326,211.772,229.120,237.090,184.120,219.246,215.416,137.900,198.263,154.434,272.426,243.309,210.380,202.783,234.805,269.223,244.740,143.560,223.938,176.362,209.716,267.550,211.201,220.523,218.286,153.916,218.616,217.452,240.742,184.382,193.670,165.289,164.356,147.815,234.247,181.518,234.251,236.844,194.643,223.255,200.827,247.004,183.799,97.650,226.586,211.685,239.476,237.157,222.431,221.188,211.171,238.332,208.901,152.484,237.264,209.832,305.178,225.788,244.719,226.250,203.029,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,b'03MAY23:10:11:25'

# Preprocess

## Change bytes to normal string

In [11]:
# Schools

df_sch_2018['CNT'] = df_sch_2018['CNT'].str.decode('utf-8')
df_sch_2022['CNT'] = df_sch_2022['CNT'].str.decode('utf-8')

In [12]:
# Schools

for col in df_sch_2018.select_dtypes(include=['object']):
    if isinstance(df_sch_2018[col].iloc[0], bytes):
        df_sch_2018[col] = df_sch_2018[col].str.decode('utf-8')

for col in df_sch_2022.select_dtypes(include=['object']):
    if isinstance(df_sch_2022[col].iloc[0], bytes):
        df_sch_2022[col] = df_sch_2022[col].str.decode('utf-8')

/var/folders/h2/xr6bwwrj22zgqdw659xpm_yr0000gn/T/ipykernel_57708/4212572245.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_sch_2018.select_dtypes(include=['object']):
/var/folders/h2/xr6bwwrj22zgqdw659xpm_yr0000gn/T/ipykernel_57708/4212572245.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_sch_2022.select_dtypes(include=['object']):

In [13]:
# Students

df_stu_2018['CNT'] = df_stu_2018['CNT'].str.decode('utf-8')
df_stu_2022['CNT'] = df_stu_2022['CNT'].str.decode('utf-8')

In [14]:
# Students

for col in df_stu_2018.select_dtypes(include=['object']):
    if isinstance(df_stu_2018[col].iloc[0], bytes):
        df_stu_2018[col] = df_stu_2018[col].str.decode('utf-8')

for col in df_stu_2022.select_dtypes(include=['object']):
    if isinstance(df_stu_2022[col].iloc[0], bytes):
        df_stu_2022[col] = df_stu_2022[col].str.decode('utf-8')

/var/folders/h2/xr6bwwrj22zgqdw659xpm_yr0000gn/T/ipykernel_57708/1678747239.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_stu_2018.select_dtypes(include=['object']):
/var/folders/h2/xr6bwwrj22zgqdw659xpm_yr0000gn/T/ipykernel_57708/1678747239.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_stu_2022.select_dtypes(include=['object']):

## Filter SEA countries

In [15]:
sea_countries = [
    "BRN",
    "IDN",
    "KHM",
    "MYS",
    "PHL",
    "SGP",
    "THA",
    "VNM"
] # NO MYANMAR AND TIMOR LESTE

In [16]:
# SEA Schools

df_sch_sea2018 = df_sch_2018[df_sch_2018['CNT'].isin(sea_countries)].reset_index(drop=True)
df_sch_sea2022 = df_sch_2022[df_sch_2022['CNT'].isin(sea_countries)].reset_index(drop=True)

In [17]:
# SEA Students

df_stu_sea2018 = df_stu_2018[df_stu_2018['CNT'].isin(sea_countries)].reset_index(drop=True)
df_stu_sea2022 = df_stu_2022[df_stu_2022['CNT'].isin(sea_countries)].reset_index(drop=True)

## Remove unnecessary and derived variables

In [18]:
# Schools

df_sch_sea2018 = df_sch_sea2018.loc[:, 'CNTRYID':'SC052Q03HA']
df_sch_sea2022 = df_sch_sea2022.loc[:, 'CNT':'SC209Q06JA']

In [19]:
df_sch_sea2018.head()

,CNTRYID,CNT,CNTSCHID,CYC,NatCen,Region,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC161Q01SA,SC161Q02SA,SC161Q03SA,SC161Q04SA,SC161Q05SA,SC162Q01SA,SC155Q01HA,SC155Q02HA,SC155Q03HA,SC155Q04HA,SC155Q05HA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC156Q01HA,SC156Q02HA,SC156Q03HA,SC156Q04HA,SC156Q05HA,SC156Q06HA,SC156Q07HA,SC156Q08HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC012Q07TA,SC042Q01TA,SC042Q02TA,SC154Q01HA,SC154Q02WA,SC154Q03WA,SC154Q04WA,SC154Q05WA,SC154Q06WA,SC154Q07WA,SC154Q08WA,SC154Q09HA,SC154Q10WA,SC154Q11HA,SC036Q01TA,SC036Q02TA,SC036Q03NA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC037Q10NA,SC165Q01HA,SC165Q02HA,SC165Q03HA,SC165Q04HA,SC165Q05HA,SC165Q06HA,SC165Q07HA,SC165Q08HA,SC165Q09HA,SC165Q10HA,SC166Q02HA,SC166Q03HA,SC166Q05HA,SC166Q06HA,SC167Q01HA,SC167Q02HA,SC167Q03HA,SC167Q04HA,SC167Q05HA,SC167Q06HA,SC158Q01HA,SC158Q02HA,SC158Q04HA,SC158Q07HA,SC158Q08HA,SC158Q09HA,SC158Q12HA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC048Q01NA,SC048Q02NA,SC048Q03NA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q04NA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC018Q05NA01,SC018Q05NA02,SC018Q06NA01,SC018Q06NA02,SC018Q07NA01,SC018Q07NA02,SC025Q01NA,SC159Q01HA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q12IA,SC053Q13IA,SC053Q09TA,SC053Q10TA,SC053Q14IA,SC053Q15IA,SC053Q16IA,SC053D11TA,SC150Q01IA,SC150Q02IA,SC150Q03IA,SC150Q04IA,SC150Q05IA,SC164Q01HA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,SC152Q01HA,SC160Q01WA,SC052Q01NA,SC052Q02NA,SC052Q03HA
0,96.0,BRN,9600001.0,07MS,009600,9600.0,BRN0308,0960000,0.0,2.0,313.0,3.0,2.0,0.0,100.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,4.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,871.0,826.0,100.0,0.0,4.0,116.0,42.0,42.0,0.0,2.0,17.0,8.0,88.0,1.0,88.0,0.0,25.0,1.0,20.0,0.0,1.0,0.0,18.0,1.0,6.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,0096001,2.0,2.0,2.0,2.0,2.0,0.0,31.0,21.0,1.0,2.0,2.0,NaN,1.0,2.0,1.0
1,96.0,BRN,9600002.0,07MS,009600,9600.0,BRN0102,0960000,0.0,2.0,313.0,2.0,1.0,95.0,0.0,5.0,0.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,3.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,340.0,294.0,100.0,5.0,85.0,121.0,60.0,60.0,0.0,2.0,10.0,15.0,74.0,0.0,72.0,0.0,53.0,0.0,10.0,0.0,0.0,0.0,91.0,2.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,0096002,1.0,2.0,2.0,1.0,2.0,34.0,95.0,53.0,17.0,5.0,2.0,NaN,2.0,2.0,1.0
2,96.0,BRN,9600003.0,07MS,009600,9600.0,BRN0102,0960000,0.0,2.0,313.0,3.0,1.0,90.0,10.0,0.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,0.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,4.0,4.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,454.0,467.0,90.0,3.0,14.0,195.0,80.0,80.0,20.0,4.0,40.0,80.0,100.0,2.0,98.0,0.0,86.0,0.0,9.0,0.0,0.0,0.0,100.0,2.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,0096001,1.0,2.0,2.0,2.0,2.0,20.0,50.0,51.0,5.0,5.0,1.0,2.0,2.0,1.0,1.0
3,96.0,BRN,9600004.0,07MS,009600,9600.0,BRN0202,0960000,0.0,2.0,313.0,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,0.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,1.0,3.0,40.0,212.0,113.0,100.0,0.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,77.0,2.0,15.0,0.0,0.0,0.0,100.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,0096001,1.0,2.0,2.0,2.0,2.0,43.0,40.0,40.0,20.0,2.0,1.0,1.0,2.0,1.0,1.0
4,96.0,BRN,9600005.0,07MS,009600,9600.0,BRN0308,0960000,0.0,2.0,313.0,3.0,2.0,0.0,100.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,4.0,4.0,4.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,412.0,384.0,90.0,0.0,3.0,159.0,35.0,35.0,0.0,0.0,0.0,51.0,48.0,6.0,48.0,6.0,30.0,4.0,12.0,0.0,0.0,0.0,95.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,0096002,2.0,2.0,1.0,1.0,2.0,5.0,75.0,20.0,1.0,60.0,1.0,3.0,2.0,1.0,1.0

In [20]:
cols_to_remove_18 = [
    "CNTRYID", "CYC", "NatCen", "Region",
    "SUBNATIO", "OECD", "ADMINMODE", "LANGTEST"
]

df_sch_sea2018 = df_sch_sea2018.drop(cols_to_remove_18, axis=1,)

In [21]:
cols_to_remove_22 = [
    "CNTRYID", "CYC", "NatCen", "REGION",
    "SUBNATIO", "OECD", "ADMINMODE", "LANGTEST_QQQ"
]

df_sch_sea2022 = df_sch_sea2022.drop(cols_to_remove_22, axis=1,)

### Drop SC053D11TA - country specific question

In [22]:
df_sch_sea2018 = df_sch_sea2018.drop('SC053D11TA', axis=1,)
df_sch_sea2022 = df_sch_sea2022.drop('SC053D11TA', axis=1,)

# Common Columns

In [23]:
sch_common_cols = df_sch_sea2018.columns.intersection(df_sch_sea2022.columns)
sch_common_cols

Index(['CNT', 'CNTSCHID', 'STRATUM', 'SC001Q01TA', 'SC013Q01TA', 'SC016Q01TA',
       'SC016Q02TA', 'SC016Q03TA', 'SC016Q04TA', 'SC017Q01NA', 'SC017Q02NA',
       'SC017Q03NA', 'SC017Q04NA', 'SC017Q05NA', 'SC017Q06NA', 'SC017Q07NA',
       'SC017Q08NA', 'SC155Q06HA', 'SC155Q07HA', 'SC155Q08HA', 'SC155Q09HA',
       'SC155Q10HA', 'SC155Q11HA', 'SC011Q01TA', 'SC012Q01TA', 'SC012Q02TA',
       'SC012Q03TA', 'SC012Q04TA', 'SC012Q05TA', 'SC012Q06TA', 'SC042Q01TA',
       'SC042Q02TA', 'SC037Q01TA', 'SC037Q02TA', 'SC037Q03TA', 'SC037Q04TA',
       'SC037Q05NA', 'SC037Q06NA', 'SC037Q07TA', 'SC037Q08TA', 'SC037Q09TA',
       'SC061Q01TA', 'SC061Q02TA', 'SC061Q03TA', 'SC061Q04TA', 'SC061Q05TA',
       'SC061Q11HA', 'SC061Q06TA', 'SC061Q07TA', 'SC061Q08TA', 'SC061Q09TA',
       'SC061Q10TA', 'SC002Q01TA', 'SC002Q02TA', 'SC004Q01TA', 'SC004Q02TA',
       'SC004Q03TA', 'SC004Q05NA', 'SC004Q06NA', 'SC004Q07NA', 'SC018Q01TA01',
       'SC018Q01TA02', 'SC018Q02TA01', 'SC018Q02TA02', 'SC025Q01NA',
       'SC003Q01TA', 'SC053Q01TA', 'SC053Q02TA', 'SC053Q03TA', 'SC053Q04TA',
       'SC053Q09TA', 'SC053Q10TA', 'SC064Q01TA', 'SC064Q02TA', 'SC064Q03TA',
       'SC064Q04NA'],
      dtype='str')

In [24]:
len(sch_common_cols)

76

In [25]:
df_sch_sea2018_common = df_sch_sea2018[sch_common_cols].copy()
df_sch_sea2022_common = df_sch_sea2022[sch_common_cols].copy()

In [26]:
df_sch_sea2018_common

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,871.0,826.0,116.0,42.0,42.0,2.0,17.0,8.0,88.0,1.0,88.0,0.0,18.0,6.0,2.0,1.0,1.0,2.0,1.0,1.0,31.0,21.0,1.0,2.0
1,BRN,9600002.0,BRN0102,2.0,1.0,95.0,0.0,5.0,0.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,340.0,294.0,121.0,60.0,60.0,2.0,10.0,15.0,74.0,0.0,72.0,0.0,91.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,95.0,53.0,17.0,5.0
2,BRN,9600003.0,BRN0102,3.0,1.0,90.0,10.0,0.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,454.0,467.0,195.0,80.0,80.0,4.0,40.0,80.0,100.0,2.0,98.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,50.0,51.0,5.0,5.0
3,BRN,9600004.0,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0
4,BRN,9600005.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,412.0,384.0,159.0,35.0,35.0,0.0,0.0,51.0,48.0,6.0,48.0,6.0,95.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,75.0,20.0,1.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1432,THA,76400287.0,THA9797,4.0,1.0,20.0,70.0,5.0,5.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,895.0,823.0,270.0,200.0,200.0,10.0,20.0,60.0,137.0,0.0,80.0,0.0,100.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,90.0,50.0,100.0
1433,THA,76400288.0,THA9797,2.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,216.0,503.0,96.0,96.0,96.0,4.0,40.0,60.0,61.0,30.0,61.0,30.0,99.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,60.0,62.0,65.0
1434,THA,76400289.0,THA9797,3.0,1.0,73.0,27.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,553.0,668.0,123.0,40.0,40.0,0.0,8.0,25.0,60.0,7.0,60.0,7.0,98.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,100.0,20.0,0.0
1435,THA,76400290.0,THA9797,1.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,10.0,10.0,0.0,1.0,10.0,12.0,0.0,12.0,0.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,40.0,100.0,70.0
1436,THA,76400291.0,THA9797,3.0,2.0,46.0,54.0,0.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,3.0,1.0,454.0,400.0,215.0,60.0,60.0,0.0,5.0,20.0,97.0,0.0,82.0,0.0,90.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,25.0,55.0,10.0

In [27]:
missing_percent_common18 = df_sch_sea2018_common.isna().mean() * 100
missing_percent_common18 = missing_percent_common18.sort_values(ascending=False)

missing_percent_common18

SC018Q02TA02    25.121781
SC018Q01TA02    19.415449
SC016Q04TA      18.371608
SC016Q03TA      14.752958
SC013Q01TA      14.613779
                  ...
SC011Q01TA       3.897008
SC001Q01TA       3.757829
CNTSCHID         0.000000
STRATUM          0.000000
CNT              0.000000
Length: 76, dtype: float64

In [28]:
missing_percent_common22 = df_sch_sea2022_common.isna().mean() * 100
missing_percent_common22 = missing_percent_common22.sort_values(ascending=False)

missing_percent_common22.keys()

Index(['SC012Q03TA', 'SC012Q05TA', 'SC155Q11HA', 'SC155Q10HA', 'SC155Q09HA',
       'SC155Q08HA', 'SC155Q07HA', 'SC155Q06HA', 'SC004Q03TA', 'SC004Q01TA',
       'SC053Q02TA', 'SC053Q03TA', 'SC004Q05NA', 'SC053Q01TA', 'SC004Q02TA',
       'SC053Q04TA', 'SC004Q07NA', 'SC004Q06NA', 'SC053Q09TA', 'SC053Q10TA',
       'SC042Q02TA', 'SC042Q01TA', 'SC003Q01TA', 'SC064Q04NA', 'SC018Q02TA01',
       'SC064Q03TA', 'SC018Q02TA02', 'SC012Q06TA', 'SC018Q01TA02',
       'SC002Q01TA', 'SC002Q02TA', 'SC012Q02TA', 'SC016Q03TA', 'SC064Q01TA',
       'SC037Q07TA', 'SC012Q04TA', 'SC001Q01TA', 'SC016Q02TA', 'SC016Q04TA',
       'SC017Q03NA', 'SC064Q02TA', 'SC016Q01TA', 'SC061Q03TA', 'SC037Q03TA',
       'SC061Q10TA', 'SC012Q01TA', 'SC025Q01NA', 'SC018Q01TA01', 'SC017Q06NA',
       'SC017Q05NA', 'SC017Q02NA', 'SC017Q04NA', 'SC061Q06TA', 'SC061Q02TA',
       'SC061Q01TA', 'SC017Q08NA', 'SC017Q01NA', 'SC017Q07NA', 'SC037Q04TA',
       'SC061Q05TA', 'SC061Q09TA', 'SC061Q08TA', 'SC061Q07TA', 'SC061Q11HA',
       'SC061Q04TA', 'SC037Q08TA', 'SC037Q06NA', 'SC037Q01TA', 'SC037Q02TA',
       'SC037Q05NA', 'SC037Q09TA', 'SC011Q01TA', 'SC013Q01TA', 'CNTSCHID',
       'STRATUM', 'CNT'],
      dtype='str')

# 2022 Imputation

In [29]:
# Compositional block (must sum to 100)
comp_cols = ["SC016Q01TA", "SC016Q02TA", "SC016Q03TA", "SC016Q04TA"]

# Columns you want to impute overall (based on your missing% list)
cols_to_impute = ['SC012Q03TA', 'SC012Q05TA', 'SC155Q11HA', 'SC155Q10HA', 'SC155Q09HA',
       'SC155Q08HA', 'SC155Q07HA', 'SC155Q06HA', 'SC004Q03TA', 'SC004Q01TA',
       'SC053Q02TA', 'SC053Q03TA', 'SC004Q05NA', 'SC053Q01TA', 'SC004Q02TA',
       'SC053Q04TA', 'SC004Q07NA', 'SC004Q06NA', 'SC053Q09TA', 'SC053Q10TA',
       'SC042Q02TA', 'SC042Q01TA', 'SC003Q01TA', 'SC064Q04NA', 'SC018Q02TA01',
       'SC064Q03TA', 'SC018Q02TA02', 'SC012Q06TA', 'SC018Q01TA02',
       'SC002Q01TA', 'SC002Q02TA', 'SC012Q02TA', 'SC064Q01TA',
       'SC037Q07TA', 'SC001Q01TA', 'SC012Q04TA',
       'SC017Q03NA', 'SC064Q02TA', 'SC061Q03TA', 'SC037Q03TA',
       'SC012Q01TA', 'SC061Q10TA', 'SC025Q01NA', 'SC018Q01TA01', 'SC017Q06NA',
       'SC017Q05NA', 'SC017Q02NA', 'SC017Q04NA', 'SC061Q06TA', 'SC061Q02TA',
       'SC061Q01TA', 'SC017Q08NA', 'SC017Q01NA', 'SC017Q07NA', 'SC037Q04TA',
       'SC061Q04TA', 'SC061Q09TA', 'SC061Q08TA', 'SC061Q07TA', 'SC061Q11HA',
       'SC061Q05TA', 'SC037Q08TA', 'SC037Q06NA', 'SC037Q01TA', 'SC037Q02TA',
       'SC037Q05NA', 'SC037Q09TA', 'SC011Q01TA', 'SC013Q01TA',
       ]

## Compositional set of questions sum should be 100
- only 1 missing
- if no missing but sum isn't 100

In [30]:
# Compositional block (must sum to 100)
comp_cols = ["SC016Q01TA", "SC016Q02TA", "SC016Q03TA", "SC016Q04TA"]

# Work on a copy of just the compositional columns
comp = df_sch_sea2022_common[comp_cols].apply(pd.to_numeric, errors="coerce")

In [31]:
# How many missing parts per row?
miss_k = comp.isna().sum(axis=1)
miss_k.value_counts()

0    1646
4       7
3       1
1       1
Name: count, dtype: int64

In [32]:
# Case A: exactly 1 missing -> fill with 100 - sum(others)
mask_one = (miss_k == 1)
sum_obs = comp.sum(axis=1, skipna=True)
fill_val = 100 - sum_obs

for col in comp_cols:
    m = mask_one & comp[col].isna()
    comp.loc[m, col] = fill_val[m]

In [33]:
# Case B: no missing but sum != 100 -> rescale to sum to 100
row_sum = comp.sum(axis=1)
mask_full = (miss_k == 0) & row_sum.notna() & (row_sum > 0)

comp.loc[mask_full, comp_cols] = (
    comp.loc[mask_full, comp_cols]
    .div(row_sum[mask_full], axis=0) * 100
)

# Safety: keep within [0, 100]
comp[comp_cols] = comp[comp_cols].clip(0, 100)

# Write back
df_sch_sea2022_common[comp_cols] = comp

In [34]:
# quick check
print("Missing-count distribution (SC016):")
print(miss_k.value_counts().sort_index())

check_sum = df_sch_sea2022_common[comp_cols].sum(axis=1)
print("Rows with no-missing but not summing to 100 (after fix):",
      int(((miss_k == 0) & (check_sum.round(1) != 100)).sum()))

Missing-count distribution (SC016):
0    1646
1       1
3       1
4       7
Name: count, dtype: int64
Rows with no-missing but not summing to 100 (after fix): 0

## Non-compositional columns 
- oridnal
- binary
- count

In [35]:
non_comp_cols = [
    c for c in cols_to_impute
    if c not in comp_cols and c in df_sch_sea2022_common.columns
]

X_noncomp = df_sch_sea2022_common[non_comp_cols].copy()

# Force numeric safely
for c in non_comp_cols:
    X_noncomp[c] = pd.to_numeric(X_noncomp[c], errors="coerce")

In [36]:
non_comp_cols = [c for c in cols_to_impute if c not in comp_cols and c in df_sch_sea2022_common.columns]

X_noncomp = df_sch_sea2022_common[non_comp_cols].copy()
for c in non_comp_cols:
    X_noncomp[c] = pd.to_numeric(X_noncomp[c], errors="coerce")

it = IterativeImputer(
    estimator=ExtraTreesRegressor(n_estimators=200, random_state=42, n_jobs=1),
    max_iter=10,
    random_state=42
)

imputed = it.fit_transform(X_noncomp)

df_sch_sea2022_common[non_comp_cols] = pd.DataFrame(
    imputed, columns=non_comp_cols, index=df_sch_sea2022_common.index
)

/Users/Lenovo/Desktop/Personal/Projects/PISAxECAIR/PISAxECAIR-Research/.venv/lib/python3.13/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [39]:
df_sch_sea2022_common.head(25)

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,4.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,212.0,183.0,24.0,30.0,28.00,0.0,8.0,2.0,35.0,0.0,35.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,35.0,70.0,0.0,0.0
1,BRN,9600002.0,BRN02,4.0,1.0,95.0,0.0,5.0,0.0,2.0,1.0,4.0,1.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,687.0,161.0,67.0,67.00,4.0,50.0,103.0,120.0,8.0,120.0,8.0,96.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,57.0,44.0,16.0,10.0
2,BRN,9600003.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,4.0,1.0,481.0,397.0,185.0,71.0,67.00,3.0,6.0,105.0,107.0,0.0,8.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
3,BRN,9600004.0,BRN02,1.0,1.0,60.0,30.0,0.0,10.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,3.0,2.0,361.0,322.0,124.0,40.0,40.00,10.0,30.0,77.0,77.0,0.0,75.0,0.0,100.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,22.0,51.0,12.0,5.0
4,BRN,9600005.0,BRN08,2.0,2.0,0.0,85.0,15.0,0.0,4.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,3.0,3.0,1.0,3.0,1.0,2.0,40.0,35.0,58.0,20.0,20.00,0.0,17.0,3.0,66.0,0.0,66.0,0.0,26.0,9.0,2.0,2.0,2.0,1.0,2.0,1.0,5.0,15.0,11.0,16.0
5,BRN,9600006.0,BRN02,2.0,1.0,80.0,15.0,5.0,0.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,400.0,346.0,124.0,50.0,50.00,3.0,31.0,80.0,79.0,0.0,76.0,0.0,95.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,50.0,2.0,2.0
6,BRN,9600007.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,3.0,2.0,2.0,3.0,3.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,828.0,183.0,60.0,60.00,3.0,30.0,105.0,106.0,0.0,105.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,95.0,2.0,0.0
7,BRN,9600008.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,571.0,459.0,229.0,98.0,98.00,3.0,31.0,124.0,124.0,0.0,124.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,5.0,1.0,0.0
8,BRN,9600009.0,BRN05,2.0,1.0,60.0,40.0,0.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,206.0,226.0,47.0,41.0,41.00,4.0,20.0,6.0,71.0,0.0,71.0,0.0,100.0,8.0,1.0,1.0,2.0,1.0,2.0,1.0,20.0,20.0,0.0,0.0
9,BRN,9600010.0,BRN02,1.0,1.0,80.0,15.0,5.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,2.0,2.0,2.0,321.0,218.0,102.0,42.0,42.00,3.0,25.0,25.0,91.0,0.0,91.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,16.0,37.0,16.0,32.0
10,BRN,9600011.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,2.0,2.0,196.0,142.0,63.0,100.0,100.00,1.0,30.0,60.0,59.0,0.0,5.0,0.0,94.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,8.0,64.0,37.0,27.0
11,BRN,9600012.0,BRN03,2.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,246.0,361.0,384.0,141.0,141.00,2.0,19.0,142.0,90.0,0.0,90.0,0.0,100.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,65.0,5.0,1.0
12,BRN,9600013.0,BRN02,1.0,1.0,80.0,10.0,10.0,0.0,2.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,1.0,3.0,4.0,2.0,2.0,2.0,2.0,2.0,253.0,215.0,97.0,80.0,50.00,3.0,15.0,55.0,92.0,0.0,92.0,0.0,67.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,10.0,70.0,1.0,0.0
13,BRN,9600014.0,BRN05,3.0,1.0,100.0,0.0,0.0,0.0,3.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,155.0,196.0,55.0,30.0,30.00,3.0,15.0,80.0,136.0,0.0,136.0,0.0,60.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,90.0,70.0,20.0,5.0
14,BRN,9600015.0,BRN02,3.0,1.0,97.0,3.0,0.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,533.0,407.0,187.0,29.0,24.62,9.0,43.0,114.0,114.0,0.0,5.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,0.0,0.0,7.0,0.0
15,BRN,9600016.0,BRN05,3.0,1.0,100.0,0.0,0.0,0.0,3.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1998.0,0.0,310.0,240.0,0.00,0.0,68.0,213.0,213.0,0.0,213.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,70.0,70.0,0.0,0.0
16,BRN,9600017.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,3.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,629.0,506.0,229.0,45.0,45.00,4.0,13.0,105.0,122.0,0.0,122.0,0.0,100.0,4.0,1.0,2.0,1.0,1.0,1.0,1.0,25.0,35.0,3.0,0.0
17,BRN,9600018.0,BRN02,3.0,1.0,23.0,58.0,3.0,16.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,546.0,310.0,173.0,50.0,50.00,3.0,50.0,45.0,111.0,0.0,111.0,0.0,99.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,42.0,47.0,43.0,33.0
18,BRN,9600019.0,BRN03,3.0,1.0,32.0,46.0,13.0,9.0,3.0,1.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,2.0,3.0,3.0,1.0,1.0,3.0,1.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,355.0,596.0,549.0,156.0,156.00,5.0,65.0,157.0,120.0,0.0,120.0,0.0,90.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,10.0,5.0,1.0
19,BRN,9600020.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,4.0,2.0,4.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,1.0,3.0,1.0,2.0,3.0,3.0,2.0,1.0,3.0,2.0,450.0,413.0,81.0,52.0,50.00,0.0,20.0,5.0,54.0,0.0,54.0,0.0,0.0,6.0,2.0,2.0,2.0,1.0,1.0,1.0,89.0,87.0,0.0,2.0
20,BRN,9600021.0,BRN02,2.0,1.0,98.0,2.0,0.0,0.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,377.0,283.0,134.0,82.0,82.00,3.0,17.0,89.0,103.0,0.0,103.0,0.0,60.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,5.0,5.0,15.0,4.0
21,BRN,9600022.0,BRN02,4.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,3.0,2.0,2.0,2.0,3.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,512.0,248.0,163.0,33.0,23.00,4.0,12.0,116.0,124.0,0.0,120.0,0.0,90.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,10.0,25.0,10.0,5.0
22,BRN,9600023.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,391.0,348.0,144.0,83.0,83.00,3.0,6.0,111.0,114.0,0.0,8.0,0.0,100.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,22.0,23.0,23.0,63.0
23,BRN,9600024.0,BRN03,3.0,1.0,90.0,5.0,5.0,0.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,4.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,77.0,112.0,189.0,106.0,106.00,3.0,97.0,51.0,51.0,0.0,50.0,0.0,89.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,95.0,85.0,95.0,35.0
24,BRN,9600025.0,BRN05,1.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,4.0,1.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,1569.0,348.0,180.0,180.00,2.0,100.0,190.0,181.0,0.0,181.0,0.0,70.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,7.0,1.0,0.0,0.0

### enforce right schema for imputed values

In [43]:
SRC = Path.cwd().parent / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from data_schema import SCHEMA_GROUPS

In [44]:
def apply_schema_groups(df: pd.DataFrame, schema_groups):
    df = df.copy()
    for g in schema_groups:
        cols = [c for c in g["cols"] if c in df.columns]
        if not cols:
            continue

        # ensure numeric
        df[cols] = df[cols].apply(pd.to_numeric, errors="coerce")

        # apply post rules
        post = g.get("post", [])
        if "round" in post:
            df[cols] = df[cols].round()

        if "clip" in post:
            df[cols] = df[cols].clip(lower=g.get("min", None), upper=g.get("max", None))

        # enforce integer type for discrete types (optional but recommended)
        if g.get("type") in {"ordinal", "binary", "count"}:
            df[cols] = df[cols].astype("float")  # keeps NaN-safe integer dtype

    return df

df_sch_sea2022_common = apply_schema_groups(df_sch_sea2022_common, SCHEMA_GROUPS)

In [45]:
df_sch_sea2022_common[non_comp_cols].isna().sum().sort_values(ascending=False).head()

SC012Q03TA    0
SC017Q06NA    0
SC061Q01TA    0
SC061Q02TA    0
SC061Q06TA    0
dtype: int64

In [46]:
df_sch_sea2022_common.head(25)

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,4.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,212.0,183.0,24.0,30.0,28.0,0.0,8.0,2.0,35.0,0.0,35.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,35.0,70.0,0.0,0.0
1,BRN,9600002.0,BRN02,4.0,1.0,95.0,0.0,5.0,0.0,2.0,1.0,4.0,1.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,687.0,161.0,67.0,67.0,4.0,50.0,103.0,120.0,8.0,120.0,8.0,96.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,57.0,44.0,16.0,10.0
2,BRN,9600003.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,4.0,1.0,481.0,397.0,185.0,71.0,67.0,3.0,6.0,105.0,107.0,0.0,8.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
3,BRN,9600004.0,BRN02,1.0,1.0,60.0,30.0,0.0,10.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,3.0,2.0,361.0,322.0,124.0,40.0,40.0,10.0,30.0,77.0,77.0,0.0,75.0,0.0,100.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,22.0,51.0,12.0,5.0
4,BRN,9600005.0,BRN08,2.0,2.0,0.0,85.0,15.0,0.0,4.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,3.0,3.0,1.0,3.0,1.0,2.0,40.0,35.0,58.0,20.0,20.0,0.0,17.0,3.0,66.0,0.0,66.0,0.0,26.0,9.0,2.0,2.0,2.0,1.0,2.0,1.0,5.0,15.0,11.0,16.0
5,BRN,9600006.0,BRN02,2.0,1.0,80.0,15.0,5.0,0.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,400.0,346.0,124.0,50.0,50.0,3.0,31.0,80.0,79.0,0.0,76.0,0.0,95.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,50.0,2.0,2.0
6,BRN,9600007.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,3.0,2.0,2.0,3.0,3.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,828.0,183.0,60.0,60.0,3.0,30.0,105.0,106.0,0.0,105.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,95.0,2.0,0.0
7,BRN,9600008.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,571.0,459.0,229.0,98.0,98.0,3.0,31.0,124.0,124.0,0.0,124.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,5.0,1.0,0.0
8,BRN,9600009.0,BRN05,2.0,1.0,60.0,40.0,0.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,206.0,226.0,47.0,41.0,41.0,4.0,20.0,6.0,71.0,0.0,71.0,0.0,100.0,8.0,1.0,1.0,2.0,1.0,2.0,1.0,20.0,20.0,0.0,0.0
9,BRN,9600010.0,BRN02,1.0,1.0,80.0,15.0,5.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,2.0,2.0,2.0,321.0,218.0,102.0,42.0,42.0,3.0,25.0,25.0,91.0,0.0,91.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,16.0,37.0,16.0,32.0
10,BRN,9600011.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,2.0,2.0,196.0,142.0,63.0,100.0,100.0,1.0,30.0,60.0,59.0,0.0,5.0,0.0,94.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,8.0,64.0,37.0,27.0
11,BRN,9600012.0,BRN03,2.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,2.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,246.0,361.0,384.0,141.0,141.0,2.0,19.0,142.0,90.0,0.0,90.0,0.0,100.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,65.0,5.0,1.0
12,BRN,9600013.0,BRN02,1.0,1.0,80.0,10.0,10.0,0.0,2.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,1.0,3.0,4.0,2.0,2.0,2.0,2.0,2.0,253.0,215.0,97.0,80.0,50.0,3.0,15.0,55.0,92.0,0.0,92.0,0.0,67.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,10.0,70.0,1.0,0.0
13,BRN,9600014.0,BRN05,3.0,1.0,100.0,0.0,0.0,0.0,3.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,155.0,196.0,55.0,30.0,30.0,3.0,15.0,80.0,136.0,0.0,136.0,0.0,60.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,90.0,70.0,20.0,5.0
14,BRN,9600015.0,BRN02,3.0,1.0,97.0,3.0,0.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,533.0,407.0,187.0,29.0,25.0,9.0,43.0,114.0,114.0,0.0,5.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,0.0,0.0,7.0,0.0
15,BRN,9600016.0,BRN05,3.0,1.0,100.0,0.0,0.0,0.0,3.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1998.0,0.0,310.0,240.0,0.0,0.0,68.0,213.0,213.0,0.0,213.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,70.0,70.0,0.0,0.0
16,BRN,9600017.0,BRN02,2.0,1.0,100.0,0.0,0.0,0.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,3.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,629.0,506.0,229.0,45.0,45.0,4.0,13.0,105.0,122.0,0.0,122.0,0.0,100.0,4.0,1.0,2.0,1.0,1.0,1.0,1.0,25.0,35.0,3.0,0.0
17,BRN,9600018.0,BRN02,3.0,1.0,23.0,58.0,3.0,16.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,546.0,310.0,173.0,50.0,50.0,3.0,50.0,45.0,111.0,0.0,111.0,0.0,99.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,42.0,47.0,43.0,33.0
18,BRN,9600019.0,BRN03,3.0,1.0,32.0,46.0,13.0,9.0,3.0,1.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,2.0,3.0,3.0,1.0,1.0,3.0,1.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,355.0,596.0,549.0,156.0,156.0,5.0,65.0,157.0,120.0,0.0,120.0,0.0,90.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,10.0,5.0,1.0
19,BRN,9600020.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,4.0,2.0,4.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,1.0,3.0,1.0,2.0,3.0,3.0,2.0,1.0,3.0,2.0,450.0,413.0,81.0,52.0,50.0,0.0,20.0,5.0,54.0,0.0,54.0,0.0,0.0,6.0,2.0,2.0,2.0,1.0,1.0,1.0,89.0,87.0,0.0,2.0
20,BRN,9600021.0,BRN02,2.0,1.0,98.0,2.0,0.0,0.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,377.0,283.0,134.0,82.0,82.0,3.0,17.0,89.0,103.0,0.0,103.0,0.0,60.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,5.0,5.0,15.0,4.0
21,BRN,9600022.0,BRN02,4.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,3.0,2.0,2.0,2.0,3.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,512.0,248.0,163.0,33.0,23.0,4.0,12.0,116.0,124.0,0.0,120.0,0.0,90.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,10.0,25.0,10.0,5.0
22,BRN,9600023.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,391.0,348.0,144.0,83.0,83.0,3.0,6.0,111.0,114.0,0.0,8.0,0.0,100.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,22.0,23.0,23.0,63.0
23,BRN,9600024.0,BRN03,3.0,1.0,90.0,5.0,5.0,0.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,4.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,77.0,112.0,189.0,106.0,106.0,3.0,97.0,51.0,51.0,0.0,50.0,0.0,89.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,95.0,85.0,95.0,35.0
24,BRN,9600025.0,BRN05,1.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,4.0,1.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,1569.0,348.0,180.0,180.0,2.0,100.0,190.0,181.0,0.0,181.0,0.0,70.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,7.0,1.0,0.0,0.0

non-compositianl columns done, next proceed on imputing the comp cols with 2 or more missing using the whole non_comp cols

In [47]:
comp_cols = ["SC016Q01TA","SC016Q02TA","SC016Q03TA","SC016Q04TA"]

# how many missing per row?
miss_k = df_sch_sea2022_common[comp_cols].isna().sum(axis=1)
print(miss_k.value_counts().sort_index())

# sums for complete rows
row_sum = df_sch_sea2022_common[comp_cols].sum(axis=1)
bad_sum = ((miss_k == 0) & (row_sum.round(2) != 100)).sum()
print("Complete rows not summing to 100:", int(bad_sum))

0    1647
3       1
4       7
Name: count, dtype: int64
Complete rows not summing to 100: 0

In [48]:
# any remaining NaNs in columns you care about?
check_cols = non_comp_cols + comp_cols
print("Total NaNs in imputation columns:", int(df_sch_sea2022_common[check_cols].isna().sum().sum()))

# range checks quick (example)
print(df_sch_sea2022_common[comp_cols].describe())

Total NaNs in imputation columns: 31
        SC016Q01TA   SC016Q02TA   SC016Q03TA   SC016Q04TA
count  1648.000000  1647.000000  1647.000000  1647.000000
mean     77.981796    16.573163     3.550698     1.907711
std      28.521634    26.444616     8.838621     6.980618
min       0.000000     0.000000     0.000000     0.000000
25%      70.000000     0.000000     0.000000     0.000000
50%      90.000000     0.000000     0.000000     0.000000
75%     100.000000    24.000000     3.000000     0.000000
max     100.000000   100.000000    99.000000   100.000000

In [49]:
comp = df_sch_sea2022_common[comp_cols].copy()
miss_k = comp.isna().sum(axis=1)

mask_train = (miss_k == 0)
mask_hard = (miss_k >= 2)

print("Rows needing ILR:", int(mask_hard.sum()))

Rows needing ILR: 8

In [50]:
# For ILR based imputation helpers

def closure(X, total=100.0):
    X = np.asarray(X, dtype=float)
    row_sums = X.sum(axis=1, keepdims=True)
    return (X / row_sums) * total

def make_strictly_positive(X, eps=1e-6):
    X = np.asarray(X, dtype=float)
    return np.where(X <= 0, eps, X)

def clr(X):
    logX = np.log(X)
    gm = logX.mean(axis=1, keepdims=True)
    return logX - gm

def helmert_submatrix(D):
    H = np.zeros((D - 1, D))
    for i in range(1, D):
        H[i - 1, :i] = 1 / np.sqrt(i * (i + 1))
        H[i - 1, i] = -i / np.sqrt(i * (i + 1))
    return H

def ilr_transform(X):
    D = X.shape[1]
    H = helmert_submatrix(D)
    return clr(X) @ H.T

def ilr_inverse(Z):
    D = Z.shape[1] + 1
    H = helmert_submatrix(D)
    clrX = Z @ H
    return np.exp(clrX)

In [51]:
# Training compositions
comp_train = comp.loc[mask_train, comp_cols].to_numpy()
comp_train = make_strictly_positive(comp_train)
comp_train = closure(comp_train)

Z_train = ilr_transform(comp_train)

# Predictors (non_comp)
predictors_train = df_sch_sea2022_common.loc[mask_train, non_comp_cols]
predictors_test = df_sch_sea2022_common.loc[mask_hard, non_comp_cols]

Z_cols = [f"ILR_{i}" for i in range(Z_train.shape[1])]

train_df = predictors_train.copy()
for i, col in enumerate(Z_cols):
    train_df[col] = Z_train[:, i]

test_df = predictors_test.copy()
for col in Z_cols:
    test_df[col] = np.nan

combo = pd.concat([train_df, test_df], ignore_index=True)

In [52]:
it = IterativeImputer(
    estimator=ExtraTreesRegressor(n_estimators=200, random_state=42),
    max_iter=10,
    random_state=42
)

combo_imp = it.fit_transform(combo)
combo_imp = pd.DataFrame(combo_imp, columns=combo.columns)

Z_imputed = combo_imp.loc[len(train_df):, Z_cols].to_numpy()

/Users/Lenovo/Desktop/Personal/Projects/PISAxECAIR/PISAxECAIR-Research/.venv/lib/python3.13/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [55]:
comp_back = ilr_inverse(Z_imputed)
comp_back = make_strictly_positive(comp_back)
comp_back = closure(comp_back)

comp.loc[mask_hard, comp_cols] = comp_back
df_sch_sea2022_common[comp_cols] = comp

In [56]:
df_sch_sea2022_common[comp_cols].isna().sum()

SC016Q01TA    0
SC016Q02TA    0
SC016Q03TA    0
SC016Q04TA    0
dtype: int64

In [57]:
df_sch_sea2022_common[comp_cols].sum(axis=1).describe()

count    1.655000e+03
mean     1.000000e+02
std      8.559099e-16
min      1.000000e+02
25%      1.000000e+02
50%      1.000000e+02
75%      1.000000e+02
max      1.000000e+02
dtype: float64

In [58]:
print(df_sch_sea2022_common[comp_cols].describe())

        SC016Q01TA   SC016Q02TA   SC016Q03TA   SC016Q04TA
count  1655.000000  1655.000000  1655.000000  1655.000000
mean     77.990063    16.577100     3.534333     1.898505
std      28.547199    26.477401     8.820370     6.964969
min       0.000000     0.000000     0.000000     0.000000
25%      70.000000     0.000000     0.000000     0.000000
50%      90.000000     0.214113     0.000000     0.000000
75%     100.000000    24.000000     3.000000     0.000000
max     100.000000   100.000000    99.000000   100.000000

In [59]:
df_sch_sea2022_common[comp_cols]

      SC016Q01TA  SC016Q02TA  SC016Q03TA  SC016Q04TA
0            0.0        95.0         5.0         0.0
1           95.0         0.0         5.0         0.0
2          100.0         0.0         0.0         0.0
3           60.0        30.0         0.0        10.0
4            0.0        85.0        15.0         0.0
...          ...         ...         ...         ...
1650       100.0         0.0         0.0         0.0
1651        15.0        80.0         5.0         0.0
1652        70.0        25.0         5.0         0.0
1653        98.0         0.0         2.0         0.0
1654        95.0         2.0         1.0         2.0

[1655 rows x 4 columns]

In [60]:
check_cols = non_comp_cols + comp_cols
print(int(df_sch_sea2022_common[check_cols].isna().sum().sum()))

0

In [62]:
# # Save cleaned and imputed data

# df_sch_sea2022_common.to_csv("../data/processed/sch_sea2022_imputed.csv", index=False)

In [85]:
df_sch_sea2022_common

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,4.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,212.0,183.0,24.0,30.0,28.0,0.0,8.0,2.0,35.0,0.0,35.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,35.0,70.0,0.0,0.0
1,BRN,9600002.0,BRN02,4.0,1.0,95.0,0.0,5.0,0.0,2.0,1.0,4.0,1.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,687.0,161.0,67.0,67.0,4.0,50.0,103.0,120.0,8.0,120.0,8.0,96.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,57.0,44.0,16.0,10.0
2,BRN,9600003.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,4.0,1.0,481.0,397.0,185.0,71.0,67.0,3.0,6.0,105.0,107.0,0.0,8.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
3,BRN,9600004.0,BRN02,1.0,1.0,60.0,30.0,0.0,10.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,3.0,2.0,361.0,322.0,124.0,40.0,40.0,10.0,30.0,77.0,77.0,0.0,75.0,0.0,100.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,22.0,51.0,12.0,5.0
4,BRN,9600005.0,BRN08,2.0,2.0,0.0,85.0,15.0,0.0,4.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,3.0,3.0,1.0,3.0,1.0,2.0,40.0,35.0,58.0,20.0,20.0,0.0,17.0,3.0,66.0,0.0,66.0,0.0,26.0,9.0,2.0,2.0,2.0,1.0,2.0,1.0,5.0,15.0,11.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,THA,76400276.0,THA97,3.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,1.0,1.0,410.0,317.0,56.0,80.0,80.0,1.0,3.0,10.0,37.0,0.0,37.0,0.0,100.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,47.0,38.0,30.0,49.0
1651,THA,76400277.0,THA97,3.0,1.0,15.0,80.0,5.0,0.0,3.0,2.0,2.0,1.0,3.0,3.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,2.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,604.0,1148.0,324.0,200.0,200.0,2.0,45.0,100.0,74.0,0.0,23.0,0.0,85.0,6.0,1.0,2.0,2.0,1.0,1.0,1.0,65.0,86.0,90.0,35.0
1652,THA,76400278.0,THA97,5.0,1.0,70.0,25.0,5.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,4.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1511.0,1990.0,1200.0,100.0,100.0,15.0,80.0,100.0,170.0,10.0,170.0,0.0,90.0,6.0,1.0,2.0,1.0,1.0,1.0,1.0,89.0,86.0,50.0,69.0
1653,THA,76400279.0,THA97,1.0,1.0,98.0,0.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,132.0,113.0,25.0,28.0,28.0,1.0,3.0,14.0,18.0,0.0,18.0,0.0,100.0,4.0,1.0,2.0,1.0,1.0,2.0,1.0,57.0,57.0,100.0,10.0
1654,THA,76400280.0,THA97,2.0,2.0,95.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,1.0,1.0,3.0,1.0,19.0,22.0,39.0,14.0,14.0,0.0,5.0,5.0,26.0,0.0,20.0,0.0,100.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,38.0,49.0,33.0,45.0

In [89]:
sch_sea2022_imputed = df_sch_sea2022_common
sch_sea2022_imputed

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN08,3.0,2.0,0.0,95.0,5.0,0.0,4.0,3.0,3.0,1.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,212.0,183.0,24.0,30.0,28.0,0.0,8.0,2.0,35.0,0.0,35.0,0.0,100.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,35.0,70.0,0.0,0.0
1,BRN,9600002.0,BRN02,4.0,1.0,95.0,0.0,5.0,0.0,2.0,1.0,4.0,1.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,687.0,161.0,67.0,67.0,4.0,50.0,103.0,120.0,8.0,120.0,8.0,96.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,57.0,44.0,16.0,10.0
2,BRN,9600003.0,BRN02,1.0,1.0,100.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,4.0,1.0,481.0,397.0,185.0,71.0,67.0,3.0,6.0,105.0,107.0,0.0,8.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
3,BRN,9600004.0,BRN02,1.0,1.0,60.0,30.0,0.0,10.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,3.0,2.0,361.0,322.0,124.0,40.0,40.0,10.0,30.0,77.0,77.0,0.0,75.0,0.0,100.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,22.0,51.0,12.0,5.0
4,BRN,9600005.0,BRN08,2.0,2.0,0.0,85.0,15.0,0.0,4.0,1.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,3.0,3.0,1.0,3.0,1.0,2.0,40.0,35.0,58.0,20.0,20.0,0.0,17.0,3.0,66.0,0.0,66.0,0.0,26.0,9.0,2.0,2.0,2.0,1.0,2.0,1.0,5.0,15.0,11.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,THA,76400276.0,THA97,3.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,1.0,1.0,410.0,317.0,56.0,80.0,80.0,1.0,3.0,10.0,37.0,0.0,37.0,0.0,100.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,47.0,38.0,30.0,49.0
1651,THA,76400277.0,THA97,3.0,1.0,15.0,80.0,5.0,0.0,3.0,2.0,2.0,1.0,3.0,3.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,2.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,604.0,1148.0,324.0,200.0,200.0,2.0,45.0,100.0,74.0,0.0,23.0,0.0,85.0,6.0,1.0,2.0,2.0,1.0,1.0,1.0,65.0,86.0,90.0,35.0
1652,THA,76400278.0,THA97,5.0,1.0,70.0,25.0,5.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,4.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1511.0,1990.0,1200.0,100.0,100.0,15.0,80.0,100.0,170.0,10.0,170.0,0.0,90.0,6.0,1.0,2.0,1.0,1.0,1.0,1.0,89.0,86.0,50.0,69.0
1653,THA,76400279.0,THA97,1.0,1.0,98.0,0.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,132.0,113.0,25.0,28.0,28.0,1.0,3.0,14.0,18.0,0.0,18.0,0.0,100.0,4.0,1.0,2.0,1.0,1.0,2.0,1.0,57.0,57.0,100.0,10.0
1654,THA,76400280.0,THA97,2.0,2.0,95.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,1.0,1.0,3.0,1.0,19.0,22.0,39.0,14.0,14.0,0.0,5.0,5.0,26.0,0.0,20.0,0.0,100.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,38.0,49.0,33.0,45.0

# 2018 imputation

## Compositional set of questions sum should be 100
- only 1 missing
- if no missing but sum isn't 100

In [63]:
# Work on a copy of just the compositional columns
comp = df_sch_sea2018_common[comp_cols].apply(pd.to_numeric, errors="coerce")

In [64]:
# How many missing parts per row?
miss_k = comp.isna().sum(axis=1)
miss_k.value_counts()

0    1163
4      98
3      68
1      56
2      52
Name: count, dtype: int64

In [65]:
# Case A: exactly 1 missing -> fill with 100 - sum(others)
mask_one = (miss_k == 1)
sum_obs = comp.sum(axis=1, skipna=True)
fill_val = 100 - sum_obs

for col in comp_cols:
    m = mask_one & comp[col].isna()
    comp.loc[m, col] = fill_val[m]

In [66]:
# Case B: no missing but sum != 100 -> rescale to sum to 100
row_sum = comp.sum(axis=1)
mask_full = (miss_k == 0) & row_sum.notna() & (row_sum > 0)

comp.loc[mask_full, comp_cols] = (
    comp.loc[mask_full, comp_cols]
    .div(row_sum[mask_full], axis=0) * 100
)

# Safety: keep within [0, 100]
comp[comp_cols] = comp[comp_cols].clip(0, 100)

# Write back
df_sch_sea2018_common[comp_cols] = comp

In [67]:
# quick check
print("Missing-count distribution (SC016):")
print(miss_k.value_counts().sort_index())

check_sum = df_sch_sea2018_common[comp_cols].sum(axis=1)
print("Rows with no-missing but not summing to 100 (after fix):",
      int(((miss_k == 0) & (check_sum.round(1) != 100)).sum()))

Missing-count distribution (SC016):
0    1163
1      56
2      52
3      68
4      98
Name: count, dtype: int64
Rows with no-missing but not summing to 100 (after fix): 0

## Non-compositional columns 
- oridnal
- binary
- count

In [68]:
non_comp_cols = [
    c for c in cols_to_impute
    if c not in comp_cols and c in df_sch_sea2018_common.columns
]

X_noncomp = df_sch_sea2018_common[non_comp_cols].copy()

# Force numeric safely
for c in non_comp_cols:
    X_noncomp[c] = pd.to_numeric(X_noncomp[c], errors="coerce")

In [69]:
non_comp_cols = [c for c in cols_to_impute if c not in comp_cols and c in df_sch_sea2018_common.columns]

X_noncomp = df_sch_sea2018_common[non_comp_cols].copy()
for c in non_comp_cols:
    X_noncomp[c] = pd.to_numeric(X_noncomp[c], errors="coerce")

it = IterativeImputer(
    estimator=ExtraTreesRegressor(n_estimators=200, random_state=42, n_jobs=1),
    max_iter=10,
    random_state=42
)

imputed = it.fit_transform(X_noncomp)

df_sch_sea2018_common[non_comp_cols] = pd.DataFrame(
    imputed, columns=non_comp_cols, index=df_sch_sea2018_common.index
)

/Users/Lenovo/Desktop/Personal/Projects/PISAxECAIR/PISAxECAIR-Research/.venv/lib/python3.13/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [70]:
df_sch_sea2018_common.isna().sum().sort_values(ascending=False).head(10)

SC016Q04TA    215
SC016Q03TA    210
SC016Q02TA    167
SC016Q01TA    108
CNT             0
SC061Q08TA      0
SC004Q03TA      0
SC004Q02TA      0
SC004Q01TA      0
SC002Q02TA      0
dtype: int64

### enforce right schema for imputed values

In [71]:
df_sch_sea2018_common = apply_schema_groups(df_sch_sea2018_common, SCHEMA_GROUPS)

In [72]:
# check
df_sch_sea2018_common[non_comp_cols].isna().sum().sort_values(ascending=False).head()

SC012Q03TA    0
SC017Q06NA    0
SC061Q01TA    0
SC061Q02TA    0
SC061Q06TA    0
dtype: int64

non-compositianl columns done, next proceed on imputing the comp cols with 2 or more missing using the whole non_comp cols

In [73]:
# how many missing per row?
miss_k = df_sch_sea2018_common[comp_cols].isna().sum(axis=1)
print(miss_k.value_counts().sort_index())

# sums for complete rows
row_sum = df_sch_sea2018_common[comp_cols].sum(axis=1)
bad_sum = ((miss_k == 0) & (row_sum.round(2) != 100)).sum()
print("Complete rows not summing to 100:", int(bad_sum))

0    1219
2      52
3      68
4      98
Name: count, dtype: int64
Complete rows not summing to 100: 0

In [74]:
# any remaining NaNs in columns
check_cols = non_comp_cols + comp_cols
print("Total NaNs in imputation columns:", int(df_sch_sea2018_common[check_cols].isna().sum().sum()))

# range checks quick (example)
print(df_sch_sea2018_common[comp_cols].describe())

Total NaNs in imputation columns: 700
        SC016Q01TA   SC016Q02TA   SC016Q03TA   SC016Q04TA
count  1329.000000  1270.000000  1227.000000  1222.000000
mean     77.897667    17.651181     4.247759     2.246318
std      27.467644    26.167137     7.444667     7.684869
min       0.000000     0.000000     0.000000     0.000000
25%      70.000000     0.000000     0.000000     0.000000
50%      90.000000     5.000000     1.000000     0.000000
75%     100.000000    25.000000     5.000000     0.000000
max     100.000000   100.000000    55.000000   100.000000

In [75]:
comp = df_sch_sea2018_common[comp_cols].copy()
miss_k = comp.isna().sum(axis=1)

mask_train = (miss_k == 0)
mask_hard = (miss_k >= 2)

print("Rows needing ILR:", int(mask_hard.sum()))

Rows needing ILR: 218

In [76]:
# Training compositions
comp_train = comp.loc[mask_train, comp_cols].to_numpy()
comp_train = make_strictly_positive(comp_train)
comp_train = closure(comp_train)

Z_train = ilr_transform(comp_train)

# Predictors (non_comp)
predictors_train = df_sch_sea2018_common.loc[mask_train, non_comp_cols]
predictors_test = df_sch_sea2018_common.loc[mask_hard, non_comp_cols]

Z_cols = [f"ILR_{i}" for i in range(Z_train.shape[1])]

train_df = predictors_train.copy()
for i, col in enumerate(Z_cols):
    train_df[col] = Z_train[:, i]

test_df = predictors_test.copy()
for col in Z_cols:
    test_df[col] = np.nan

combo = pd.concat([train_df, test_df], ignore_index=True)

In [77]:
it = IterativeImputer(
    estimator=ExtraTreesRegressor(n_estimators=200, random_state=42),
    max_iter=10,
    random_state=42
)

combo_imp = it.fit_transform(combo)
combo_imp = pd.DataFrame(combo_imp, columns=combo.columns)

Z_imputed = combo_imp.loc[len(train_df):, Z_cols].to_numpy()

/Users/Lenovo/Desktop/Personal/Projects/PISAxECAIR/PISAxECAIR-Research/.venv/lib/python3.13/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [78]:
comp_back = ilr_inverse(Z_imputed)
comp_back = make_strictly_positive(comp_back)
comp_back = closure(comp_back)

comp.loc[mask_hard, comp_cols] = comp_back
df_sch_sea2018_common[comp_cols] = comp

In [79]:
df_sch_sea2018_common[comp_cols].isna().sum()

SC016Q01TA    0
SC016Q02TA    0
SC016Q03TA    0
SC016Q04TA    0
dtype: int64

In [80]:
df_sch_sea2018_common[comp_cols].sum(axis=1).describe()

count    1.437000e+03
mean     1.000000e+02
std      4.758345e-15
min      1.000000e+02
25%      1.000000e+02
50%      1.000000e+02
75%      1.000000e+02
max      1.000000e+02
dtype: float64

In [81]:
check_cols = non_comp_cols + comp_cols
print(int(df_sch_sea2018_common[check_cols].isna().sum().sum()))

0

In [82]:
df_sch_sea2018_common

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,871.0,826.0,116.0,42.0,42.0,2.0,17.0,8.0,88.0,1.0,88.0,0.0,18.0,6.0,2.0,1.0,1.0,2.0,1.0,1.0,31.0,21.0,1.0,2.0
1,BRN,9600002.0,BRN0102,2.0,1.0,95.0,0.0,5.0,0.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,340.0,294.0,121.0,60.0,60.0,2.0,10.0,15.0,74.0,0.0,72.0,0.0,91.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,95.0,53.0,17.0,5.0
2,BRN,9600003.0,BRN0102,3.0,1.0,90.0,10.0,0.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,454.0,467.0,195.0,80.0,80.0,4.0,40.0,80.0,100.0,2.0,98.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,50.0,51.0,5.0,5.0
3,BRN,9600004.0,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0
4,BRN,9600005.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,412.0,384.0,159.0,35.0,35.0,0.0,0.0,51.0,48.0,6.0,48.0,6.0,95.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,75.0,20.0,1.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1432,THA,76400287.0,THA9797,4.0,1.0,20.0,70.0,5.0,5.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,895.0,823.0,270.0,200.0,200.0,10.0,20.0,60.0,137.0,0.0,80.0,0.0,100.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,90.0,50.0,100.0
1433,THA,76400288.0,THA9797,2.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,216.0,503.0,96.0,96.0,96.0,4.0,40.0,60.0,61.0,30.0,61.0,30.0,99.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,60.0,62.0,65.0
1434,THA,76400289.0,THA9797,3.0,1.0,73.0,27.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,553.0,668.0,123.0,40.0,40.0,0.0,8.0,25.0,60.0,7.0,60.0,7.0,98.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,100.0,20.0,0.0
1435,THA,76400290.0,THA9797,1.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,12.0,10.0,10.0,0.0,1.0,10.0,12.0,0.0,12.0,0.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,40.0,100.0,70.0
1436,THA,76400291.0,THA9797,3.0,2.0,46.0,54.0,0.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,3.0,1.0,454.0,400.0,215.0,60.0,60.0,0.0,5.0,20.0,97.0,0.0,82.0,0.0,90.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,25.0,55.0,10.0

In [83]:
# # Save cleaned and imputed data

# df_sch_sea2018_common.to_csv("../data/processed/sch_sea2018_imputed.csv", index=False)

In [86]:
df_sch_sea2018_common

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA
0,BRN,9600001.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,871.0,826.0,116.0,42.0,42.0,2.0,17.0,8.0,88.0,1.0,88.0,0.0,18.0,6.0,2.0,1.0,1.0,2.0,1.0,1.0,31.0,21.0,1.0,2.0
1,BRN,9600002.0,BRN0102,2.0,1.0,95.0,0.0,5.0,0.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,340.0,294.0,121.0,60.0,60.0,2.0,10.0,15.0,74.0,0.0,72.0,0.0,91.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,95.0,53.0,17.0,5.0
2,BRN,9600003.0,BRN0102,3.0,1.0,90.0,10.0,0.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,454.0,467.0,195.0,80.0,80.0,4.0,40.0,80.0,100.0,2.0,98.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,50.0,51.0,5.0,5.0
3,BRN,9600004.0,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0
4,BRN,9600005.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,412.0,384.0,159.0,35.0,35.0,0.0,0.0,51.0,48.0,6.0,48.0,6.0,95.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,75.0,20.0,1.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1432,THA,76400287.0,THA9797,4.0,1.0,20.0,70.0,5.0,5.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,895.0,823.0,270.0,200.0,200.0,10.0,20.0,60.0,137.0,0.0,80.0,0.0,100.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,90.0,50.0,100.0
1433,THA,76400288.0,THA9797,2.0,1.0,100.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,216.0,503.0,96.0,96.0,96.0,4.0,40.0,60.0,61.0,30.0,61.0,30.0,99.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,60.0,60.0,62.0,65.0
1434,THA,76400289.0,THA9797,3.0,1.0,73.0,27.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,553.0,668.0,123.0,40.0,40.0,0.0,8.0,25.0,60.0,7.0,60.0,7.0,98.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,10.0,100.0,20.0,0.0
1435,THA,76400290.0,THA9797,1.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,12.0,10.0,10.0,0.0,1.0,10.0,12.0,0.0,12.0,0.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,40.0,100.0,70.0
1436,THA,76400291.0,THA9797,3.0,2.0,46.0,54.0,0.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,3.0,1.0,454.0,400.0,215.0,60.0,60.0,0.0,5.0,20.0,97.0,0.0,82.0,0.0,90.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,20.0,25.0,55.0,10.0

In [87]:
sch_sea2018_imputed = df_sch_sea2018_common

# Transform school data
- based on ecair remarks and comments

In [90]:
# Join dataset first

# df_2018 = pd.read_csv("../data/processed/sch_sea2018_imputed.csv")
# df_2022 = pd.read_csv("../data/processed/sch_sea2022_imputed.csv")

df_2018 = sch_sea2018_imputed
df_2022 = sch_sea2022_imputed

In [91]:
df_2018["YEAR"] = 2018
df_2022["YEAR"] = 2022

In [92]:
df_2018.shape

(1437, 77)

In [93]:
df_2022.shape

(1655, 77)

In [94]:
sch_sea_combined = pd.concat([df_2018, df_2022], ignore_index=True)

In [95]:
sch_sea_combined

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,YEAR
0,BRN,9600001.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,1.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,871.0,826.0,116.0,42.0,42.0,2.0,17.0,8.0,88.0,1.0,88.0,0.0,18.0,6.0,2.0,1.0,1.0,2.0,1.0,1.0,31.0,21.0,1.0,2.0,2018
1,BRN,9600002.0,BRN0102,2.0,1.0,95.0,0.0,5.0,0.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,340.0,294.0,121.0,60.0,60.0,2.0,10.0,15.0,74.0,0.0,72.0,0.0,91.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,95.0,53.0,17.0,5.0,2018
2,BRN,9600003.0,BRN0102,3.0,1.0,90.0,10.0,0.0,0.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,454.0,467.0,195.0,80.0,80.0,4.0,40.0,80.0,100.0,2.0,98.0,0.0,100.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,50.0,51.0,5.0,5.0,2018
3,BRN,9600004.0,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0,2018
4,BRN,9600005.0,BRN0308,3.0,2.0,0.0,100.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,412.0,384.0,159.0,35.0,35.0,0.0,0.0,51.0,48.0,6.0,48.0,6.0,95.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,75.0,20.0,1.0,60.0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3087,THA,76400276.0,THA97,3.0,1.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,1.0,1.0,410.0,317.0,56.0,80.0,80.0,1.0,3.0,10.0,37.0,0.0,37.0,0.0,100.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,47.0,38.0,30.0,49.0,2022
3088,THA,76400277.0,THA97,3.0,1.0,15.0,80.0,5.0,0.0,3.0,2.0,2.0,1.0,3.0,3.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,2.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,604.0,1148.0,324.0,200.0,200.0,2.0,45.0,100.0,74.0,0.0,23.0,0.0,85.0,6.0,1.0,2.0,2.0,1.0,1.0,1.0,65.0,86.0,90.0,35.0,2022
3089,THA,76400278.0,THA97,5.0,1.0,70.0,25.0,5.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,4.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1511.0,1990.0,1200.0,100.0,100.0,15.0,80.0,100.0,170.0,10.0,170.0,0.0,90.0,6.0,1.0,2.0,1.0,1.0,1.0,1.0,89.0,86.0,50.0,69.0,2022
3090,THA,76400279.0,THA97,1.0,1.0,98.0,0.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,132.0,113.0,25.0,28.0,28.0,1.0,3.0,14.0,18.0,0.0,18.0,0.0,100.0,4.0,1.0,2.0,1.0,1.0,2.0,1.0,57.0,57.0,100.0,10.0,2022
3091,THA,76400280.0,THA97,2.0,2.0,95.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,1.0,1.0,3.0,1.0,19.0,22.0,39.0,14.0,14.0,0.0,5.0,5.0,26.0,0.0,20.0,0.0,100.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,38.0,49.0,33.0,45.0,2022

In [96]:
# sch_sea_combined.to_csv("../data/processed/sch_combined_imputed.csv", index=False)

CREATE a variable for % of external funding by adding: Percentage of total funding for school year from: Benefactors, donations, bequests, sponsorships, parent fundraising AND Others. Policy Importance: Do schools that receive more external (non-government) funding have higher performance?

EXT_FUND = external funding other than government (student fees, school fee, donations, others)

In [97]:
# working copy of transformed df

sch_combined_transformed = sch_sea_combined.copy()

In [98]:
# Rows 7-10 (excel file)

sch_combined_transformed['EXT_FUND'] = (sch_combined_transformed['SC016Q02TA'] + sch_combined_transformed['SC016Q03TA'] + sch_combined_transformed['SC016Q04TA'])
sch_combined_transformed['EXT_FUND']

0       100.0
1         5.0
2        10.0
3        73.0
4       100.0
        ...
3087      0.0
3088     85.0
3089     30.0
3090      2.0
3091      5.0
Name: EXT_FUND, Length: 3092, dtype: float64

USE inadequate or poor quality educational material as the proxy for EDUCATIONAL MATERIALS, AND Inadequate or poor quality phyiscal infra as proxy for INFRA

EDU_MAT = inadequate or poor quality educational material

EDU_INFRA = Inadequate or poor quality phyiscal infra

In [99]:
sch_combined_transformed['EDU_MAT'] = sch_combined_transformed['SC017Q06NA']
sch_combined_transformed['EDU_INFRA'] = sch_combined_transformed['SC017Q08NA']

CREATE an index for digital capacity using the MEAN of the indicators

DIGI_CAP = schools capacity using digital devices

In [100]:
digi_cap_cols = ['SC155Q06HA', 'SC155Q07HA', 'SC155Q08HA', 'SC155Q09HA', 'SC155Q10HA', 'SC155Q11HA']

sch_combined_transformed['DIGI_CAP'] = (sch_combined_transformed[digi_cap_cols].mean(axis=1)).round(0)

Leaning towards just using external evaluation. Since the other indicators are basic elements of school operations -- and theyre just answered by yes or no --  little inference can be derived on their implementation. Whereas external assurance is not always applicable for schools. Can we generate a chart for this to check?

- we'll just retain SC037Q02TA - Quality assurance at school: External evaluation

In [101]:
quality_assurance = [
    'SC037Q01TA', 'SC037Q02TA', 'SC037Q03TA', 'SC037Q04TA', 'SC037Q05NA', 
    'SC037Q06NA', 'SC037Q07TA', 'SC037Q08TA', 'SC037Q09TA', 
]

In [102]:
sch_combined_transformed['SC037Q02TA'].value_counts()

SC037Q02TA
1.0    2208
2.0     633
3.0     251
Name: count, dtype: int64

USE absenteeism as the proxy for student engagement

- we'll just retain SC061Q01TA - Extent to which student learning is hindered by: Student truancy

Student-teacher ratio
- STU_TCH

#'SC002Q01TA' - boys

#'SC002Q02TA' - girls

#'SC018Q01TA01' - full time teacher

#'SC018Q01TA02' - part time teacher

In [103]:
sch_combined_transformed['SC002Q01TA'].value_counts()

SC002Q01TA
0.0       63
379.0     51
377.0     11
350.0     10
391.0      9
          ..
1540.0     1
965.0      1
1660.0     1
604.0      1
19.0       1
Name: count, Length: 1214, dtype: int64

In [104]:
sch_combined_transformed[['SC002Q02TA', 'SC002Q01TA']].min()

SC002Q02TA    0.0
SC002Q01TA    0.0
dtype: float64

In [105]:
sch_combined_transformed['TOT_STU'] = sch_combined_transformed['SC002Q01TA'] + sch_combined_transformed['SC002Q02TA']
sch_combined_transformed['TOT_TCH'] = (sch_combined_transformed['SC018Q01TA01'] + (sch_combined_transformed['SC018Q01TA02'])/2 )

In [106]:
# sch_combined_transformed['TOT_STU'].min()

In [107]:
sch_combined_transformed[sch_combined_transformed['TOT_TCH'] == 0]

,CNT,CNTSCHID,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,YEAR,EXT_FUND,EDU_MAT,EDU_INFRA,DIGI_CAP,TOT_STU,TOT_TCH
1420,THA,76400275.0,THA9797,3.0,1.0,40.0,30.0,20.0,10.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,573.0,597.0,380.0,300.0,300.0,5.0,120.0,120.0,0.0,0.0,0.0,0.0,90.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,90.0,90.0,90.0,90.0,2018,60.0,3.0,3.0,3.0,1170.0,0.0
2843,THA,76400031.0,THA97,4.0,2.0,100.0,0.0,0.0,0.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1187.0,2481.0,616.0,60.0,60.0,1.0,1.0,10.0,0.0,0.0,24.0,0.0,100.0,7.0,2.0,1.0,1.0,1.0,1.0,1.0,61.0,61.0,59.0,63.0,2022,0.0,1.0,1.0,4.0,3668.0,0.0

In [108]:
# If TOT_TCH is 0, replace it with NaN, to avoid division by 0. Then fill NaN again with 0 after 

sch_combined_transformed['STU_TCH'] = (
    sch_combined_transformed['TOT_STU'] /
    sch_combined_transformed['TOT_TCH'].replace(0, np.nan)
).fillna(0).round(4)

In [109]:
# sch_combined_transformed['STU_TCH'] = ((sch_combined_transformed['SC002Q01TA'] + sch_combined_transformed['SC002Q02TA'] 
#                                ) / (sch_combined_transformed['SC018Q01TA01'] + (sch_combined_transformed['SC018Q01TA02'])/2 )).round(4)

In [110]:
# sch_combined_transformed['STU_TCH'].max()

Students-computer (connected to internet) ratio for 15 year olds

- STU_COMP

In [111]:
sch_combined_transformed['SC004Q03TA'].min()

np.float64(0.0)

In [112]:
sch_combined_transformed['STU_COMP'] = (
    sch_combined_transformed['SC004Q01TA'] / 
    sch_combined_transformed['SC004Q03TA'].replace(0, np.nan)
    ).fillna(0).round(4)

In [113]:
sch_combined_transformed['STU_COMP'].max()

np.float64(461.0)

Teacher-computer (connected to internet) ratio

- TCH_COMP

In [114]:
sch_combined_transformed['TCH_COMP'] = (sch_combined_transformed['TOT_TCH']  / 
                                        sch_combined_transformed['SC004Q07NA'].replace(0, np.nan)
                                        ).fillna(0).round(4)

In [115]:
sch_combined_transformed['TCH_COMP']

0       11.0625
1        4.9333
2        1.2625
3        3.8667
4        1.0000
         ...
3087     3.7000
3088     0.7400
3089     1.7500
3090     1.2857
3091     5.2000
Name: TCH_COMP, Length: 3092, dtype: float64

CREATE an index for extra curricular offerings using the SUM of all entries, where OFFERED = 1, NOT OFFERED = 0

- X_ACTIV

In [116]:
extra_curricular = [
    'SC053Q01TA', 'SC053Q02TA', 'SC053Q03TA', 'SC053Q04TA', 'SC053Q09TA', 'SC053Q10TA',
]

In [117]:
# Replace 2 with 0
sch_combined_transformed[extra_curricular] = (
    sch_combined_transformed[extra_curricular]
    .replace(2, 0)
)

In [118]:
sch_combined_transformed['X_ACTIV'] = sch_combined_transformed[extra_curricular].sum(axis=1)

In [120]:
sch_combined_transformed['X_ACTIV'].max()

np.float64(6.0)

CREATE an index for parent engagement using the MEAN of the indicators

- PRNT_ENG

In [121]:
parent_engagement = [
    'SC064Q01TA', 'SC064Q02TA', 'SC064Q03TA', 'SC064Q04NA', 
]

In [122]:
sch_combined_transformed['PRNT_ENG'] = sch_combined_transformed[parent_engagement].mean(axis=1)

In [123]:
sch_combined_transformed['PRNT_ENG']

0       13.75
1       42.50
2       27.75
3       25.50
4       39.00
        ...
3087    41.00
3088    69.00
3089    73.50
3090    56.00
3091    41.25
Name: PRNT_ENG, Length: 3092, dtype: float64

NOW drop the other Qs that was used

In [124]:
cols_to_drop = [
    'SC001Q01TA', 'SC016Q01TA', 'SC016Q02TA', 'SC016Q03TA', 'SC016Q04TA',
    'SC017Q01NA', 'SC017Q02NA', 'SC017Q03NA', 'SC017Q04NA', 'SC017Q05NA', 
    'SC017Q06NA', 'SC017Q07NA', 'SC017Q08NA',
    'SC155Q06HA', 'SC155Q07HA', 'SC155Q08HA', 'SC155Q09HA', 'SC155Q10HA', 'SC155Q11HA',
    'SC011Q01TA', 'SC012Q01TA', 'SC012Q02TA', 'SC012Q03TA', 'SC012Q04TA', 'SC012Q05TA', 'SC012Q06TA',
    'SC042Q01TA', 'SC042Q02TA', 'SC037Q01TA', 'SC037Q03TA', 'SC037Q04TA', 'SC037Q05NA', 
    'SC037Q06NA', 'SC037Q07TA', 'SC037Q08TA', 'SC037Q09TA', 'SC061Q02TA', 'SC061Q03TA', 'SC061Q04TA',
    'SC061Q05TA', 'SC061Q11HA', 'SC061Q06TA', 'SC061Q07TA', 'SC061Q08TA', 'SC061Q09TA', 'SC061Q10TA',
    'SC002Q01TA', 'SC002Q02TA', 'SC018Q01TA01', 'SC018Q01TA02', 'SC018Q02TA01', 'SC018Q02TA02', 
    'SC004Q01TA', 'SC004Q02TA', 'SC004Q03TA', 'SC004Q05NA', 'SC004Q06NA', 'SC004Q07NA',
    'SC003Q01TA', 'SC053Q01TA', 'SC053Q02TA', 'SC053Q03TA', 'SC053Q04TA', 'SC053Q09TA', 'SC053Q10TA',
    'SC064Q01TA', 'SC064Q02TA', 'SC064Q03TA', 'SC064Q04NA', 'TOT_STU', 'TOT_TCH'
]

In [125]:
sch_combined_transformed.shape

(3092, 88)

In [126]:
sch_combined_transformed = sch_combined_transformed.drop(cols_to_drop, axis=1)

In [127]:
sch_combined_transformed.shape

(3092, 17)

In [128]:
sch_combined_transformed

,CNT,CNTSCHID,STRATUM,SC013Q01TA,SC037Q02TA,SC061Q01TA,SC025Q01NA,YEAR,EXT_FUND,EDU_MAT,EDU_INFRA,DIGI_CAP,STU_TCH,STU_COMP,TCH_COMP,X_ACTIV,PRNT_ENG
0,BRN,9600001.0,BRN0308,2.0,3.0,1.0,18.0,2018,100.0,1.0,1.0,2.0,19.1751,2.7619,11.0625,4.0,13.75
1,BRN,9600002.0,BRN0102,1.0,1.0,2.0,91.0,2018,5.0,2.0,3.0,2.0,8.5676,2.0167,4.9333,5.0,42.50
2,BRN,9600003.0,BRN0102,1.0,1.0,1.0,100.0,2018,10.0,3.0,3.0,2.0,9.1188,2.4375,1.2625,3.0,27.75
3,BRN,9600004.0,BRN0202,1.0,1.0,2.0,100.0,2018,73.0,2.0,2.0,3.0,9.2586,2.1200,3.8667,5.0,25.50
4,BRN,9600005.0,BRN0308,2.0,1.0,2.0,95.0,2018,100.0,2.0,2.0,3.0,15.6078,4.5429,1.0000,6.0,39.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3087,THA,76400276.0,THA97,1.0,1.0,2.0,100.0,2022,0.0,2.0,1.0,4.0,19.6486,0.7000,3.7000,6.0,41.00
3088,THA,76400277.0,THA97,1.0,1.0,3.0,85.0,2022,85.0,3.0,2.0,4.0,23.6757,1.6200,0.7400,4.0,69.00
3089,THA,76400278.0,THA97,1.0,1.0,2.0,90.0,2022,30.0,1.0,1.0,4.0,20.0057,12.0000,1.7500,5.0,73.50
3090,THA,76400279.0,THA97,1.0,1.0,1.0,100.0,2022,2.0,1.0,1.0,3.0,13.6111,0.8929,1.2857,4.0,56.00
3091,THA,76400280.0,THA97,2.0,1.0,3.0,100.0,2022,5.0,1.0,1.0,3.0,1.5769,2.7857,5.2000,3.0,41.25

In [129]:
sch_combined_transformed.min()

CNT                 BRN
CNTSCHID      9600001.0
STRATUM         BRN0102
SC013Q01TA          1.0
SC037Q02TA          1.0
SC061Q01TA          1.0
SC025Q01NA          0.0
YEAR               2018
EXT_FUND            0.0
EDU_MAT             1.0
EDU_INFRA           1.0
DIGI_CAP            1.0
STU_TCH             0.0
STU_COMP            0.0
TCH_COMP            0.0
X_ACTIV             0.0
PRNT_ENG            0.0
dtype: object

In [130]:
# # save transformed data

# sch_combined_transformed.to_csv("../data/processed/sch_combined_transformed.csv", index=False)

# Join school and students data

## 2018

In [131]:
df_stu_sea2018.head()

,CNTRYID,CNT,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST_QQQ,LANGTEST_COG,LANGTEST_PAQ,BOOKID,ST001D01T,ST003D02T,ST003D03T,ST004D01T,ST005Q01TA,ST006Q01TA,ST006Q02TA,ST006Q03TA,ST006Q04TA,ST007Q01TA,ST008Q01TA,ST008Q02TA,ST008Q03TA,ST008Q04TA,ST011Q01TA,ST011Q02TA,ST011Q03TA,ST011Q04TA,ST011Q05TA,ST011Q06TA,ST011Q07TA,ST011Q08TA,ST011Q09TA,ST011Q10TA,ST011Q11TA,ST011Q12TA,ST011Q16NA,ST011D17TA,ST011D18TA,ST011D19TA,ST012Q01TA,ST012Q02TA,ST012Q03TA,ST012Q05NA,ST012Q06NA,ST012Q07NA,ST012Q08NA,ST012Q09NA,ST013Q01TA,ST019AQ01T,ST019BQ01T,ST019CQ01T,ST021Q01TA,ST125Q01NA,ST126Q01TA,ST127Q01TA,ST127Q02TA,ST127Q03TA,ST022Q01TA,ST023Q01TA,ST023Q02TA,ST023Q03TA,ST023Q04TA,ST023Q05TA,ST097Q01TA,ST097Q02TA,ST097Q03TA,ST097Q04TA,ST097Q05TA,ST100Q01TA,ST100Q02TA,ST100Q03TA,ST100Q04TA,ST102Q01TA,ST102Q02TA,ST102Q03TA,ST102Q04TA,ST211Q01HA,ST211Q02HA,ST211Q03HA,ST212Q01HA,ST212Q02HA,ST212Q03HA,ST104Q02NA,ST104Q03NA,ST104Q04NA,ST213Q01HA,ST213Q02HA,ST213Q03HA,ST213Q04HA,ST150Q01IA,ST150Q02IA,ST150Q03IA,ST150Q04HA,ST152Q05IA,ST152Q06IA,ST152Q07IA,ST152Q08IA,ST154Q01HA,ST153Q01HA,ST153Q02HA,ST153Q03HA,ST153Q04HA,ST153Q05HA,ST153Q06HA,ST153Q08HA,ST153Q09HA,ST153Q10HA,ST158Q01HA,ST158Q02HA,ST158Q03HA,ST158Q04HA,ST158Q05HA,ST158Q06HA,ST158Q07HA,ST160Q01IA,ST160Q02IA,ST160Q03IA,ST160Q04IA,ST160Q05IA,ST167Q01IA,ST167Q02IA,ST167Q03IA,ST167Q04IA,ST167Q05IA,ST168Q01HA,ST175Q01IA,ST176Q01IA,ST176Q02IA,ST176Q03IA,ST176Q05IA,ST176Q06IA,ST176Q07IA,ST161Q01HA,ST161Q02HA,ST161Q03HA,ST161Q06HA,ST161Q07HA,ST161Q08HA,ST163Q02HA,ST163Q03HA,ST163Q04HA,ST164Q01IA,ST164Q02IA,ST164Q03IA,ST164Q04IA,ST164Q05IA,ST164Q06IA,ST165Q01IA,ST165Q02IA,ST165Q03IA,ST165Q04IA,ST165Q05IA,ST166Q01HA,ST166Q02HA,ST166Q03HA,ST166Q04HA,ST166Q05HA,ST016Q01NA,ST036Q05TA,ST036Q06TA,ST036Q08TA,ST225Q01HA,ST225Q02HA,ST225Q03HA,ST225Q04HA,ST225Q05HA,ST225Q06HA,ST181Q02HA,ST181Q03HA,ST181Q04HA,ST182Q03HA,ST182Q04HA,ST182Q05HA,ST182Q06HA,ST183Q01HA,ST183Q02HA,ST183Q03HA,ST184Q01HA,ST185Q01HA,ST185Q02HA,ST185Q03HA,ST186Q05HA,ST186Q06HA,ST186Q07HA,ST186Q10HA,ST186Q09HA,ST186Q02HA,ST186Q01HA,ST186Q08HA,ST186Q03HA,ST208Q01HA,ST208Q02HA,ST208Q04HA,ST188Q01HA,ST188Q02HA,ST188Q03HA,ST188Q06HA,ST188Q07HA,ST034Q01TA,ST034Q02TA,ST034Q03TA,ST034Q04TA,ST034Q05TA,ST034Q06TA,ST196Q02HA,ST196Q03HA,ST196Q04HA,ST196Q05HA,ST196Q06HA,ST196Q07HA,ST197Q01HA,ST197Q02HA,ST197Q04HA,ST197Q07HA,ST197Q08HA,ST197Q09HA,ST197Q12HA,ST215Q01HA,ST215Q02HA,ST215Q03HA,ST215Q04HA,ST215Q05HA,ST216Q01HA,ST216Q02HA,ST216Q03HA,ST216Q04HA,ST216Q05HA,ST216Q06HA,ST218Q01HA,ST218Q02HA,ST218Q03HA,ST218Q04HA,ST218Q05HA,ST218Q06HA,ST218Q07HA,ST222Q01HA,ST222Q03HA,ST222Q04HA,ST222Q05HA,ST222Q06HA,ST222Q08HA,ST222Q09HA,ST222Q10HA,ST214Q01HA,ST214Q02HA,ST214Q03HA,ST214Q06HA,ST220Q01HA,ST220Q02HA,ST220Q03HA,ST220Q04HA,ST217Q01HA,ST217Q02HA,ST217Q03HA,ST217Q04HA,ST217Q05HA,ST219Q01HA,ST219Q02HA,ST219Q03HA,ST219Q04HA,ST219Q05HA,ST219Q06HA,ST204Q02HA,ST204Q03HA,ST204Q04HA,ST204Q05HA,ST177Q01HA,ST177Q02HA,ST177Q03HA,ST189Q01HA,ST221Q01HA,ST221Q02HA,ST221Q03HA,ST221Q04HA,ST221Q05HA,ST221Q06HA,ST221Q07HA,ST221Q08HA,ST221Q09HA,ST221Q11HA,ST223Q02HA,ST223Q04HA,ST223Q05HA,ST223Q08HA,ST123Q02NA,ST123Q03NA,ST123Q04NA,ST205Q01HA,ST205Q02HA,ST205Q03HA,ST205Q04HA,ST059Q01TA,ST059Q02TA,ST059Q03TA,ST059Q04HA,ST060Q01NA,ST061Q01NA,ST062Q01TA,ST062Q02TA,ST062Q03TA,ST038Q03NA,ST038Q04NA,ST038Q05NA,ST038Q06NA,ST038Q07NA,ST038Q08NA,ST207Q01HA,ST207Q02HA,ST207Q03HA,ST207Q04HA,ST207Q05HA,ST206Q01HA,ST206Q02HA,ST206Q03HA,ST206Q04HA,IC001Q01TA,IC001Q02TA,IC001Q03TA,IC001Q04TA,IC001Q05TA,IC001Q06TA,IC001Q07TA,IC001Q08TA,IC001Q09TA,IC001Q10TA,IC001Q11TA,IC009Q01TA,IC009Q02TA,IC009Q03TA,IC009Q05NA,IC009Q06NA,IC009Q07NA,IC009Q08TA,IC009Q09TA,IC009Q10NA,IC009Q11NA,IC002Q01HA,IC004Q01HA,IC005Q01TA,IC006Q01TA,IC007Q01TA,IC150Q01HA,IC150Q02HA,IC150Q03HA,IC150Q04HA,IC150Q05HA,IC150Q06HA,IC150Q07HA,IC150Q08HA,IC150Q09HA,IC151Q01HA,IC151Q02HA,IC151Q03HA,IC151Q04HA,IC151Q05HA,IC151Q06HA,IC151Q07HA,IC151Q08HA,IC151Q09HA,IC152Q01HA,IC152Q02HA,IC152Q03HA,IC152Q04HA,IC152Q05HA,IC152Q06HA,IC152Q07HA,IC152Q08HA,IC152Q09HA,IC008Q01TA,IC008Q02TA,IC008Q03TA,IC008Q04TA,IC008Q05TA,IC008Q07NA,IC008Q08TA,IC008Q09TA,IC008Q10TA,IC008Q11TA,IC008Q12TA,IC008Q13NA,IC010Q01TA,IC010Q02NA,IC010Q03TA,IC010Q04TA,IC010Q05NA,IC010Q06NA,IC010Q07TA,IC010Q08TA,IC010Q09NA,IC010Q10NA,IC010Q11HA,IC010Q12HA,IC011Q01TA,IC011Q02TA,IC011Q03TA,IC011Q04TA,IC011Q05TA,IC011Q06TA,IC011Q07TA,IC011Q08TA,IC011Q09TA,IC011Q10HA,IC013Q01NA,IC013Q04NA,IC013Q05NA,IC013Q11NA,IC013Q12NA,IC013Q13NA,IC014Q03NA,IC014Q04NA,IC014Q06NA,IC014Q08NA,IC014Q09NA,IC015Q02NA,IC015Q03NA,IC015Q05NA,IC015Q07NA,IC015Q09NA,IC016Q01NA,IC016Q02NA,IC016Q04NA,IC016Q05NA,IC016Q07NA,IC169Q01HA,EC031Q01TA,EC032Q01TA,EC033Q01NA,EC150Q01WA,EC150Q02WA,EC150Q03WA,EC150Q04WA,EC150Q05WA,EC150Q06WA,EC150Q07WA,EC150Q08WA,EC150Q09WA,EC150Q10WA,EC151Q01WA,EC151Q01WB,EC151Q01WC,EC151Q02WA,EC151Q02WB,EC151Q02WC,EC151Q03WA,EC151Q03WB,EC151Q03WC,EC151Q04WA,EC151Q04WB,EC151Q04WC,EC151Q05WA,EC151Q05WB,EC151Q05WC,EC152Q01HA,EC153Q01HA,EC153Q02HA,EC153Q03HA,EC153Q04HA,EC153Q05HA,EC153Q06HA,EC153Q07HA,EC153Q08HA,EC153Q09HA,EC153Q10HA,EC153Q11HA,EC160Q01HA,EC158Q01HA,EC158Q02HA,EC159Q01HA,EC159Q02HA,EC163Q01HA,EC163Q02HA,EC163Q03HA,EC163Q04HA,EC163Q05HA,EC163Q06HA,EC163Q07HA,EC162Q01HA,EC162Q02HA,EC162Q03HA,EC162Q04HA,EC162Q05HA,EC162Q06HA,EC162Q07HA,EC162Q08HA,EC154Q01IA,EC154Q02IA,EC154Q03IA,EC154Q04HA,EC154Q05IA,EC154Q06IA,EC154Q07IA,EC154Q08HA,EC154Q09IA,EC012Q01NA,EC012Q02NA,EC012Q04NA,EC012Q06NA,EC012Q07NA,EC012Q08NA,EC012Q13HA,EC012Q12NA,EC155Q01DA,EC155Q02DA,EC155Q03DA,EC155Q04HA,EC155Q05HA,WB150Q01HA,WB151Q01HA,WB152Q01HA,WB153Q01HA,WB153Q02HA,WB153Q03HA,WB153Q04HA,WB153Q05HA,WB154Q01HA,WB154Q02HA,WB154Q03HA,WB154Q04HA,WB154Q05HA,WB154Q06HA,WB154Q07HA,WB154Q08HA,WB154Q09HA,WB155Q01HA,WB155Q02HA,WB155Q03HA,WB155Q04HA,WB155Q05HA,WB155Q06HA,WB155Q07HA,WB155Q08HA,WB155Q09HA,WB155Q10HA,WB156Q01HA,WB158Q01HA,WB160Q01HA,WB161Q01HA,WB162Q01HA,WB162Q02HA,WB162Q03HA,WB162Q04HA,WB162Q05HA,WB162Q06HA,WB162Q07HA,WB162Q08HA,WB162Q09HA,WB163Q01HA,WB163Q02HA,WB163Q03HA,WB163Q04HA,WB163Q05HA,WB163Q06HA,WB163Q07HA,WB163Q08HA,WB164Q01HA,WB165Q01HA,WB166Q01HA,WB166Q02HA,WB166Q03HA,WB166Q04HA,WB167Q01HA,WB168Q01HA,WB168Q02HA,WB168Q03HA,WB168Q04HA,WB171Q01HA,WB171Q02HA,WB171Q03HA,WB171Q04HA,WB172Q01HA,WB173Q01HA,WB173Q02HA,WB173Q03HA,WB173Q04HA,WB176Q01HA,WB177Q01HA,WB177Q02HA,WB177Q03HA,WB177Q04HA,WB032Q01NA,WB032Q02NA,WB031Q01NA,WB178Q01HA,WB178Q02HA,WB178Q03HA,WB178Q04HA,WB178Q05HA,WB178Q06HA,WB178Q07HA,FL150Q01TA,FL150Q02TA,FL150Q03TA,FL151Q01HA,FL151Q02HA,FL164Q01HA,FL164Q02HA,FL164Q03HA,FL164Q04HA,FL164Q05HA,FL164Q06HA,FL164Q07HA,FL164Q08HA,FL164Q09HA,FL164Q10HA,FL164Q11HA,FL164Q12HA,FL164Q13HA,FL164Q14HA,FL164Q15HA,FL164Q16HA,FL164Q17HA,FL164Q18HA,FL165Q01HA,FL165Q02HA,FL165Q03HA,FL165Q04HA,FL166Q01HA,FL166Q02HA,FL166Q03HA,FL166Q05HA,FL166Q06HA,FL166Q07HA,FL153Q01HA,FL153Q02HA,FL153Q03HA,FL153Q04HA,FL153Q05HA,FL153Q06HA,FL167Q01HA,FL167Q02HA,FL167Q03HA,FL167Q04HA,FL167Q05HA,FL156Q01TA,FL156Q02TA,FL156Q03TA,FL156Q04TA,FL156Q05TA,FL156Q06TA,FL156Q07HA,FL159Q01HA,FL159Q02HA,FL159Q03HA,FL159Q04HA,FL160Q01HA,FL160Q02HA,FL160Q03HA,FL160Q04HA,FL161Q01HA,FL161Q02HA,FL161Q03HA,FL162Q01HA,FL162Q02HA,FL162Q03HA,FL162Q04HA,FL162Q05HA,FL162Q06HA,FL163Q01HA,FL163Q02HA,FL163Q03HA,FL163Q04HA,FL163Q05HA,FL168Q01HA,FL168Q02HA,FL168Q03HA,FL168Q04HA,FL168Q05HA,FL168Q06HA,FL168Q07HA,FL168Q08HA,FL169Q01HA,FL169Q02HA,FL169Q03HA,FL169Q04HA,PA001Q01TA,PA001Q02TA,PA001Q03TA,PA003Q01TA,PA003Q02TA,PA003Q03TA,PA003Q04HA,PA003Q05IA,PA003Q06IA,PA003Q07IA,PA154Q01IA,PA154Q02IA,PA154Q03IA,PA154Q04IA,PA154Q05IA,PA154Q06IA,PA154Q07IA,PA154Q08IA,PA154Q09IA,PA154Q10HA,PA155Q01IA,PA156Q01HA,PA156Q02HA,PA156Q03HA,PA156Q04HA,PA004Q02NA,PA004Q03NA,PA004Q04NA,PA008Q01TA,PA008Q02TA,PA008Q03TA,PA008Q04TA,PA008Q05TA,PA008Q06NA,PA008Q07NA,PA008Q08NA,PA008Q09NA,PA008Q10NA,PA009Q01NA,PA009Q02NA,PA009Q03NA,PA009Q04NA,PA009Q05NA,PA009Q06NA,PA009Q07NA,PA009Q08NA,PA009Q09NA,PA009Q10NA,PA009Q11NA,PA007Q01TA,PA007Q02TA,PA007Q03TA,PA007Q04TA,PA007Q05TA,PA007Q06TA,PA007Q07TA,PA007Q09NA,PA007Q11NA,PA007Q12NA,PA007Q13NA,PA007Q14NA,PA007Q15NA,PA005Q01TA,PA006Q01TA,PA006Q02TA,PA006Q03TA,PA006Q04TA,PA006Q05TA,PA006Q06TA,PA006Q07TA,PA006Q08TA,PA006Q09TA,PA006Q10TA,PA006Q11TA,PA006Q12HA,PA006Q13HA,PA006Q14HA,PA158Q01HA,PA158Q02IA,PA158Q03HA,PA158Q04IA,PA158Q05HA,PA159Q01HA,PA160Q01HA,PA160Q02HA,PA160Q03HA,PA160Q04HA,PA160Q05HA,PA161Q01HA,PA161Q02HA,PA161Q03HA,PA161Q05HA,PA161Q06HA,PA161Q07HA,PA162Q01HA,PA163Q01HA,PA166Q01HA,PA167Q02HA,PA167Q03HA,PA167Q04HA,PA167Q05HA,PA168Q01HA,PA168Q02HA,PA168Q03HA,PA168Q06HA,PA169Q01HA,PA169Q02HA,PA169Q03HA,PA169Q04HA,PA169Q05HA,PA169Q06HA,PA170Q01HA,PA170Q02HA,PA170Q04HA,PA170Q07HA,PA170Q08HA,PA170Q09HA,PA170Q12HA,PA171Q01HA,PA171Q03HA,PA171Q04HA,PA171Q05HA,PA171Q06HA,PA171Q08HA,PA171Q09HA,PA171Q10HA,PA172Q01WA,PA172Q02WA,PA172Q03WA,PA172Q04WA,PA172Q05WA,PA172Q06WA,PA018Q01NA,PA018Q02NA,PA018Q03NA,PA177Q01HA,PA177Q02HA,PA177Q03HA,PA177Q04HA,PA177Q05HA,PA177Q06HA,PA177Q07HA,PA177Q08HA,PA180Q01HA,PA182Q01HA,PA175Q01HA,PA175Q02HA,PA041Q01TA,PA042Q01TA,EFFORT1,EFFORT2,OCOD1,OCOD2,OCOD3,GRADE,AGE,PROGN,COBN_S,COBN_M,COBN_F,LANGN,ISCEDL,ISCEDD,ISCEDO,MISCED,FISCED,HISCED,PARED,MISCED_D,FISCED_D,HISCED_D,PAREDINT,BMMJ1,BFMJ2,HISEI,LANGMOTHER,LANGFATHER,LANGSIBLINGS,LANGFRIEND,LANGSCHMATES,IMMIG,DURECEC,REPEAT,BSMJ,MMINS,LMINS,SMINS,TMINS,FCFMLRTY,SCCHANGE,CHANGE,STUBMI,ESCS,UNDREM,METASUM,METASPAM,ICTHOME,ICTSCH,HOMEPOS,CULTPOSS,HEDRES,WEALTH,ICTRES,DISCLIMA,TEACHSUP,DIRINS,PERFEED,EMOSUPS,STIMREAD,ADAPTIVITY,TEACHINT,JOYREAD,SCREADCOMP,SCREADDIFF,PISADIFF,PERCOMP,PERCOOP,ATTLNACT,COMPETE,WORKMAST,GFOFAIL,EUDMO,SWBP,RESILIENCE,MASTGOAL,GCSELFEFF,GCAWARE,ATTIMM,INTCULT,PERSPECT,COGFLEX,RESPECT,AWACOM,GLOBMIND,DISCRIM,BELONG,BEINGBULLIED,ENTUSE,HOMESCH,USESCH,INTICT,COMPICT,AUTICT,SOIAICT,ICTCLASS,ICTOUTSIDE,INFOCAR,INFOJOB1,INFOJOB2,FLCONFIN,FLCONICT,FLSCHOOL,FLFAMILY,CURSUPP,EMOSUPP,PQSCHOOL,PASCHPOL,PRESUPP,JOYREADP,ATTIMMP,INTCULTP,GCAWAREP,BODYIMA,SOCONPA,W_FSTUWT,W_FSTURWT1,W_FSTURWT2,W_FSTURWT3,W_FSTURWT4,W_FSTURWT5,W_FSTURWT6,W_FSTURWT7,W_FSTURWT8,W_FSTURWT9,W_FSTURWT10,W_FSTURWT11,W_FSTURWT12,W_FSTURWT13,W_FSTURWT14,W_FSTURWT15,W_FSTURWT16,W_FSTURWT17,W_FSTURWT18,W_FSTURWT19,W_FSTURWT20,W_FSTURWT21,W_FSTURWT22,W_FSTURWT23,W_FSTURWT24,W_FSTURWT25,W_FSTURWT26,W_FSTURWT27,W_FSTURWT28,W_FSTURWT29,W_FSTURWT30,W_FSTURWT31,W_FSTURWT32,W_FSTURWT33,W_FSTURWT34,W_FSTURWT35,W_FSTURWT36,W_FSTURWT37,W_FSTURWT38,W_FSTURWT39,W_FSTURWT40,W_FSTURWT41,W_FSTURWT42,W_FSTURWT43,W_FSTURWT44,W_FSTURWT45,W_FSTURWT46,W_FSTURWT47,W_FSTURWT48,W_FSTURWT49,W_FSTURWT50,W_FSTURWT51,W_FSTURWT52,W_FSTURWT53,W_FSTURWT54,W_FSTURWT55,W_FSTURWT56,W_FSTURWT57,W_FSTURWT58,W_FSTURWT59,W_FSTURWT60,W_FSTURWT61,W_FSTURWT62,W_FSTURWT63,W_FSTURWT64,W_FSTURWT65,W_FSTURWT66,W_FSTURWT67,W_FSTURWT68,W_FSTURWT69,W_FSTURWT70,W_FSTURWT71,W_FSTURWT72,W_FSTURWT73,W_FSTURWT74,W_FSTURWT75,W_FSTURWT76,W_FSTURWT77,W_FSTURWT78,W_FSTURWT79,W_FSTURWT80,UNIT,WVARSTRR,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE,PV1GLCM,PV2GLCM,PV3GLCM,PV4GLCM,PV5GLCM,PV6GLCM,PV7GLCM,PV8GLCM,PV9GLCM,PV10GLCM,PV1RCLI,PV2RCLI,PV3RCLI,PV4RCLI,PV5RCLI,PV6RCLI,PV7RCLI,PV8RCLI,PV9RCLI,PV10RCLI,PV1RCUN,PV2RCUN,PV3RCUN,PV4RCUN,PV5RCUN,PV6RCUN,PV7RCUN,PV8RCUN,PV9RCUN,PV10RCUN,PV1RCER,PV2RCER,PV3RCER,PV4RCER,PV5RCER,PV6RCER,PV7RCER,PV8RCER,PV9RCER,PV10RCER,PV1RTSN,PV2RTSN,PV3RTSN,PV4RTSN,PV5RTSN,PV6RTSN,PV7RTSN,PV8RTSN,PV9RTSN,PV10RTSN,PV1RTML,PV2RTML,PV3RTML,PV4RTML,PV5RTML,PV6RTML,PV7RTML,PV8RTML,PV9RTML,PV10RTML,SENWT,VER_DAT,i
0,96.0,BRN,9600004.0,9600001.0,07MS,009600,BRN0202,0960000,0.0,2.0,313.0,313.0,NaN,19.0,10.0,8.0,2002.0,1.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,0096001,0096001,0096001,3.0,3.0,2.0,4.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,5.0,4.0,1.0,1.0,1.0,2.0,1.0,4.0,1.0,1.0,4.0,3.0,2.0,4.0,1.0,1.0,1.0,3.0,3.0,4.0,3.0,1.0,2.0,4.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,3.0,2.0,2.0,3.0,2.0,2.0,3.0,4.0,4.0,4.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,1.0,4.0,1.0,1.0,3.0,1.0,3.0,2.0,2.0,2.0,5.0,2.0,4.0,4.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,1.0,2.0,3.0,2.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,1.0,1.0,2.0,5.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,3.0,2.0,3.0,4.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,2.0,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,4.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,3.0,2.0,1.0,2.0,2.0,3.0,3.0,2.0,0.0,NaN,30.0,1.0,1.0,2.0,2.0,2.0,3.0,4.0,1.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,3.0,2.0,1.0,3.0,3.0,1.0,2.0,3.0,1.0,2.0,3.0,2.0,1.0,3.0,3.0,3.0,2.0,2.0,4.0,4.0,4.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,8.0,9701,0310,3339,0.0,15.67,00960003,009600,009600,009600,204.0,3.0,1.0,1.0,4.0,2.0,4.0,13.0,4.0,2.0,4.0,12.0,17.00,29.18,29.18,1.0,NaN,1.0,1.0,NaN,1.0,1.0,0.0,59.89,90.0,90.0,60.0,NaN,NaN,NaN,NaN,NaN,-1.5098,-0.94,-0.18,-0.50,6.0,6.0,-1.8332,-0.7380,-2.2894,-1.0142,-1.2346,-0.8055,-1.0051,-0.4800,-0.0008,0.2169,-0.3302,-0.1716,-0.8967,0.0495,-1.0985,1.2421,-0.5536,-1.2276,-1.5068,0.4626,-0.2661,-0.7233,-0.1300,-0.1652,-0.5928,-0.7906,-1.1295,-0.4064,-1.6307,0.3013,-1.0139,-0.3581,-1.5019,-1.0065,-0.5229,-0.3066,-1.1549,-0.6720,1.4812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.5,0.5,1.5,1.5,0.5,0.5,1.5,1.5,1.5,1.5,0.5,1.5,0.5,1.5,0.5,0.5,0.5,0.5,1.5,1.5,1.5,1.5,0.5,0.5,1.5,1.5,0.5,0.5,0.5,0.5,1.5,0.5,1.5,0.5,1.5,1.5,1.5,1.5,0.5,0.5,0.5,0.5,1.5,1.5,0.5,0.5,1.5,1.5,1.5,1.5,0.5,1.5,0.5,1.5,0.5,0.5,0.5,0.5,1.5,1.5,1.5,1.5,0.5,0.5,1.5,1.5,0.5,0.5,0.5,0.5,1.5,0.5,1.5,0.5,1.5,1.5,1.5,1.5,0.5,0.5,2.0,2.0,275.067,290.998,336.737,330.614,312.539,335.296,327.829,289.944,330.321,305.523,319.465,310.405,308.179,300.809,359.740,358.161,335.350,294.169,299.682,298.695,323.422,334.638,329.393,352.142,408.456,344.385,357.833,349.156,348.140,352.419,331.534,362.647,338.578,359.438,420.413,387.704,380.948,331.833,380.727,418.356,259.333,346.937,323.060,320.168,282.511,303.042,337.754,318.608,357.725,341.314,283.413,351.249,291.013,344.285,316.947,325.929,308.459,316.499,340.997,352.342,304.521,351.395,287.870,327.780,306.726,343.479,351.740,292.546,327.008,326.534,312.715,293.562,300.418,364.665,284.791,356.033,304.934,303.372,317.597,336.063,355.932,347.340,345.456,382.446,308.188,362.700,306.608,335.660,337.758,349.098,0.72474,26APR19:16:35:11,31.0

In [132]:
stu_cols_to_use = [
    'CNT', 'CNTSCHID', 'STRATUM', 'W_FSTUWT'
]

In [133]:
def select_student_columns(df):
    """
    Select base student columns + plausible values (PV) for READ, SCIE, MATH.
    """
    
    # Automatically detect PV columns
    pv_cols = [
        col for col in df.columns
        if col.startswith("PV") and (
            col.endswith("READ") or 
            col.endswith("SCIE") or 
            col.endswith("MATH")
        )
    ]
    
    # Combine
    selected_cols = stu_cols_to_use + pv_cols
    
    # Keep only those that exist
    selected_cols = [col for col in selected_cols if col in df.columns]
    
    return df[selected_cols]

In [134]:
stu_sea2018_selected = select_student_columns(df_stu_sea2018)

In [135]:
stu_sea2018_selected

,CNT,CNTSCHID,STRATUM,W_FSTUWT,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE
0,BRN,9600004.0,BRN0202,1.00000,275.067,290.998,336.737,330.614,312.539,335.296,327.829,289.944,330.321,305.523,319.465,310.405,308.179,300.809,359.740,358.161,335.350,294.169,299.682,298.695,323.422,334.638,329.393,352.142,408.456,344.385,357.833,349.156,348.140,352.419
1,BRN,9600039.0,BRN0305,1.00000,555.674,460.202,495.337,478.589,471.862,491.833,457.191,450.496,478.227,503.689,475.030,465.840,469.094,415.407,461.034,435.474,436.752,433.401,407.575,450.521,475.274,472.165,448.326,414.754,464.371,465.234,442.654,485.909,451.189,458.745
2,BRN,9600013.0,BRN0108,1.00000,425.360,486.858,411.810,430.167,429.450,453.949,460.655,431.025,460.361,456.282,453.792,530.047,465.644,476.962,479.157,497.856,481.355,475.571,471.243,425.406,499.008,567.237,495.634,503.307,511.941,518.323,493.969,517.028,550.967,489.528
3,BRN,9600050.0,BRN0202,1.00000,345.277,316.666,376.185,385.563,401.337,361.000,376.146,385.809,412.617,315.271,327.125,325.595,320.565,353.102,343.022,348.752,341.981,405.192,361.492,320.959,344.571,320.054,339.278,362.075,380.618,344.550,394.856,408.605,382.302,285.057
4,BRN,9600027.0,BRN0202,1.00000,346.777,405.205,365.882,360.179,356.404,358.281,345.493,346.018,386.261,373.041,321.345,397.084,327.124,341.422,394.604,361.078,358.206,321.249,393.726,378.057,330.973,378.861,371.351,323.333,421.665,381.724,364.725,334.241,392.926,394.971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52951,THA,76400106.0,THA9797,150.92110,199.875,183.180,225.954,199.218,259.279,223.655,320.576,248.441,206.047,331.424,220.324,285.543,265.257,252.527,314.335,265.025,308.561,264.870,258.568,297.110,375.998,378.414,409.545,377.569,392.156,350.719,347.057,369.638,352.643,427.839
52952,THA,76400135.0,THA9797,29.13095,386.395,435.647,276.291,316.536,318.367,395.364,351.692,402.633,312.802,357.105,386.339,380.325,385.797,381.200,370.740,419.941,429.899,412.020,413.865,382.374,462.133,360.445,439.549,429.359,409.703,482.126,481.432,453.209,419.090,400.232
52953,THA,76400203.0,THA9797,4.09524,324.223,333.682,314.040,403.046,322.272,377.554,393.129,335.877,371.572,339.427,395.957,334.763,339.990,368.075,351.758,367.211,384.145,340.148,356.452,331.126,442.525,458.038,388.542,416.169,420.501,448.306,436.786,411.982,433.277,384.902
52954,THA,76400249.0,THA9797,73.16701,439.873,401.274,464.562,447.062,480.282,473.885,460.090,428.821,440.797,420.929,443.631,428.644,442.820,420.651,454.126,455.620,471.519,421.873,466.373,431.838,440.451,403.399,410.809,415.782,409.362,419.196,436.752,401.772,436.684,434.819
52955,THA,76400161.0,THA9797,94.81347,475.689,429.177,324.006,302.024,434.834,392.526,341.561,434.600,323.916,360.017,321.743,349.722,336.858,389.868,388.472,320.348,388.681,352.496,342.782,349.120,308.027,304.275,351.592,353.523,363.197,294.971,362.870,295.423,290.423,312.822

In [136]:
# NO PV for VNM 2018

stu_sea2018_selected = stu_sea2018_selected[stu_sea2018_selected['CNT'] != 'VNM']

In [137]:
stu_sea2018_selected

,CNT,CNTSCHID,STRATUM,W_FSTUWT,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE
0,BRN,9600004.0,BRN0202,1.00000,275.067,290.998,336.737,330.614,312.539,335.296,327.829,289.944,330.321,305.523,319.465,310.405,308.179,300.809,359.740,358.161,335.350,294.169,299.682,298.695,323.422,334.638,329.393,352.142,408.456,344.385,357.833,349.156,348.140,352.419
1,BRN,9600039.0,BRN0305,1.00000,555.674,460.202,495.337,478.589,471.862,491.833,457.191,450.496,478.227,503.689,475.030,465.840,469.094,415.407,461.034,435.474,436.752,433.401,407.575,450.521,475.274,472.165,448.326,414.754,464.371,465.234,442.654,485.909,451.189,458.745
2,BRN,9600013.0,BRN0108,1.00000,425.360,486.858,411.810,430.167,429.450,453.949,460.655,431.025,460.361,456.282,453.792,530.047,465.644,476.962,479.157,497.856,481.355,475.571,471.243,425.406,499.008,567.237,495.634,503.307,511.941,518.323,493.969,517.028,550.967,489.528
3,BRN,9600050.0,BRN0202,1.00000,345.277,316.666,376.185,385.563,401.337,361.000,376.146,385.809,412.617,315.271,327.125,325.595,320.565,353.102,343.022,348.752,341.981,405.192,361.492,320.959,344.571,320.054,339.278,362.075,380.618,344.550,394.856,408.605,382.302,285.057
4,BRN,9600027.0,BRN0202,1.00000,346.777,405.205,365.882,360.179,356.404,358.281,345.493,346.018,386.261,373.041,321.345,397.084,327.124,341.422,394.604,361.078,358.206,321.249,393.726,378.057,330.973,378.861,371.351,323.333,421.665,381.724,364.725,334.241,392.926,394.971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52951,THA,76400106.0,THA9797,150.92110,199.875,183.180,225.954,199.218,259.279,223.655,320.576,248.441,206.047,331.424,220.324,285.543,265.257,252.527,314.335,265.025,308.561,264.870,258.568,297.110,375.998,378.414,409.545,377.569,392.156,350.719,347.057,369.638,352.643,427.839
52952,THA,76400135.0,THA9797,29.13095,386.395,435.647,276.291,316.536,318.367,395.364,351.692,402.633,312.802,357.105,386.339,380.325,385.797,381.200,370.740,419.941,429.899,412.020,413.865,382.374,462.133,360.445,439.549,429.359,409.703,482.126,481.432,453.209,419.090,400.232
52953,THA,76400203.0,THA9797,4.09524,324.223,333.682,314.040,403.046,322.272,377.554,393.129,335.877,371.572,339.427,395.957,334.763,339.990,368.075,351.758,367.211,384.145,340.148,356.452,331.126,442.525,458.038,388.542,416.169,420.501,448.306,436.786,411.982,433.277,384.902
52954,THA,76400249.0,THA9797,73.16701,439.873,401.274,464.562,447.062,480.282,473.885,460.090,428.821,440.797,420.929,443.631,428.644,442.820,420.651,454.126,455.620,471.519,421.873,466.373,431.838,440.451,403.399,410.809,415.782,409.362,419.196,436.752,401.772,436.684,434.819
52955,THA,76400161.0,THA9797,94.81347,475.689,429.177,324.006,302.024,434.834,392.526,341.561,434.600,323.916,360.017,321.743,349.722,336.858,389.868,388.472,320.348,388.681,352.496,342.782,349.120,308.027,304.275,351.592,353.523,363.197,294.971,362.870,295.423,290.423,312.822

In [138]:
COUNTRY_COL = "CNT"
SCHOOL_COL  = "CNTSCHID"
WEIGHT_COL  = "W_FSTUWT"
DOMAINS = ["MATH", "READ", "SCIE"]

def get_pv_cols(df, domain):
    pv = [c for c in df.columns if c.startswith("PV") and c.endswith(domain)]
    # sort PV1..PV10 by the number
    return sorted(pv, key=lambda x: int(x.replace("PV", "").replace(domain, "")))

def pisa_school_weighted_by_domain(stu_df):
    """
    Returns one row per (CNT, CNTSCHID) with:
      - <DOMAIN>_school_weighted (PISA-style: compute per PV then average over PVs)
      - optional per-PV school means can be kept if you want
    """
    df = stu_df.copy()
    group_cols = [COUNTRY_COL, SCHOOL_COL]

    # base output skeleton (unique schools)
    out = df[group_cols].drop_duplicates().copy()

    # ensure weight is numeric
    df[WEIGHT_COL] = pd.to_numeric(df[WEIGHT_COL], errors="coerce")

    for domain in DOMAINS:
        pv_cols = get_pv_cols(df, domain)
        if not pv_cols:
            continue

        per_pv_school = []

        for pv in pv_cols:
            x = pd.to_numeric(df[pv], errors="coerce")
            w = df[WEIGHT_COL]

            tmp = pd.DataFrame({
                COUNTRY_COL: df[COUNTRY_COL],
                SCHOOL_COL:  df[SCHOOL_COL],
                "xw": x * w,
                "w":  w
            }).dropna()

            # school weighted mean for this PV
            school_pv = (
                tmp.groupby(group_cols, as_index=False)
                   .agg(xw_sum=("xw", "sum"), w_sum=("w", "sum"))
            )
            school_pv[pv + "_school"] = school_pv["xw_sum"] / school_pv["w_sum"]
            school_pv = school_pv[group_cols + [pv + "_school"]]

            per_pv_school.append(school_pv)

        # merge all PV-school means for the domain
        dom_df = per_pv_school[0]
        for d in per_pv_school[1:]:
            dom_df = dom_df.merge(d, on=group_cols, how="outer")

        # PISA-style combine: mean across PV-school means
        pv_school_cols = [c for c in dom_df.columns if c.endswith("_school") and c.startswith("PV")]
        dom_df[f"PV{domain}_weighted"] = dom_df[pv_school_cols].mean(axis=1)

        # keep only final domain score (or keep pv_school_cols too if you want)
        dom_df = dom_df[group_cols + [f"PV{domain}_weighted"]]

        out = out.merge(dom_df, on=group_cols, how="left")

    # overall across domains (optional)
    dom_cols = [c for c in out.columns if c.endswith("_weighted")]
    if dom_cols:
        out["ALL_DOMAINS_weighted"] = out[dom_cols].mean(axis=1)

    return out

In [139]:
# After you've filtered to base cols + PV cols
sch_perf_2018 = pisa_school_weighted_by_domain(stu_sea2018_selected)
sch_perf_2018['YEAR'] = 2018
sch_perf_2018

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,YEAR
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,2018
...,...,...,...,...,...,...,...
1281,THA,76400246.0,439.756900,379.971100,412.629000,410.785667,2018
1282,THA,76400182.0,518.481700,487.569600,502.820300,502.957200,2018
1283,THA,76400010.0,540.792800,437.241500,479.719700,485.918000,2018
1284,THA,76400098.0,479.335150,430.219950,504.743400,471.432833,2018
1285,THA,76400148.0,337.768750,350.921350,395.187700,361.292600,2018

## 2018 recomputed

In [140]:
COUNTRY_COL = "CNT"
WEIGHT_COL  = "W_FSTUWT"
DOMAINS     = ["MATH", "READ", "SCIE"]

def get_pv_cols(df, domain):
    pv = [c for c in df.columns if c.startswith("PV") and c.endswith(domain)]
    return sorted(pv, key=lambda x: int(x.replace("PV", "").replace(domain, "")))

def weighted_mean(values, weights):
    return (values * weights).sum() / weights.sum()

def pisa_country_means(stu_df):
    """
    Returns one row per CNT with T_bar (pooled PV mean) per domain.
    SE computation excluded — validate means against OECD report first.
    """
    df = stu_df.copy()
    df[WEIGHT_COL] = pd.to_numeric(df[WEIGHT_COL], errors="coerce")

    results = []

    for cnt, grp in df.groupby(COUNTRY_COL):
        row = {COUNTRY_COL: cnt}

        for domain in DOMAINS:
            pv_cols = get_pv_cols(grp, domain)
            if not pv_cols:
                continue

            w = grp[WEIGHT_COL]
            T_d_list = []

            # Step 1: one weighted mean per PV
            for pv in pv_cols:
                x    = pd.to_numeric(grp[pv], errors="coerce")
                mask = x.notna() & w.notna()
                T_d_list.append(weighted_mean(x[mask], w[mask]))

            # Step 2: pool → final country mean (T_bar)
            row[f"{domain}_mean"] = sum(T_d_list) / len(T_d_list)

        results.append(row)

    return pd.DataFrame(results)

In [141]:
country_means_2018 = pisa_country_means(stu_sea2018_selected)

In [142]:
country_means_2018.round(0)

   CNT  MATH_mean  READ_mean  SCIE_mean
0  BRN      430.0      408.0      431.0
1  IDN      379.0      371.0      396.0
2  MYS      440.0      415.0      438.0
3  PHL      353.0      340.0      357.0
4  SGP      569.0      549.0      551.0
5  THA      419.0      393.0      426.0

## 2022

In [146]:
df_stu_sea2022

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,ADMINMODE,LANGTEST_QQQ,LANGTEST_COG,LANGTEST_PAQ,Option_CT,Option_FL,Option_ICTQ,Option_WBQ,Option_PQ,Option_TQ,Option_UH,BOOKID,ST001D01T,ST003D02T,ST003D03T,ST004D01T,ST250Q01JA,ST250Q02JA,ST250Q03JA,ST250Q04JA,ST250Q05JA,ST250D06JA,ST250D07JA,ST251Q01JA,ST251Q02JA,ST251Q03JA,ST251Q04JA,ST251Q06JA,ST251Q07JA,ST251D08JA,ST251D09JA,ST253Q01JA,ST254Q01JA,ST254Q02JA,ST254Q03JA,ST254Q04JA,ST254Q05JA,ST254Q06JA,ST255Q01JA,ST256Q01JA,ST256Q02JA,ST256Q03JA,ST256Q06JA,ST256Q07JA,ST256Q08JA,ST256Q09JA,ST256Q10JA,ST230Q01JA,ST005Q01JA,ST006Q01JA,ST006Q02JA,ST006Q03JA,ST006Q04JA,ST006Q05JA,ST007Q01JA,ST008Q01JA,ST008Q02JA,ST008Q03JA,ST008Q04JA,ST008Q05JA,ST258Q01JA,ST259Q01JA,ST259Q02JA,ST019AQ01T,ST019BQ01T,ST019CQ01T,ST021Q01TA,ST022Q01TA,ST226Q01JA,ST125Q01NA,ST126Q01TA,ST127Q01TA,ST127Q02TA,ST127Q03TA,ST260Q01JA,ST260Q02JA,ST260Q03JA,ST261Q01JA,ST261Q02JA,ST261Q03JA,ST261Q04JA,ST261Q05JA,ST261Q06JA,ST261Q07JA,ST261Q08JA,ST261Q09JA,ST261Q10JA,ST261Q11JA,ST062Q01TA,ST062Q02TA,ST062Q03TA,ST267Q01JA,ST267Q02JA,ST267Q03JA,ST267Q04JA,ST267Q05JA,ST267Q06JA,ST267Q07JA,ST267Q08JA,ST034Q01TA,ST034Q02TA,ST034Q03TA,ST034Q04TA,ST034Q05TA,ST034Q06TA,ST038Q03NA,ST038Q04NA,ST038Q05NA,ST038Q06NA,ST038Q07NA,ST038Q08NA,ST038Q09JA,ST038Q10JA,ST038Q11JA,ST265Q01JA,ST265Q02JA,ST265Q03JA,ST265Q04JA,ST266Q01JA,ST266Q02JA,ST266Q03JA,ST266Q04JA,ST266Q05JA,ST294Q01JA,ST294Q02JA,ST294Q03JA,ST294Q04JA,ST294Q05JA,ST295Q01JA,ST295Q02JA,ST295Q03JA,ST295Q04JA,ST295Q05JA,ST326Q01JA,ST326Q02JA,ST326Q03JA,ST326Q04JA,ST326Q05JA,ST326Q06JA,ST326Q07JA,ST326Q08JA,ST326Q09JA,ST326Q10JA,ST326Q11JA,ST326Q12JA,ST322Q01JA,ST322Q02JA,ST322Q03JA,ST322Q04JA,ST322Q06JA,ST322Q07JA,ST307Q01JA,ST307Q02JA,ST307Q03JA,ST307Q04JA,ST307Q05JA,ST307Q06JA,ST307Q07JA,ST307Q08JA,ST307Q09JA,ST307Q10JA,ST309Q01JA,ST309Q02JA,ST309Q03JA,ST309Q04JA,ST309Q05JA,ST309Q06JA,ST309Q07JA,ST309Q08JA,ST309Q09JA,ST309Q10JA,ST301Q01JA,ST301Q02JA,ST301Q03JA,ST301Q04JA,ST301Q05JA,ST301Q06JA,ST301Q07JA,ST301Q08JA,ST301Q09JA,ST301Q10JA,ST343Q01JA,ST343Q02JA,ST343Q03JA,ST343Q04JA,ST343Q05JA,ST343Q06JA,ST343Q07JA,ST343Q08JA,ST343Q09JA,ST343Q10JA,ST311Q01JA,ST311Q02JA,ST311Q03JA,ST311Q04JA,ST311Q05JA,ST311Q06JA,ST311Q07JA,ST311Q08JA,ST311Q09JA,ST311Q10JA,ST315Q01JA,ST315Q02JA,ST315Q03JA,ST315Q04JA,ST315Q05JA,ST315Q06JA,ST315Q07JA,ST315Q08JA,ST315Q09JA,ST315Q10JA,ST303Q01JA,ST303Q02JA,ST303Q03JA,ST303Q04JA,ST303Q05JA,ST303Q06JA,ST303Q07JA,ST303Q08JA,ST305Q01JA,ST305Q02JA,ST305Q03JA,ST305Q04JA,ST305Q05JA,ST305Q06JA,ST305Q07JA,ST305Q08JA,ST305Q09JA,ST305Q10JA,ST345Q01JA,ST345Q02JA,ST345Q03JA,ST345Q04JA,ST345Q05JA,ST345Q06JA,ST345Q07JA,ST345Q08JA,ST345Q09JA,ST345Q10JA,ST313Q01JA,ST313Q02JA,ST313Q03JA,ST313Q04JA,ST313Q05JA,ST313Q06JA,ST313Q07JA,ST313Q08JA,ST313Q09JA,ST313Q10JA,ST263Q02JA,ST263Q04JA,ST263Q06JA,ST263Q08JA,ST016Q01NA,ST059Q01TA,ST059Q02JA,ST296Q01JA,ST296Q02JA,ST296Q03JA,ST296Q04JA,ST272Q01JA,ST273Q01JA,ST273Q02JA,ST273Q03JA,ST273Q04JA,ST273Q05JA,ST273Q06JA,ST273Q07JA,ST270Q01JA,ST270Q02JA,ST270Q03JA,ST270Q04JA,ST285Q01JA,ST285Q02JA,ST285Q03JA,ST285Q04JA,ST285Q05JA,ST285Q06JA,ST285Q07JA,ST285Q08JA,ST285Q09JA,ST283Q01JA,ST283Q02JA,ST283Q03JA,ST283Q04JA,ST283Q05JA,ST283Q06JA,ST283Q07JA,ST283Q08JA,ST283Q09JA,ST275Q01WA,ST275Q02WA,ST275Q03WA,ST275Q04WA,ST275Q05WA,ST275Q06WA,ST275Q07WA,ST275Q08WA,ST275Q09WA,ST276Q01JA,ST276Q02JA,ST276Q03JA,ST276Q04JA,ST276Q05JA,ST276Q06JA,ST276Q07JA,ST276Q08JA,ST276Q09JA,ST276Q10JA,ST268Q01JA,ST268Q02JA,ST268Q03JA,ST268Q04JA,ST268Q05JA,ST268Q06JA,ST268Q07JA,ST268Q08JA,ST268Q09JA,ST290Q01WA,ST290Q02WA,ST290Q03WA,ST290Q04WA,ST290Q05WA,ST290Q06WA,ST290Q07WA,ST290Q08WA,ST290Q09WA,ST291Q01JA,ST291Q02JA,ST291Q03JA,ST291Q04JA,ST291Q05JA,ST291Q06JA,ST291Q07JA,ST291Q08JA,ST291Q09JA,ST291Q10JA,ST289Q01WA,ST289Q02JA,ST289Q03WA,ST289Q04JA,ST289Q05WA,ST289Q06JA,ST289Q07JA,ST289Q08WA,ST289Q09WA,ST289Q10WA,ST289Q11WA,ST289Q14JA,ST293Q01JA,ST293Q02JA,ST293Q03JA,ST293Q04JA,ST293Q05JA,ST293Q06JA,ST293Q07JA,ST293Q08JA,ST293Q09JA,ST292Q01JA,ST292Q02JA,ST292Q03JA,ST292Q04JA,ST292Q05JA,ST292Q06JA,ST297Q01JA,ST297Q03JA,ST297Q05JA,ST297Q06JA,ST297Q07JA,ST297Q09JA,ST334Q01JA,ST334Q02JA,ST334Q03JA,ST334Q04JA,ST334Q05JA,ST334Q06JA,ST334Q07JA,ST334Q08JA,ST334Q09JA,ST334Q10JA,ST335Q01JA,ST335Q02JA,ST335Q03JA,ST335Q05JA,ST335Q06JA,ST335Q07JA,ST336Q01JA,ST336Q03JA,ST336Q04JA,ST336Q05JA,ST336Q06JA,ST336Q07JA,ST337Q01JA,ST337Q02JA,ST337Q03JA,ST337Q04JA,ST337Q05JA,ST337Q06JA,ST337Q07JA,ST337Q08JA,ST338Q01JA,ST338Q02JA,ST338Q03JA,ST338Q04JA,ST338Q05JA,ST338Q06JA,ST338Q07JA,ST338Q08JA,ST339Q04JA,ST339Q06JA,ST340Q01JA,ST340Q02JA,ST340Q03JA,ST340Q04JA,ST340Q05JA,ST340Q06JA,ST340Q07JA,ST340Q08JA,ST340Q09JA,ST340Q10JA,ST341Q01JA,ST341Q02JA,ST341Q03JA,ST341Q04JA,ST341Q05JA,ST342Q01JA,ST342Q02JA,ST342Q03JA,ST342Q04JA,ST342Q06JA,ST342Q07JA,ST342Q08JA,ST300Q01JA,ST300Q02JA,ST300Q03JA,ST300Q04JA,ST300Q05JA,ST300Q06JA,ST300Q07JA,ST300Q08JA,ST300Q09JA,ST300Q10JA,ST327Q01JA,ST327Q02JA,ST327Q03JA,ST327Q04JA,ST327Q05JA,ST327Q06JA,ST327Q07JA,ST327Q08JA,ST330Q01WA,ST330Q02WA,ST330Q03WA,ST330Q04WA,ST330Q05WA,ST330Q06WA,ST330Q07WA,ST330Q08WA,ST330Q09WA,ST330Q11WA,ST330D10WA,ST324Q02JA,ST324Q04JA,ST324Q05JA,ST324Q07JA,ST324Q10JA,ST324Q11JA,ST324Q12JA,ST324Q13JA,ST324Q14JA,ST347Q01JA,ST347Q02JA,ST348Q01JA,ST348Q02JA,ST348Q03JA,ST348Q04JA,ST348Q05JA,ST348Q06JA,ST348Q07JA,ST348Q08JA,ST349Q01JA,ST350Q01JA,ST351Q01JA,ST351Q02JA,ST351Q03JA,ST351Q04JA,ST351Q05JA,ST351Q06JA,ST351Q07JA,ST351Q08JA,ST352Q01JA,ST352Q02JA,ST352Q03JA,ST352Q04JA,ST352Q05JA,ST352Q06JA,ST352Q07JA,ST352Q08JA,ST353Q01JA,ST353Q02JA,ST353Q03JA,ST353Q04JA,ST353Q05JA,ST353Q06JA,ST353Q07JA,ST353Q08JA,ST354Q01JA,ST354Q02JA,ST354Q03JA,ST354Q04JA,ST354Q05JA,ST354Q06JA,ST354Q07JA,ST354Q08JA,ST354Q09JA,ST354Q10JA,ST355Q01JA,ST355Q02JA,ST355Q03JA,ST355Q04JA,ST355Q05JA,ST355Q06JA,ST355Q07JA,ST355Q08JA,ST356Q01JA,ST331Q01JA,ST331Q02JA,ST331Q03JA,FL150Q01TA,FL150Q02TA,FL150Q03TA,FL164Q01HA,FL164Q02HA,FL164Q03HA,FL164Q04HA,FL164Q05HA,FL164Q06HA,FL164Q07HA,FL164Q08HA,FL164Q09HA,FL164Q10HA,FL164Q11HA,FL164Q12HA,FL164Q13HA,FL164Q14HA,FL164Q15HA,FL164Q16HA,FL166Q01HA,FL166Q02HA,FL166Q03HA,FL166Q05HA,FL166Q06HA,FL166Q07HA,FL174Q01JA,FL174Q02JA,FL174Q03JA,FL174Q04JA,FL174Q05JA,FL174Q06JA,FL174Q07JA,FL167Q01HA,FL167Q02HA,FL167Q06JA,FL167Q03HA,FL167Q04HA,FL167Q05HA,FL167Q07JA,FL170Q01JA,FL170Q02JA,FL170Q03JA,FL170Q04JA,FL170Q05JA,FL170Q06JA,FL170Q07JA,FL159Q01HA,FL159Q02HA,FL159Q03HA,FL159Q04HA,FL160Q01HA,FL160Q02HA,FL160Q03HA,FL160Q04HA,FL161Q01HA,FL161Q02HA,FL161Q03HA,FL162Q01HA,FL162Q02HA,FL162Q03HA,FL162Q04HA,FL162Q05HA,FL162Q06HA,FL163Q01HA,FL163Q02HA,FL163Q03HA,FL163Q04HA,FL163Q05HA,FL171Q01JA,FL171Q02JA,FL171Q03JA,FL171Q04JA,FL171Q05JA,FL171Q07JA,FL171Q08JA,FL171Q09JA,FL171Q10JA,FL171Q11JA,FL171Q12JA,FL169Q01HA,FL169Q05JA,FL169Q02HA,FL169Q06JA,FL169Q07JA,FL169Q03HA,FL169Q04HA,FL169Q08JA,FL169Q10JA,FL169Q11JA,FL172Q01JA,FL172Q03JA,FL172Q05JA,FL172Q06JA,IC170Q01JA,IC170Q02JA,IC170Q03JA,IC170Q04JA,IC170Q05JA,IC170Q06JA,IC170Q07JA,IC171Q01JA,IC171Q02JA,IC171Q03JA,IC171Q04JA,IC171Q05JA,IC171Q06JA,IC172Q01JA,IC172Q02JA,IC172Q03JA,IC172Q04JA,IC172Q05JA,IC172Q06JA,IC172Q07JA,IC172Q08JA,IC172Q09JA,IC173Q01JA,IC173Q02JA,IC173Q03JA,IC173Q04JA,IC174Q01JA,IC174Q02JA,IC174Q03JA,IC174Q04JA,IC174Q05JA,IC174Q06JA,IC174Q07JA,IC174Q08JA,IC174Q09JA,IC174Q10JA,IC175Q01JA,IC175Q02JA,IC175Q03JA,IC175Q05JA,IC176Q01JA,IC176Q02JA,IC176Q03JA,IC176Q04JA,IC176Q05JA,IC176Q06JA,IC176Q07JA,IC176Q08JA,IC184Q01JA,IC184Q02JA,IC184Q03JA,IC184Q04JA,IC177Q01JA,IC177Q02JA,IC177Q03JA,IC177Q04JA,IC177Q05JA,IC177Q06JA,IC177Q07JA,IC178Q01JA,IC178Q02JA,IC178Q03JA,IC178Q04JA,IC178Q05JA,IC178Q06JA,IC178Q07JA,IC179Q01JA,IC179Q02JA,IC179Q03JA,IC179Q04JA,IC179Q05JA,IC179Q06JA,IC180Q01JA,IC180Q02JA,IC180Q03JA,IC180Q04JA,IC180Q05JA,IC180Q06JA,IC180Q07JA,IC180Q08JA,IC181Q01JA,IC181Q02JA,IC181Q03JA,IC181Q04JA,IC182Q01JA,IC182Q02JA,IC182Q03JA,IC183Q01JA,IC183Q02JA,IC183Q03JA,IC183Q04JA,IC183Q05JA,IC183Q07JA,IC183Q08JA,IC183Q09JA,IC183Q10JA,IC183Q12JA,IC183Q13JA,IC183Q14JA,IC183Q15JA,IC183Q16JA,WB150Q01HA,WB151Q01HA,WB152Q01HA,WB153Q01HA,WB153Q02HA,WB153Q03HA,WB153Q04HA,WB153Q05HA,WB154Q01HA,WB154Q02HA,WB154Q03HA,WB154Q04HA,WB154Q05HA,WB154Q06HA,WB154Q07HA,WB154Q08HA,WB154Q09HA,WB155Q01HA,WB155Q02HA,WB155Q03HA,WB155Q04HA,WB155Q05HA,WB155Q06HA,WB155Q07HA,WB155Q08HA,WB155Q09HA,WB155Q10HA,WB156Q01HA,WB158Q01HA,WB160Q01HA,WB161Q01HA,WB162Q01HA,WB162Q02HA,WB162Q03HA,WB162Q04HA,WB162Q05HA,WB162Q06HA,WB162Q07HA,WB162Q08HA,WB162Q09HA,WB163Q01HA,WB163Q02HA,WB163Q03HA,WB163Q04HA,WB163Q05HA,WB163Q06HA,WB163Q07HA,WB163Q08HA,WB164Q01HA,WB165Q01HA,WB166Q01HA,WB166Q02HA,WB166Q03HA,WB166Q04HA,WB167Q01HA,WB168Q01HA,WB168Q02HA,WB168Q03HA,WB168Q04HA,WB171Q01HA,WB171Q02HA,WB171Q03HA,WB171Q04HA,WB172Q01HA,WB173Q01HA,WB173Q02HA,WB173Q03HA,WB173Q04HA,WB176Q01HA,WB177Q01HA,WB177Q02HA,WB177Q03HA,WB177Q04HA,WB032Q01NA,WB032Q02NA,WB031Q01NA,WB178Q01HA,WB178Q02HA,WB178Q03HA,WB178Q04HA,WB178Q05HA,WB178Q06HA,WB178Q07HA,PA001Q01TA,PA001Q02TA,PA001Q03TA,PA003Q01TA,PA003Q02TA,PA003Q03TA,PA003Q05IA,PA003Q18WA,PA003Q19WA,PA003Q20WA,PA003Q11JA,PA003Q12JA,PA003Q13JA,PA003Q14JA,PA003Q15JA,PA003Q16JA,PA003Q17JA,PA196Q01WA,PA196Q02WA,PA196Q03WA,PA196Q04WA,PA197Q01WA,PA197Q02WA,PA197Q03WA,PA197Q04WA,PA197Q05WA,PA008Q01TA,PA008Q02TA,PA008Q03TA,PA008Q04TA,PA008Q05TA,PA008Q06NA,PA008Q07NA,PA008Q08NA,PA008Q09NA,PA008Q10NA,PA009Q01NA,PA009Q02NA,PA009Q03NA,PA009Q04NA,PA009Q05NA,PA009Q06NA,PA009Q07NA,PA009Q08NA,PA009Q09NA,PA009Q10NA,PA009Q11NA,PA007Q01TA,PA007Q02TA,PA007Q03TA,PA007Q04TA,PA007Q05TA,PA007Q06TA,PA007Q07TA,PA007Q09NA,PA007Q11NA,PA007Q12NA,PA007Q13NA,PA007Q14NA,PA007Q15NA,PA005Q01TA,PA006Q01TA,PA006Q02TA,PA006Q03TA,PA006Q04TA,PA006Q05TA,PA006Q06TA,PA006Q07TA,PA006Q08TA,PA006Q09TA,PA006Q10TA,PA006Q11TA,PA006Q12HA,PA006Q13HA,PA006Q14HA,PA166Q01HA,PA167Q02HA,PA167Q03HA,PA167Q04HA,PA167Q05HA,PA183Q01JA,PA183Q02JA,PA183Q03JA,PA183Q04JA,PA183Q05JA,PA183Q06JA,PA183Q07JA,PA183Q08JA,PA018Q01NA,PA018Q02NA,PA018Q03NA,PA177Q01HA,PA177Q02HA,PA177Q03HA,PA177Q04HA,PA177Q05HA,PA177Q06HA,PA177Q07HA,PA177Q08HA,PA180Q01HA,PA182Q01HA,PA175Q01HA,PA175Q02HA,PA175Q03JA,PA175Q04JA,PA185Q01JA,PA185Q02JA,PA185Q03JA,PA185Q04JA,PA185Q05JA,PA185Q07JA,PA185Q08JA,PA185Q09JA,PA185Q10JA,PA186Q01JA,PA186Q02JA,PA186Q03JA,PA186Q04JA,PA186Q05JA,PA186Q06JA,PA186Q07JA,PA186Q08JA,PA187Q04JA,PA187Q06JA,PA188Q01JA,PA188Q02JA,PA188Q03JA,PA188Q04JA,PA188Q05JA,PA188Q06JA,PA188Q08JA,PA188Q09JA,PA188Q10JA,PA189Q01JA,PA189Q02JA,PA189Q03JA,PA189Q04JA,PA189Q05JA,PA189Q06JA,PA189Q09JA,PA189Q10JA,PA194Q01JA,PA195Q01JA,PA041Q01TA,PA042Q01TA,EFFORT1,EFFORT2,OCOD1,OCOD2,OCOD3,PROGN,AGE,GRADE,ISCEDP,IMMIG,COBN_S,COBN_M,COBN_F,LANGN,REPEAT,MISSSC,SKIPPING,TARDYSD,EXERPRAC,STUDYHMW,WORKPAY,WORKHOME,EXPECEDU,MATHPREF,MATHEASE,MATHMOT,DURECEC,BSMJ,SISCO,RELATST,BELONG,BULLIED,FEELSAFE,SCHRISK,PERSEVAGR,CURIOAGR,COOPAGR,EMPATAGR,ASSERAGR,STRESAGR,EMOCOAGR,GROSAGR,INFOSEEK,FAMSUP,DISCLIM,TEACHSUP,COGACRCO,COGACMCO,EXPOFA,EXPO21ST,MATHEFF,MATHEF21,FAMCON,ANXMAT,MATHPERS,CREATEFF,CREATSCH,CREATFAM,CREATAS,CREATOOS,CREATOP,OPENART,IMAGINE,SCHSUST,LEARRES,PROBSELF,FAMSUPSL,FEELLAH,SDLEFF,MISCED,FISCED,HISCED,PAREDINT,BMMJ1,BFMJ2,HISEI,ICTRES,HOMEPOS,ESCS,FCFMLRTY,FLSCHOOL,FLMULTSB,FLFAMILY,ACCESSFP,FLCONFIN,FLCONICT,ACCESSFA,ATTCONFM,FRINFLFM,ICTSCH,ICTAVSCH,ICTHOME,ICTAVHOM,ICTQUAL,ICTSUBJ,ICTENQ,ICTFEED,ICTOUT,ICTWKDY,ICTWKEND,ICTREG,ICTINFO,ICTDISTR,ICTEFFIC,STUBMI,BODYIMA,SOCONPA,LIFESAT,PSYCHSYM,SOCCON,EXPWB,CURSUPP,PQMIMP,PQMCAR,PARINVOL,PQSCHOOL,PASCHPOL,ATTIMMP,PAREXPT,CREATHME,CREATACT,CREATOPN,CREATOR,W_FSTUWT,W_FSTURWT1,W_FSTURWT2,W_FSTURWT3,W_FSTURWT4,W_FSTURWT5,W_FSTURWT6,W_FSTURWT7,W_FSTURWT8,W_FSTURWT9,W_FSTURWT10,W_FSTURWT11,W_FSTURWT12,W_FSTURWT13,W_FSTURWT14,W_FSTURWT15,W_FSTURWT16,W_FSTURWT17,W_FSTURWT18,W_FSTURWT19,W_FSTURWT20,W_FSTURWT21,W_FSTURWT22,W_FSTURWT23,W_FSTURWT24,W_FSTURWT25,W_FSTURWT26,W_FSTURWT27,W_FSTURWT28,W_FSTURWT29,W_FSTURWT30,W_FSTURWT31,W_FSTURWT32,W_FSTURWT33,W_FSTURWT34,W_FSTURWT35,W_FSTURWT36,W_FSTURWT37,W_FSTURWT38,W_FSTURWT39,W_FSTURWT40,W_FSTURWT41,W_FSTURWT42,W_FSTURWT43,W_FSTURWT44,W_FSTURWT45,W_FSTURWT46,W_FSTURWT47,W_FSTURWT48,W_FSTURWT49,W_FSTURWT50,W_FSTURWT51,W_FSTURWT52,W_FSTURWT53,W_FSTURWT54,W_FSTURWT55,W_FSTURWT56,W_FSTURWT57,W_FSTURWT58,W_FSTURWT59,W_FSTURWT60,W_FSTURWT61,W_FSTURWT62,W_FSTURWT63,W_FSTURWT64,W_FSTURWT65,W_FSTURWT66,W_FSTURWT67,W_FSTURWT68,W_FSTURWT69,W_FSTURWT70,W_FSTURWT71,W_FSTURWT72,W_FSTURWT73,W_FSTURWT74,W_FSTURWT75,W_FSTURWT76,W_FSTURWT77,W_FSTURWT78,W_FSTURWT79,W_FSTURWT80,UNIT,WVARSTRR,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE,PV1MCCR,PV2MCCR,PV3MCCR,PV4MCCR,PV5MCCR,PV6MCCR,PV7MCCR,PV8MCCR,PV9MCCR,PV10MCCR,PV1MCQN,PV2MCQN,PV3MCQN,PV4MCQN,PV5MCQN,PV6MCQN,PV7MCQN,PV8MCQN,PV9MCQN,PV10MCQN,PV1MCSS,PV2MCSS,PV3MCSS,PV4MCSS,PV5MCSS,PV6MCSS,PV7MCSS,PV8MCSS,PV9MCSS,PV10MCSS,PV1MCUD,PV2MCUD,PV3MCUD,PV4MCUD,PV5MCUD,PV6MCUD,PV7MCUD,PV8MCUD,PV9MCUD,PV10MCUD,PV1MPEM,PV2MPEM,PV3MPEM,PV4MPEM,PV5MPEM,PV6MPEM,PV7MPEM,PV8MPEM,PV9MPEM,PV10MPEM,PV1MPFS,PV2MPFS,PV3MPFS,PV4MPFS,PV5MPFS,PV6MPFS,PV7MPFS,PV8MPFS,PV9MPFS,PV10MPFS,PV1MPIN,PV2MPIN,PV3MPIN,PV4MPIN,PV5MPIN,PV6MPIN,PV7MPIN,PV8MPIN,PV9MPIN,PV10MPIN,PV1MPRE,PV2MPRE,PV3MPRE,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT
0,BRN,96.0,9600021.0,9600001.0,08MS,009600,BRN02,0960000,9600.0,0.0,2.0,313.0,313.0,NaN,1.0,0.0,1.0,0.0,0.0,0.0,0.0,44.0,10.0,4.0,2006.0,2.0,2.0,2.0,2.0,1.0,2.0,0960002,0960002,4.0,1.0,4.0,4.0,2.0,1.0,0960001,0960001,5.0,3.0,NaN,1.0,1.0,1.0,4.0,7.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,1.0,1.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,1.0,NaN,2.0,5.0,3.0,1.0,1.0,1.0,NaN,2.0,4.0,5.0,7.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.0,NaN,2.0,NaN,2.0,4.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,5.0,1.0,2.0,6.0,2.0,4.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,4.0,NaN,4.0,NaN,1.0,NaN,NaN,4.0,4.0,2.0,NaN,NaN,NaN,2.0,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,4.0,4.0,4.0,4.0,NaN,NaN,5.0,NaN,5.0,1.0,NaN,NaN,1.0,NaN,5.0,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,4.0,4.0,4.0,1.0,4.0,NaN,4.0,NaN,4.0,4.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,1.0,5.0,5.0,NaN,1.0,4.0,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,1.0,1.0,5.0,NaN,4.0,4.0,4.0,4.0,1.0,4.0,5.0,NaN,NaN,NaN,NaN,6.0,3.0,4.0,4.0,4.0,NaN,NaN,4.0,1.0,1.0,1.0,1.0,3.0,NaN,3.0,NaN,NaN,3.0,NaN,5.0,5.0,5.0,NaN,NaN,NaN,NaN,1.0,5.0,5.0,5.0,3.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,3.0,3.0,3.0,2.0,4.0,4.0,4.0,4.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,3.0,NaN,2.0,2.0,NaN,3.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,5.0,1.0,3.0,NaN,2.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,4.0,4.0,NaN,4.0,4.0,NaN,4.0,NaN,NaN,3.0,3.0,3.0,3.0,NaN,3.0,3.0,1.0,NaN,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,2.0,3.0,1.0,1.0,2.0,1.0,NaN,1.0,1.0,4.0,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,5.0,NaN,5.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,0960002,4.0,NaN,4.0,NaN,NaN,1.0,NaN,4.0,3.0,5.0,1.0,1.0,4.0,4.0,NaN,4.0,NaN,4.0,NaN,2.0,1.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,NaN,4.0,4.0,4.0,NaN,NaN,NaN,4.0,4.0,1.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,4.0,4.0,NaN,4.0,NaN,NaN,3.0,NaN,NaN,3.0,3.0,NaN,3.0,2.0,NaN,2.0,NaN,3.0,1.0,7.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0,5.0,5.0,1.0,5.0,1.0,4.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,6.0,5.0,1.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,4.0,4.0,4.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,5.0,5.0,5.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,3339,5411,2149,00960004,16.17,0.0,344.0,1.0,009600,009600,009600,204.0,0.0,1.0,0.0,0.0,1.0,4.0,0.0,7.0,8.0,0.0,0.0,0.0,4.0,78.69,1.0,NaN,-1.0414,-1.2280,1.1246,-0.6386,NaN,NaN,NaN,NaN,NaN,0.5675,-0.7578,-3.5994,0.2743,-0.5551,1.3436,1.5558,0.4269,1.0939,1.3688,2.6159,-3.4762,0.3492,-3.0463,0.8918,2.1708,2.3208,0.5032,-1.1754,-0.0155,0.3331,-2.4637,-0.3378,NaN,0.4293,-2.7154,3.0179,-0.3759,NaN,-0.4825,10.0,7.0,10.0,16.0,59.89,46.38,59.89,-1.8963,-1.4556,-0.1936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4062,7.0,0.3346,6.0,0.1515,-1.0124,3.0231,2.9420,-0.8087,1.0713,3.8168,0.6912,0.1831,12.0,2.2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.04615,1.53435,1.55906,0.51145,1.55725,1.55639,1.55725,1.60800,0.52713,0.51908,1.58400,0.52756,0.51880,1.58015,1.60630,0.52756,0.53600,0.51938,0.52713,1.55814,0.51938,1.58015,1.55556,0.52672,1.60630,1.60800,1.55725,1.55639,0.52713,0.51908,1.53285,0.52672,0.53600,1.58268,1.55725,0.51111,0.51880,0.51880,0.52713,1.55639,0.51880,0.52672,0.53435,1.58015,0.51908,0.51938,0.51908,0.51880,1.58140,1.55725,0.52632,1.58015,1.55814,0.51145,0.51908,1.58015,1.55639,1.60465,1.53383,0.53488,1.55639,0.52756,0.51969,1.58268,0.51908,0.51880,0.53543,0.51938,1.53383,1.60630,0.52800,1.53435,1.55639,0.52672,0.51908,1.58268,1.55814,1.55814,1.58140,0.51938,1.60800,1.0,7.0,326.588,307.331,269.774,357.324,298.840,325.610,279.204,290.312,313.322,225.575,298.761,312.858,249.797,381.931,262.475,336.274,271.053,238.661,252.966,207.355,395.768,369.758,302.169,386.029,289.304,353.513,306.945,318.773,334.563,252.347,340.473,375.144,344.254,346.522,313.687,260.333,318.705,299.240,292.868,342.347,346.227,303.558,348.545,271.679,284.214,289.941,332.643,260.741,268.773,274.197,320.582,297.861,340.730,252.615,251.014,224.147,272.593,249.752,217.648,298.390,360.606,279.899,340.942,304.077,328.866,290.145,350.448,292.253,247.590,301.062,317.350,304.983,206.014,200.243,271.845,254.771,322.261,313.379,321.005,276.995,282.328,280.728,259.559,211.903,270.256,215.896,300.377,352.378,274.831,288.362,349.828,324.374,291.787,270.786,271.825,338.625,321.245,342.428,316.118,334.039,257.735,248.261,265.097,204.799,281.187,297.073,290.320,290.820,292.760,291.931,0.87471,02MAY23:08:34:58

In [144]:
stu_sea2022_selected = select_student_columns(df_stu_sea2022)
stu_sea2022_selected

,CNT,CNTSCHID,STRATUM,W_FSTUWT,PV1MATH,PV2MATH,PV3MATH,PV4MATH,PV5MATH,PV6MATH,PV7MATH,PV8MATH,PV9MATH,PV10MATH,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV6READ,PV7READ,PV8READ,PV9READ,PV10READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE,PV6SCIE,PV7SCIE,PV8SCIE,PV9SCIE,PV10SCIE
0,BRN,9600021.0,BRN02,1.04615,326.588,307.331,269.774,357.324,298.840,325.610,279.204,290.312,313.322,225.575,298.761,312.858,249.797,381.931,262.475,336.274,271.053,238.661,252.966,207.355,395.768,369.758,302.169,386.029,289.304,353.513,306.945,318.773,334.563,252.347
1,BRN,9600045.0,BRN11,1.20370,521.307,536.860,537.262,548.298,545.913,539.283,535.929,503.642,519.308,565.281,566.726,620.651,604.130,608.577,597.526,577.392,578.550,592.506,662.210,604.106,568.252,584.335,665.918,602.782,572.235,600.661,614.990,551.546,574.961,621.360
2,BRN,9600018.0,BRN02,1.04444,368.922,371.590,411.600,390.922,372.720,331.105,409.375,393.753,360.681,353.057,327.274,377.068,397.876,333.849,365.232,312.419,412.081,391.788,348.772,376.880,387.319,378.118,408.698,401.188,386.369,317.698,409.946,408.143,304.877,356.823
3,BRN,9600006.0,BRN02,1.02041,443.209,452.860,447.634,379.558,444.950,405.125,412.647,412.144,408.821,423.827,421.751,435.065,441.736,413.615,442.944,429.153,413.410,404.898,426.733,408.355,488.964,464.733,447.824,415.271,462.583,398.691,407.210,429.135,426.988,454.408
4,BRN,9600004.0,BRN02,1.01639,395.945,404.269,365.507,411.916,392.963,426.954,358.419,355.583,417.385,343.157,382.723,304.200,339.186,374.003,341.419,330.676,314.854,360.638,392.653,321.743,352.061,301.725,315.402,395.130,379.131,410.635,290.765,296.562,404.750,312.479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59720,THA,76400011.0,THA97,141.41500,324.790,380.214,301.642,310.815,269.539,370.052,387.927,384.559,323.486,321.281,327.912,351.233,371.526,295.154,283.041,295.943,334.797,378.849,303.026,354.970,356.854,331.078,329.270,327.338,313.316,306.960,354.646,365.164,328.214,311.617
59721,THA,76400075.0,THA97,3.88095,528.037,560.733,567.615,574.489,567.990,562.738,531.740,560.207,579.549,542.980,512.949,570.034,579.537,570.115,536.428,500.262,469.462,546.447,519.212,493.195,559.840,586.912,623.375,593.423,597.944,591.011,561.807,592.770,578.720,556.611
59722,THA,76400167.0,THA97,100.53930,388.109,370.563,388.613,371.833,398.949,404.158,374.179,418.344,389.293,356.287,381.011,322.272,330.374,381.478,377.961,361.018,344.384,439.399,382.623,368.162,424.525,344.467,410.838,370.624,456.336,396.479,378.522,412.129,354.065,395.264
59723,THA,76400258.0,THA97,71.78788,401.596,386.838,422.284,385.798,412.738,363.277,365.045,303.000,380.288,379.072,368.361,383.647,327.888,355.271,339.684,372.216,307.399,297.984,359.099,343.715,378.856,406.576,435.788,394.172,402.851,372.515,371.393,418.982,426.134,377.490
59724,THA,76400067.0,THA97,83.06088,498.849,532.447,489.281,491.130,470.224,547.614,553.389,491.672,503.700,550.916,530.119,505.337,502.341,485.424,477.933,509.750,516.515,469.057,485.740,555.398,550.785,503.490,582.927,587.115,524.562,599.516,575.282,536.238,545.066,551.229

In [145]:
country_means_2022 = pisa_country_means(stu_sea2022_selected)
country_means_2022.round(0)

   CNT  MATH_mean  READ_mean  SCIE_mean
0  BRN      442.0      429.0      446.0
1  IDN      366.0      359.0      383.0
2  KHM      336.0      329.0      347.0
3  MYS      409.0      388.0      416.0
4  PHL      355.0      347.0      356.0
5  SGP      575.0      543.0      561.0
6  THA      394.0      379.0      409.0
7  VNM      469.0      462.0      472.0

In [147]:
stu_sea2022_selected.isna().sum()

CNT         0
CNTSCHID    0
STRATUM     0
W_FSTUWT    0
PV1MATH     0
PV2MATH     0
PV3MATH     0
PV4MATH     0
PV5MATH     0
PV6MATH     0
PV7MATH     0
PV8MATH     0
PV9MATH     0
PV10MATH    0
PV1READ     0
PV2READ     0
PV3READ     0
PV4READ     0
PV5READ     0
PV6READ     0
PV7READ     0
PV8READ     0
PV9READ     0
PV10READ    0
PV1SCIE     0
PV2SCIE     0
PV3SCIE     0
PV4SCIE     0
PV5SCIE     0
PV6SCIE     0
PV7SCIE     0
PV8SCIE     0
PV9SCIE     0
PV10SCIE    0
dtype: int64

In [148]:
sch_perf_2022 = pisa_school_weighted_by_domain(stu_sea2022_selected)
sch_perf_2022['YEAR'] = 2022
sch_perf_2022

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,YEAR
0,BRN,9600021.0,387.749419,358.354188,384.540609,376.881405,2022
1,BRN,9600045.0,559.595745,563.132004,567.806113,563.511287,2022
2,BRN,9600018.0,424.889844,412.270348,433.630417,423.596870,2022
3,BRN,9600006.0,412.100736,390.800801,411.377292,404.759610,2022
4,BRN,9600004.0,403.104819,378.120677,396.360861,392.528786,2022
...,...,...,...,...,...,...,...
1650,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,2022
1651,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,2022
1652,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,2022
1653,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,2022
1654,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,2022

In [149]:
sch_perf_combined = pd.concat(
    [sch_perf_2018, sch_perf_2022],
    ignore_index=True
)

In [150]:
sch_perf_combined

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,YEAR
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,2018
...,...,...,...,...,...,...,...
2936,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,2022
2937,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,2022
2938,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,2022
2939,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,2022
2940,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,2022

In [151]:
# # save school perf

# sch_perf_combined.to_csv("../data/processed/sch_perf_combined.csv", index=False)

## Combined school perf and original imputed data

In [153]:
# df_2018 = pd.read_csv("../data/processed/sch_sea2018_imputed.csv")
# df_2022 = pd.read_csv("../data/processed/sch_sea2022_imputed.csv")

df_2018 = sch_sea2018_imputed
df_2022 = sch_sea2022_imputed

sch_sea2018_imputed = df_2018.copy()
sch_sea2022_imputed = df_2022.copy()

In [154]:
sch_2018_final_orig = sch_perf_2018.merge(
    sch_sea2018_imputed,
    on=["CNT", "CNTSCHID"],
    how="left"
)

In [155]:
sch_2018_final_orig.shape

(1286, 82)

In [156]:
sch_2022_final_orig = sch_perf_2022.merge(
    sch_sea2022_imputed,
    on=["CNT", "CNTSCHID"],
    how="left"
)

In [157]:
sch_2022_final_orig.shape

(1655, 82)

In [158]:
sch_combined_final_orig = pd.concat(
    [sch_2018_final_orig, sch_2022_final_orig],
    ignore_index=True
)

In [159]:
sch_combined_final_orig

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,YEAR_x,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,YEAR_y
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,2018,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,2018,BRN0305,1.0,1.0,90.0,10.0,0.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,3.0,1.0,0.0,1557.0,263.0,25.0,25.0,0.0,54.0,136.0,136.0,0.0,106.0,0.0,70.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,80.0,80.0,80.0,80.0,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,2018,BRN0108,2.0,2.0,0.0,80.0,20.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,532.0,515.0,43.0,80.0,80.0,0.0,35.0,80.0,74.0,0.0,74.0,0.0,2.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,10.0,90.0,2.0,1.0,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,2018,BRN0202,2.0,1.0,17.0,44.0,20.0,19.0,3.0,1.0,3.0,1.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,1.0,3.0,3.0,3.0,503.0,354.0,181.0,50.0,50.0,5.0,15.0,5.0,106.0,0.0,98.0,0.0,75.0,3.0,1.0,2.0,1.0,2.0,1.0,1.0,15.0,5.0,2.0,5.0,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,2018,BRN0202,4.0,1.0,70.0,10.0,10.0,10.0,2.0,1.0,4.0,3.0,2.0,3.0,3.0,4.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,605.0,336.0,187.0,60.0,60.0,9.0,20.0,18.0,124.0,0.0,124.0,0.0,75.0,3.0,1.0,2.0,2.0,2.0,1.0,1.0,25.0,40.0,5.0,1.0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2936,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,2022,THA97,1.0,1.0,95.0,0.0,5.0,0.0,3.0,1.0,4.0,1.0,3.0,3.0,1.0,1.0,4.0,2.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,101.0,84.0,18.0,20.0,20.0,1.0,4.0,6.0,18.0,0.0,17.0,0.0,100.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,100.0,100.0,100.0,100.0,2022
2937,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,2022,THA97,1.0,1.0,99.0,0.0,1.0,0.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,86.0,73.0,7.0,9.0,9.0,0.0,3.0,10.0,13.0,4.0,13.0,4.0,90.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,100.0,64.0,16.0,2022
2938,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,2022,THA97,1.0,1.0,100.0,0.0,0.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,4.0,115.0,87.0,27.0,16.0,16.0,0.0,1.0,11.0,17.0,0.0,17.0,0.0,50.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,50.0,50.0,50.0,50.0,2022
2939,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,2022,THA97,1.0,1.0,90.0,0.0,10.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,60.0,45.0,16.0,9.0,9.0,0.0,2.0,6.0,15.0,2.0,15.0,1.0,80.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,50.0,80.0,80.0,80.0,2022
2940,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,2022,THA97,1.0,1.0,100.0,0.0,0.0,0.0,3.0,4.0,4.0,1.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,114.0,89.0,12.0,15.0,11.0,0.0,2.0,15.0,15.0,0.0,15.0,0.0,100.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,69.0,57.0,29.0,22.0,2022

In [160]:
# # save final original data

# sch_combined_final_orig.to_csv("../data/processed/sch_combined_final_orig.csv", index=False)

## Combined school perf and transformed data

In [161]:
# sch_combined_transformed = sch_combined_transformed.drop(columns='YEAR')

In [162]:
sch_2018_final_transformed = sch_perf_2018.merge(
    sch_combined_transformed[sch_combined_transformed['YEAR']== 2018],
    on=["CNT", "CNTSCHID"],
    how="left"
)

sch_2022_final_transformed = sch_perf_2022.merge(
    sch_combined_transformed[sch_combined_transformed['YEAR']== 2022],
    on=["CNT", "CNTSCHID"],
    how="left"
)

In [163]:
sch_2018_final_transformed['YEAR'] = sch_2018_final_transformed['YEAR_x']
sch_2018_final_transformed = sch_2018_final_transformed.drop(columns=['YEAR_x', 'YEAR_y'])

In [164]:
sch_2018_final_transformed

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,STRATUM,SC013Q01TA,SC037Q02TA,SC061Q01TA,SC025Q01NA,EXT_FUND,EDU_MAT,EDU_INFRA,DIGI_CAP,STU_TCH,STU_COMP,TCH_COMP,X_ACTIV,PRNT_ENG,YEAR
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,BRN0202,1.0,1.0,2.0,100.0,73.0,2.0,2.0,3.0,9.2586,2.1200,3.8667,5.0,25.50,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,BRN0305,1.0,1.0,2.0,70.0,10.0,1.0,1.0,3.0,11.4485,10.5200,1.0000,4.0,80.00,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,BRN0108,2.0,3.0,2.0,2.0,100.0,1.0,1.0,3.0,14.1486,0.5375,0.9250,4.0,25.75,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,BRN0202,1.0,1.0,3.0,75.0,83.0,3.0,4.0,3.0,8.0849,3.6200,21.2000,4.0,6.75,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,BRN0202,1.0,1.0,2.0,75.0,30.0,3.0,4.0,2.0,7.5887,3.1167,6.8889,3.0,17.75,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1281,THA,76400246.0,439.756900,379.971100,412.629000,410.785667,THA9797,1.0,1.0,2.0,84.0,10.0,2.0,3.0,2.0,10.8947,0.4167,1.5833,6.0,33.75,2018
1282,THA,76400182.0,518.481700,487.569600,502.820300,502.957200,THA9797,1.0,1.0,3.0,85.0,0.0,4.0,3.0,3.0,11.2903,1.5000,2.5833,5.0,80.75,2018
1283,THA,76400010.0,540.792800,437.241500,479.719700,485.918000,THA9797,2.0,1.0,1.0,80.0,40.0,2.0,2.0,3.0,24.5833,4.3000,4.0000,4.0,91.25,2018
1284,THA,76400098.0,479.335150,430.219950,504.743400,471.432833,THA9797,1.0,1.0,1.0,100.0,32.0,2.0,3.0,3.0,8.3333,1.1000,1.0000,4.0,28.75,2018
1285,THA,76400148.0,337.768750,350.921350,395.187700,361.292600,THA9797,1.0,1.0,2.0,85.0,5.0,3.0,3.0,2.0,16.1000,1.8750,2.0000,3.0,21.50,2018

In [165]:
sch_2022_final_transformed['YEAR'] = sch_2022_final_transformed['YEAR_x']
sch_2022_final_transformed = sch_2022_final_transformed.drop(columns=['YEAR_x', 'YEAR_y'])

In [166]:
sch_2022_final_transformed

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,STRATUM,SC013Q01TA,SC037Q02TA,SC061Q01TA,SC025Q01NA,EXT_FUND,EDU_MAT,EDU_INFRA,DIGI_CAP,STU_TCH,STU_COMP,TCH_COMP,X_ACTIV,PRNT_ENG,YEAR
0,BRN,9600021.0,387.749419,358.354188,384.540609,376.881405,BRN02,1.0,2.0,2.0,60.0,2.0,2.0,2.0,3.0,6.4078,1.6341,1.1573,4.0,7.25,2022
1,BRN,9600045.0,559.595745,563.132004,567.806113,563.511287,BRN11,2.0,2.0,1.0,100.0,100.0,1.0,1.0,3.0,8.4061,0.4825,0.6567,6.0,28.00,2022
2,BRN,9600018.0,424.889844,412.270348,433.630417,423.596870,BRN02,1.0,1.0,3.0,99.0,77.0,2.0,3.0,3.0,7.7117,3.4600,2.4667,4.0,41.25,2022
3,BRN,9600006.0,412.100736,390.800801,411.377292,404.759610,BRN02,1.0,1.0,2.0,95.0,20.0,2.0,1.0,3.0,9.4430,2.4800,0.9875,5.0,13.75,2022
4,BRN,9600004.0,403.104819,378.120677,396.360861,392.528786,BRN02,1.0,2.0,2.0,100.0,40.0,3.0,3.0,3.0,8.8701,3.1000,1.0000,5.0,22.50,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,THA97,1.0,1.0,2.0,100.0,5.0,3.0,1.0,3.0,10.2778,0.9000,3.0000,4.0,100.00,2022
1651,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,THA97,1.0,1.0,2.0,90.0,1.0,4.0,4.0,4.0,10.6000,0.7778,1.5000,5.0,45.25,2022
1652,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,THA97,1.0,1.0,3.0,50.0,0.0,3.0,3.0,2.0,11.8824,1.6875,1.5455,3.0,50.00,2022
1653,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,THA97,1.0,1.0,2.0,80.0,10.0,1.0,1.0,3.0,6.5625,1.7778,2.6667,5.0,72.50,2022
1654,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,THA97,1.0,1.0,2.0,100.0,0.0,2.0,2.0,3.0,13.5333,1.0909,1.0000,5.0,44.25,2022

In [167]:
sch_combined_final_transformed = pd.concat(
    [sch_2018_final_transformed, sch_2022_final_transformed],
    ignore_index=True
)

In [168]:
sch_combined_final_transformed

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,STRATUM,SC013Q01TA,SC037Q02TA,SC061Q01TA,SC025Q01NA,EXT_FUND,EDU_MAT,EDU_INFRA,DIGI_CAP,STU_TCH,STU_COMP,TCH_COMP,X_ACTIV,PRNT_ENG,YEAR
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,BRN0202,1.0,1.0,2.0,100.0,73.0,2.0,2.0,3.0,9.2586,2.1200,3.8667,5.0,25.50,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,BRN0305,1.0,1.0,2.0,70.0,10.0,1.0,1.0,3.0,11.4485,10.5200,1.0000,4.0,80.00,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,BRN0108,2.0,3.0,2.0,2.0,100.0,1.0,1.0,3.0,14.1486,0.5375,0.9250,4.0,25.75,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,BRN0202,1.0,1.0,3.0,75.0,83.0,3.0,4.0,3.0,8.0849,3.6200,21.2000,4.0,6.75,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,BRN0202,1.0,1.0,2.0,75.0,30.0,3.0,4.0,2.0,7.5887,3.1167,6.8889,3.0,17.75,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2936,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,THA97,1.0,1.0,2.0,100.0,5.0,3.0,1.0,3.0,10.2778,0.9000,3.0000,4.0,100.00,2022
2937,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,THA97,1.0,1.0,2.0,90.0,1.0,4.0,4.0,4.0,10.6000,0.7778,1.5000,5.0,45.25,2022
2938,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,THA97,1.0,1.0,3.0,50.0,0.0,3.0,3.0,2.0,11.8824,1.6875,1.5455,3.0,50.00,2022
2939,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,THA97,1.0,1.0,2.0,80.0,10.0,1.0,1.0,3.0,6.5625,1.7778,2.6667,5.0,72.50,2022
2940,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,THA97,1.0,1.0,2.0,100.0,0.0,2.0,2.0,3.0,13.5333,1.0909,1.0000,5.0,44.25,2022

In [169]:
# # save final transformed data

# sch_combined_final_transformed.to_csv("../data/processed/sch_combined_final_transformed.csv", index=False)

In [170]:
sch_combined_final_orig

,CNT,CNTSCHID,PVMATH_weighted,PVREAD_weighted,PVSCIE_weighted,ALL_DOMAINS_weighted,YEAR_x,STRATUM,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC042Q01TA,SC042Q02TA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC025Q01NA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q09TA,SC053Q10TA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,YEAR_y
0,BRN,9600004.0,379.067386,347.880933,372.468728,366.472349,2018,BRN0202,2.0,1.0,27.0,51.0,1.0,21.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,562.0,512.0,212.0,113.0,100.0,11.0,25.0,30.0,115.0,2.0,115.0,2.0,100.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,20.0,2.0,2018
1,BRN,9600039.0,449.347079,433.233092,438.165721,440.248631,2018,BRN0305,1.0,1.0,90.0,10.0,0.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,3.0,1.0,0.0,1557.0,263.0,25.0,25.0,0.0,54.0,136.0,136.0,0.0,106.0,0.0,70.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,80.0,80.0,80.0,80.0,2018
2,BRN,9600013.0,501.147131,478.563343,517.555315,499.088596,2018,BRN0108,2.0,2.0,0.0,80.0,20.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,532.0,515.0,43.0,80.0,80.0,0.0,35.0,80.0,74.0,0.0,74.0,0.0,2.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,10.0,90.0,2.0,1.0,2018
3,BRN,9600050.0,378.841053,358.139932,378.362731,371.781239,2018,BRN0202,2.0,1.0,17.0,44.0,20.0,19.0,3.0,1.0,3.0,1.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,1.0,3.0,3.0,3.0,503.0,354.0,181.0,50.0,50.0,5.0,15.0,5.0,106.0,0.0,98.0,0.0,75.0,3.0,1.0,2.0,1.0,2.0,1.0,1.0,15.0,5.0,2.0,5.0,2018
4,BRN,9600027.0,395.449849,370.716459,399.513442,388.559917,2018,BRN0202,4.0,1.0,70.0,10.0,10.0,10.0,2.0,1.0,4.0,3.0,2.0,3.0,3.0,4.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,605.0,336.0,187.0,60.0,60.0,9.0,20.0,18.0,124.0,0.0,124.0,0.0,75.0,3.0,1.0,2.0,2.0,2.0,1.0,1.0,25.0,40.0,5.0,1.0,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2936,THA,76400065.0,317.759668,306.091416,359.336916,327.729333,2022,THA97,1.0,1.0,95.0,0.0,5.0,0.0,3.0,1.0,4.0,1.0,3.0,3.0,1.0,1.0,4.0,2.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,101.0,84.0,18.0,20.0,20.0,1.0,4.0,6.0,18.0,0.0,17.0,0.0,100.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,100.0,100.0,100.0,100.0,2022
2937,THA,76400094.0,310.692267,314.832800,291.748833,305.757967,2022,THA97,1.0,1.0,99.0,0.0,1.0,0.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,3.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,86.0,73.0,7.0,9.0,9.0,0.0,3.0,10.0,13.0,4.0,13.0,4.0,90.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,100.0,64.0,16.0,2022
2938,THA,76400133.0,432.563525,315.122625,377.528200,375.071450,2022,THA97,1.0,1.0,100.0,0.0,0.0,0.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,4.0,115.0,87.0,27.0,16.0,16.0,0.0,1.0,11.0,17.0,0.0,17.0,0.0,50.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,50.0,50.0,50.0,50.0,2022
2939,THA,76400070.0,390.990900,348.765200,416.199200,385.318433,2022,THA97,1.0,1.0,90.0,0.0,10.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,60.0,45.0,16.0,9.0,9.0,0.0,2.0,6.0,15.0,2.0,15.0,1.0,80.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,50.0,80.0,80.0,80.0,2022
2940,THA,76400021.0,462.332000,405.136400,440.088700,435.852367,2022,THA97,1.0,1.0,100.0,0.0,0.0,0.0,3.0,4.0,4.0,1.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,114.0,89.0,12.0,15.0,11.0,0.0,2.0,15.0,15.0,0.0,15.0,0.0,100.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,69.0,57.0,29.0,22.0,2022